Initiate Types Rule Package and Implement MISRA RULE-6-1
github/codeql-coding-standards pull request #174
Opened 2023-01-26 21:12 UTC by jeongsoolee09

## Description

Implemented MISRA's RULE-6-1: *Bit-fields shall only be declared with an appropriate type*.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [X] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [X] Queries have been added for the following rules:
     - RULE-6-1
 - [ ] Queries have been modified for the following rules:
     - _rule number here_

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [ ] Yes
  - [X] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [X] Have all the relevant rule package description files been checked in?
 - [X] Have you verified that the metadata properties of each new query is set appropriately?
 - [X] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [X] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [X] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [X] Does the query have an appropriate level of in-query comments/documentation?
 - [X] Have you considered/identified possible edge cases?
 - [X] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2023-01-26 21:19 UTC, jeongsoolee09 commented
The suggested `cert-help-extraction.py` seems to have a bug.

```
√ codeql-coding-standards % python3.9 scripts/help/cert-help-extraction.py 
ID: ARR39-C - Converting contents at https://wiki.sei.cmu.edu/confluence/display/c/ARR39-C.+Do+not+add+or+subtract+a+scaled+integer+to+a+pointer into Markdown help file for DoNotAddOrSubtractAScaledIntegerToAPointer
ID: ARR39-C - Didn't find heading 'CERT', going to update the headings 'Noncompliant Code Example, Compliant Solution, Related Vulnerabilities, Automated Detection, Risk Assessment, Description, Related Guidelines, Bibliography'.
ID: CON30-C - Converting contents at https://wiki.sei.cmu.edu/confluence/display/c/CON30-C.+Clean+up+thread-specific+storage into Markdown help file for CleanUpThreadSpecificStorage
ID: CON30-C - Didn't find heading 'CERT', going to update the headings 'Noncompliant Code Example, Compliant Solution, Related Vulnerabilities, Automated Detection, Risk Assessment, Description'.
ID: CON31-C - Converting contents at https://wiki.sei.cmu.edu/confluence/display/c/CON31-C.+Do+not+destroy+a+mutex+while+it+is+locked into Markdown help file for DoNotAllowAMutexToGoOutOfScopeWhileLocked
ID: CON31-C - Didn't find heading 'CERT', going to update the headings 'Noncompliant Code Example, Compliant Solution, Related Vulnerabilities, Automated Detection, Risk Assessment, Description, Related Guidelines, Bibliography, CERT-CWE Mapping Notes'.
ID: CON31-C - Converting contents at https://wiki.sei.cmu.edu/confluence/display/c/CON31-C.+Do+not+destroy+a+mutex+while+it+is+locked into Markdown help file for DoNotDestroyAMutexWhileItIsLocked
ID: CON31-C - Didn't find heading 'CERT', going to update the headings 'Noncompliant Code Example, Compliant Solution, Related Vulnerabilities, Automated Detection, Risk Assessment, Description, Related Guidelines, Bibliography, CERT-CWE Mapping Notes'.
ID: CON32-C - Converting contents at https://wiki.sei.cmu.edu/confluence/display/c/CON32-C.+Prevent+data+races+when+accessing+bit-fields+from+multiple+threads into Markdown help file for PreventDataRacesWithMultipleThreads
ID: CON32-C - Didn't find heading 'CERT', going to update the headings 'Related Vulnerabilities, Compliant Solution (Bit-field, C11, Mutex), Automated Detection, Risk Assessment, Description, Compliant Solution (C11), Bibliography, Noncompliant Code Example (Bit-field)'.
ID: CON33-C - Converting contents at https://wiki.sei.cmu.edu/confluence/display/c/CON33-C.+Avoid+race+conditions+when+using+library+functions into Markdown help file for RaceConditionsWhenUsingLibraryFunctions
ID: CON33-C - Didn't find heading 'CERT', going to update the headings 'Noncompliant Code Example, Compliant Solution (Annex K, strerror_s()), Related Vulnerabilities, Automated Detection, Risk Assessment, Description, Related Guidelines, Bibliography, Compliant Solution (POSIX, strerror_r()), CERT-CWE Mapping Notes'.
ID: CON34-C - Converting contents at https://wiki.sei.cmu.edu/confluence/display/c/CON34-C.+Declare+objects+shared+between+threads+with+appropriate+storage+durations into Markdown help file for AppropriateThreadObjectStorageDurations
Traceback (most recent call last):
  File "/Users/jslee/Work/WorkRepos/codeql-coding-standards/scripts/help/cert-help-extraction.py", line 526, in <module>
    if find_heading(parsed_help, 'CERT'):
  File "/Users/jslee/Work/WorkRepos/codeql-coding-standards/scripts/shared/markdown_helpers.py", line 98, in find_heading
    if get_heading_text(h) == heading:
  File "/Users/jslee/Work/WorkRepos/codeql-coding-standards/scripts/shared/markdown_helpers.py", line 108, in get_heading_text
    return heading.children[0].children
IndexError: list index out of range
```

2023-01-27 14:28 UTC, lcartey commented
@jeongsoolee09 Can you please create a new package for your two rules? We don't want to generate and commit files for all 30 rules in the Types package, as we are not going to implement all of them.

I would recommend calling the new package `BitfieldTypes`. You can create it like this:

 1. Update `rules.csv` so that Rule 6.1 and Rule 6.2 are assigned to the new package (`BitfieldTypes`).
 2. Generate the BitfieldTypes c package description file.
 3. Copy any changes you made for Rule 6.1 and Rule 6.2 from the existing `Types.json` to the `BitfieldTypes.json`.
 4. Generate the package files for the new package.
 5. Delete any files from the types package.

Thanks!

2023-01-27 17:43 UTC, jeongsoolee09 commented
I am changing this PR to draft to accommodate RULE-6-2 as well.

2023-01-27 22:12 UTC, jeongsoolee09 commented
Undone `Types` and made a small rule package called `BitfieldTypes`.

2023-01-31 18:19 UTC, lcartey requested changes
Looks good, just a couple of changes.

2023-01-31 18:19 UTC, lcartey commented on c/misra/src/rules/RULE-6-2/SingleBitNamedBitFieldsOfASignedType.ql
> +  type.(IntegralType).isExplicitlySigned()
Use isSigned instead.

2023-01-31 18:19 UTC, lcartey commented on c/misra/src/rules/RULE-6-2/SingleBitNamedBitFieldsOfASignedType.ql
> +  type instanceof FixedWidthIntegralType or
I don't think we need this condition.

2023-01-31 18:19 UTC, lcartey commented on c/misra/src/rules/RULE-6-2/SingleBitNamedBitFieldsOfASignedType.ql
> +predicate isSigned(Type type) {
I think you will be able to inline this predicate once you simplify it.

2023-01-31 18:19 UTC, lcartey commented on c/misra/src/rules/RULE-6-2/SingleBitNamedBitFieldsOfASignedType.ql
> +predicate isSingleBit(BitField bitField) {
I think you can inline this predicate

2023-01-31 18:20 UTC, lcartey commented on rule_packages/c/Types.json
> +{
Delete this file, regenerate the `BitfieldTypes` package, and delete the excess tests.

2023-02-01 01:07 UTC, jeongsoolee09 commented
We can ignore implementation-specific integer types: [GCC](https://gcc.gnu.org/onlinedocs/gcc-8.5.0/gcc/C-Implementation.html#C-Implementation) and [Clang](https://releases.llvm.org/10.0.0/tools/clang/docs/LanguageExtensions.html) does not define any additional types that are equivalent to `int`.

2023-02-01 19:00 UTC, jeongsoolee09 commented on c/misra/src/rules/RULE-6-1/BitFieldsShallOnlyBeDeclaredWithAnAppropriateType.ql
> +    isAppropriatePrimitive(bitField.getType()) or
Didn't know that resolveTypedefs is an identity operation on types that have no aliases.

2023-02-02 09:05 UTC, lcartey approved these changes

2023-02-02 09:05 UTC, merged

2023-02-03 01:29 UTC, rvermeulen commented on c/misra/test/rules/RULE-6-2/test.c
> +  int x1 : 1; // NON_COMPILANT: very likely be signed, but if it's not, the
NON_COMPLIANT