Fix "modernize qlpacks"
github/codeql-coding-standards pull request #179
Opened 2023-02-02 10:07 UTC by jketema

## Description

_please enter the description of your change here_

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [ ] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [ ] Queries have been modified for the following rules:
     - _rule number here_

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [ ] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2023-02-04 00:18 UTC, rvermeulen requested changes
Exciting update.
A few suggestions to make full use of the new CodeQL pack specification.

I vaguely recall there was a reason we didn't use the `codeql-workspace.yml` that I suggested not sure anymore. So need to look into that before we go forward with that suggestion.

2023-02-04 00:18 UTC, rvermeulen commented on cpp/autosar/src/qlpack.yml
> +dependencies:
We should add the `defaultSuiteFile`, `suites`, `license`, and `description` properties.

The `defaultSuiteFile` helps with running the default selected suite when our package is provided to `codeql database analyze` and the `suites` informs the CodeQL cli of the possible suites and turns them into well-known suites so you can run them without providing the full path.

2023-02-04 00:18 UTC, rvermeulen commented on c/cert/src/qlpack.yml
> +dependencies:
We should add the `defaultSuiteFile`, `suites`, `license`, and `description` properties.

The `defaultSuiteFile` helps with running the default selected suite when our package is provided to `codeql database analyze` and the `suites` informs the CodeQL cli of the possible suites and turns them into well-known suites so you can run them without providing the full path.

2023-02-04 00:18 UTC, rvermeulen commented on c/cert/test/qlpack.yml
> +extractor: cpp
```suggestion
extractor: cpp
license: MIT
```

2023-02-04 00:18 UTC, rvermeulen commented on c/common/src/qlpack.yml
> +  codeql/cpp-all: 0.2.3
```suggestion
  codeql/cpp-all: 0.2.3
license: MIT
```

2023-02-04 00:18 UTC, rvermeulen commented on c/common/test/qlpack.yml
>  extractor: cpp
```suggestion
extractor: cpp
license: MIT
```

2023-02-04 00:18 UTC, rvermeulen commented on c/misra/test/qlpack.yml
> +extractor: cpp
```suggestion
extractor: cpp
license: MIT
```

2023-02-04 00:18 UTC, rvermeulen commented on cpp/autosar/test/qlpack.yml
>  extractor: cpp
```suggestion
extractor: cpp
license: MIT
```

2023-02-04 00:18 UTC, rvermeulen commented on cpp/cert/src/qlpack.yml
> +dependencies:
We should add the `defaultSuiteFile`, `suites`, `license`, and `description` properties.

The `defaultSuiteFile` helps with running the default selected suite when our package is provided to `codeql database analyze` and the `suites` informs the CodeQL cli of the possible suites and turns them into well-known suites so you can run them without providing the full path.

2023-02-04 00:18 UTC, rvermeulen commented on cpp/cert/test/qlpack.yml
>  extractor: cpp
```suggestion
extractor: cpp
license: MIT
```

2023-02-04 00:18 UTC, rvermeulen commented on cpp/common/src/qlpack.yml
> +dependencies:
We should add the `license`, and `description` properties.

2023-02-04 00:18 UTC, rvermeulen commented on cpp/common/test/qlpack.yml
>  extractor: cpp
```suggestion
extractor: cpp
license: MIT
```

2023-02-04 00:18 UTC, rvermeulen commented on cpp/misra/src/qlpack.yml
> +dependencies:
We should add the `defaultSuiteFile`, `suites`, `license`, and `description` properties.

The `defaultSuiteFile` helps with running the default selected suite when our package is provided to `codeql database analyze` and the `suites` informs the CodeQL cli of the possible suites and turns them into well-known suites so you can run them without providing the full path.

2023-02-04 00:18 UTC, rvermeulen commented on cpp/misra/test/qlpack.yml
>  extractor: cpp
```suggestion
extractor: cpp
license: MIT
```

2023-02-04 00:18 UTC, rvermeulen commented on cpp/report/src/qlpack.yml
> +dependencies:
```suggestion
license: MIT
dependencies:
```

2023-02-04 00:18 UTC, rvermeulen commented on scripts/generate_modules/queries/qlpack.yml
> +dependencies:
```suggestion
license: MIT
dependencies:
```

2023-02-04 00:18 UTC, rvermeulen commented on scripts/get_workspace_packs.py
> +    with open('.codeqlmanifest.json') as manifest_file:
If we choose to replace `.codeqlmanifest.json` with a `codeql-workspace.yml` we need to update this reference.

2023-02-06 18:33 UTC, rvermeulen commented on cpp/misra/src/qlpack.yml
> +dependencies:
Good point. I think running just the MISRA rules would make sense.

I believe we can archive that with an inline suite definition, something like

```yml
defaultSuite:
 qlpack: codeql/autosar-cpp-coding-standards
 include:
   tags contains: /^external/autosar/id/m.*/
```

2023-02-06 23:59 UTC, rvermeulen commented on .github/workflows/codeql_unit_tests.yml
> +         ${{ github.workspace }}/codeql_home/codeql/codeql query compile --threads 0 cpp
Good point. For shared queries we have a single unit test case with a simple query that only imports the library module implementing the shared query. That is, we do not exercise the standard query files importing a shared implementation.

So for this PR lets keep this in.

2023-02-07 19:15 UTC, rvermeulen commented on .codeqlmanifest.json
> +{ "provide": [ "cpp/*/src/qlpack.yml", "cpp/*/test/qlpack.yml", "c/*/src/qlpack.yml", "c/*/test/qlpack.yml", "scripts/generate_modules/queries/qlpack.yml" ] }
How does it break it?

2023-02-07 19:16 UTC, rvermeulen commented on .github/workflows/code-scanning-pack-gen.yml
> -          codeql query compile --search-path c --search-path cpp --threads 0 c
Yes, a bundle or/and publishing the packs should be a different PR.

2023-02-07 19:17 UTC, rvermeulen commented on .github/workflows/code-scanning-pack-gen.yml
> -          codeql query compile --search-path c --search-path cpp --threads 0 c
`codeql pack ls` is a the better way to list the packs in the current workspace.

2023-02-08 16:59 UTC, jsinglet commented
> Release test ✅ after removing the `codeql-workspace.yml` file and `defaultSuiteFile` property https://github.com/github/codeql-coding-standards-release-engineering/actions/runs/4124784509

Sweet @mbaluda -- so this requires no changes to the release process then? **Just as a note, we should not merge** this until #171 is merged to make sure you are compatible with the latest matrix testing work.

2023-02-27 19:24 UTC, rvermeulen approved these changes
LGTM

2023-02-27 19:29 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-02-27 19:29 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-02-27 19:31 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-02-27 19:31 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-02-27 19:32 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-02-27 22:30 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-02-27 22:30 UTC, jsinglet commented
/test-performance

2023-02-27 22:30 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-02-27 22:32 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-02-27 22:34 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-02-27 22:34 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-02-27 22:43 UTC, jsinglet commented
/test-performance

2023-02-27 22:45 UTC, jsinglet commented
/test-performance

2023-02-27 22:46 UTC, jsinglet commented
/test-performance

2023-02-27 23:08 UTC, jsinglet commented
/test-performance

2023-02-27 23:12 UTC, jsinglet commented
/test-performance

2023-02-27 23:14 UTC, jsinglet commented
/test-performance

2023-02-27 23:16 UTC, jsinglet commented
/test-performance

2023-02-27 23:34 UTC, jsinglet commented
/test-performance

2023-02-27 23:41 UTC, jsinglet commented
/test-performance

2023-02-27 23:43 UTC, jsinglet commented
🏁 Beep Boop! One or things failed during performance testing. Please check the release engineering repo for details.

2023-02-27 23:47 UTC, jsinglet commented
🏁 Beep Boop! One or things failed during performance testing. Please check the release engineering repo for details.

2023-02-28 00:18 UTC, jsinglet commented
/test-performance

2023-02-28 00:24 UTC, jsinglet commented
🏁 Beep Boop! One or things failed during performance testing. Please check the release engineering repo for details.

2023-02-28 00:35 UTC, jsinglet commented
/test-performance

2023-02-28 00:36 UTC, jsinglet commented
/test-performance

2023-02-28 00:40 UTC, jsinglet commented
🏁 Beep Boop! One or things failed during performance testing. Please check the release engineering repo for details.

2023-02-28 00:49 UTC, jsinglet commented
/test-performance

2023-02-28 01:49 UTC, jsinglet commented
🏁 Beep Boop! One or things failed during performance testing. Please check the release engineering repo for details.

2023-02-28 15:55 UTC, jsinglet commented
/test-performance

2023-02-28 17:33 UTC, jsinglet commented
🏁 Beep Boop! ** Performance testing complete! See below for performance of the last 3 runs vs your PR. <br><br>
``` 

Release                            : v2.12.0
Platform                           : x86-windows
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 13079180.0
Mean_Query_Execution_Time_Ms       : 23608.628158844764
Median_Query_Execution_Time_Ms     : 1700.0
Standard_Deviation_Ms              : 68251.8659996672
Total_Serialized_Execution_Time_s  : 13079.18
Mean_Query_Execution_Time_s        : 23.608628158844763
Median_Query_Execution_Time_s      : 1.7
Standard_Deviation_s               : 68.2518659996672
Percentile95_s                     : 154.70000000000005
Number_of_Queries                  : 554

Release                            : v2.12.0
Platform                           : x86-windows
Language                           : c
Total_Serialized_Execution_Time_Ms : 11264392.0
Mean_Query_Execution_Time_Ms       : 73623.477124183
Median_Query_Execution_Time_Ms     : 25300.0
Standard_Deviation_Ms              : 99037.51477843111
Total_Serialized_Execution_Time_s  : 11264.392
Mean_Query_Execution_Time_s        : 73.623477124183
Median_Query_Execution_Time_s      : 25.3
Standard_Deviation_s               : 99.03751477843112
Percentile95_s                     : 260.0
Number_of_Queries                  : 153

Release                            : v2.12.0
Platform                           : x86-linux
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 11743245.0
Mean_Query_Execution_Time_Ms       : 21197.193140794225
Median_Query_Execution_Time_Ms     : 1600.0
Standard_Deviation_Ms              : 57951.59797493685
Total_Serialized_Execution_Time_s  : 11743.245
Mean_Query_Execution_Time_s        : 21.197193140794226
Median_Query_Execution_Time_s      : 1.6
Standard_Deviation_s               : 57.951597974936846
Percentile95_s                     : 131.5500000000003
Number_of_Queries                  : 554

Release                            : v2.12.0
Platform                           : x86-linux
Language                           : c
Total_Serialized_Execution_Time_Ms : 9034750.0
Mean_Query_Execution_Time_Ms       : 59050.65359477124
Median_Query_Execution_Time_Ms     : 24400.0
Standard_Deviation_Ms              : 82856.59932760814
Total_Serialized_Execution_Time_s  : 9034.75
Mean_Query_Execution_Time_s        : 59.05065359477124
Median_Query_Execution_Time_s      : 24.4
Standard_Deviation_s               : 82.85659932760814
Percentile95_s                     : 226.0
Number_of_Queries                  : 153

Release                            : v2.13.0
Platform                           : x86-windows
Language                           : c
Total_Serialized_Execution_Time_Ms : 12888623.0
Mean_Query_Execution_Time_Ms       : 71603.46111111112
Median_Query_Execution_Time_Ms     : 10650.0
Standard_Deviation_Ms              : 101717.53237896915
Total_Serialized_Execution_Time_s  : 12888.623
Mean_Query_Execution_Time_s        : 71.60346111111112
Median_Query_Execution_Time_s      : 10.65
Standard_Deviation_s               : 101.71753237896915
Percentile95_s                     : 268.0
Number_of_Queries                  : 180

Release                            : v2.13.0
Platform                           : x86-linux
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 11263499.0
Mean_Query_Execution_Time_Ms       : 20331.225631768953
Median_Query_Execution_Time_Ms     : 1550.0
Standard_Deviation_Ms              : 56503.505727253716
Total_Serialized_Execution_Time_s  : 11263.499
Mean_Query_Execution_Time_s        : 20.33122563176895
Median_Query_Execution_Time_s      : 1.55
Standard_Deviation_s               : 56.50350572725372
Percentile95_s                     : 124.05000000000007
Number_of_Queries                  : 554

Release                            : v2.13.0
Platform                           : x86-linux
Language                           : c
Total_Serialized_Execution_Time_Ms : 10070641.0
Mean_Query_Execution_Time_Ms       : 55948.00555555556
Median_Query_Execution_Time_Ms     : 16250.0
Standard_Deviation_Ms              : 82449.7274569554
Total_Serialized_Execution_Time_s  : 10070.641
Mean_Query_Execution_Time_s        : 55.94800555555556
Median_Query_Execution_Time_s      : 16.25
Standard_Deviation_s               : 82.4497274569554
Percentile95_s                     : 233.0
Number_of_Queries                  : 180

Release                            : v2.13.0
Platform                           : x86-windows
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 13055520.0
Mean_Query_Execution_Time_Ms       : 23565.92057761733
Median_Query_Execution_Time_Ms     : 1600.0
Standard_Deviation_Ms              : 67365.32368053458
Total_Serialized_Execution_Time_s  : 13055.52
Mean_Query_Execution_Time_s        : 23.56592057761733
Median_Query_Execution_Time_s      : 1.6
Standard_Deviation_s               : 67.36532368053459
Percentile95_s                     : 153.05000000000007
Number_of_Queries                  : 554

Release                            : 179
Platform                           : x86-linux
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 11655826.0
Mean_Query_Execution_Time_Ms       : 21039.397111913357
Median_Query_Execution_Time_Ms     : 1550.0
Standard_Deviation_Ms              : 57808.34390347044
Total_Serialized_Execution_Time_s  : 11655.826
Mean_Query_Execution_Time_s        : 21.039397111913356
Median_Query_Execution_Time_s      : 1.55
Standard_Deviation_s               : 57.808343903470444
Percentile95_s                     : 128.4000000000001
Number_of_Queries                  : 554

Release                            : 179
Platform                           : x86-linux
Language                           : c
Total_Serialized_Execution_Time_Ms : 12609777.0
Mean_Query_Execution_Time_Ms       : 63365.71356783919
Median_Query_Execution_Time_Ms     : 10900.0
Standard_Deviation_Ms              : 91469.60089031604
Total_Serialized_Execution_Time_s  : 12609.777
Mean_Query_Execution_Time_s        : 63.365713567839194
Median_Query_Execution_Time_s      : 10.9
Standard_Deviation_s               : 91.46960089031604
Percentile95_s                     : 271.0
Number_of_Queries                  : 199


```

2023-02-28 18:14 UTC, jsinglet commented
/test-performance

2023-02-28 19:21 UTC, jsinglet commented
🏁 Beep Boop! Performance testing complete! See below for performance of the last 3 runs vs your PR. Times are based on predicate performance. You can **find full graphs and stats** in the PR that was created for this test in the release engineering repo. <br><br>
``` 

Release                            : v2.12.0
Platform                           : x86-windows
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 4428018
Mean_Predicate_Execution_Time_Ms   : 111.02798254851812
Median_Predicate_Execution_Time_Ms : 3.0
Standard_Deviation_Ms              : 1849.028713918296
Total_Serialized_Execution_Time_s  : 4428.018
Mean_Query_Execution_Time_s        : 0.1110279825485181
Median_Predicate_Execution_Time_s  : 0.003
Percentile95_Ms                    : 223.0
Number_of_Predicates               : 39882

Release                            : v2.12.0
Platform                           : x86-windows
Language                           : c
Total_Serialized_Execution_Time_Ms : 2646295
Mean_Predicate_Execution_Time_Ms   : 121.49556953307928
Median_Predicate_Execution_Time_Ms : 4.0
Standard_Deviation_Ms              : 1930.489882503224
Total_Serialized_Execution_Time_s  : 2646.295
Mean_Query_Execution_Time_s        : 0.1214955695330792
Median_Predicate_Execution_Time_s  : 0.004
Percentile95_Ms                    : 287.0
Number_of_Predicates               : 21781

Release                            : v2.12.0
Platform                           : x86-linux
Language                           : c
Total_Serialized_Execution_Time_Ms : 2290304
Mean_Predicate_Execution_Time_Ms   : 104.99239020812324
Median_Predicate_Execution_Time_Ms : 3.0
Standard_Deviation_Ms              : 1629.1630253157075
Total_Serialized_Execution_Time_s  : 2290.304
Mean_Query_Execution_Time_s        : 0.1049923902081232
Median_Predicate_Execution_Time_s  : 0.003
Percentile95_Ms                    : 260.0
Number_of_Predicates               : 21814

Release                            : v2.12.0
Platform                           : x86-linux
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 4005710
Mean_Predicate_Execution_Time_Ms   : 99.6594019007812
Median_Predicate_Execution_Time_Ms : 2.0
Standard_Deviation_Ms              : 1654.8379642914922
Total_Serialized_Execution_Time_s  : 4005.71
Mean_Query_Execution_Time_s        : 0.0996594019007812
Median_Predicate_Execution_Time_s  : 0.002
Percentile95_Ms                    : 203.0
Number_of_Predicates               : 40194

Release                            : v2.13.0
Platform                           : x86-linux
Language                           : c
Total_Serialized_Execution_Time_Ms : 2851919
Mean_Predicate_Execution_Time_Ms   : 123.07077201916024
Median_Predicate_Execution_Time_Ms : 3.0
Standard_Deviation_Ms              : 1960.041520356055
Total_Serialized_Execution_Time_s  : 2851.919
Mean_Query_Execution_Time_s        : 0.1230707720191602
Median_Predicate_Execution_Time_s  : 0.003
Percentile95_Ms                    : 266.0
Number_of_Predicates               : 23173

Release                            : v2.13.0
Platform                           : x86-windows
Language                           : c
Total_Serialized_Execution_Time_Ms : 3268794
Mean_Predicate_Execution_Time_Ms   : 141.10917332182171
Median_Predicate_Execution_Time_Ms : 5.0
Standard_Deviation_Ms              : 2347.189663268768
Total_Serialized_Execution_Time_s  : 3268.794
Mean_Query_Execution_Time_s        : 0.1411091733218217
Median_Predicate_Execution_Time_s  : 0.005
Percentile95_Ms                    : 300.0
Number_of_Predicates               : 23165

Release                            : v2.13.0
Platform                           : x86-linux
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 3877306
Mean_Predicate_Execution_Time_Ms   : 97.3048410168896
Median_Predicate_Execution_Time_Ms : 2.0
Standard_Deviation_Ms              : 1572.1314154912643
Total_Serialized_Execution_Time_s  : 3877.306
Mean_Query_Execution_Time_s        : 0.0973048410168896
Median_Predicate_Execution_Time_s  : 0.002
Percentile95_Ms                    : 200.0
Number_of_Predicates               : 39847

Release                            : v2.13.0
Platform                           : x86-windows
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 4405198
Mean_Predicate_Execution_Time_Ms   : 110.18504252126064
Median_Predicate_Execution_Time_Ms : 3.0
Standard_Deviation_Ms              : 1816.991907084716
Total_Serialized_Execution_Time_s  : 4405.198
Mean_Query_Execution_Time_s        : 0.1101850425212606
Median_Predicate_Execution_Time_s  : 0.003
Percentile95_Ms                    : 222.0
Number_of_Predicates               : 39980

Release                            : 179
Platform                           : x86-linux
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 3897887
Mean_Predicate_Execution_Time_Ms   : 97.5911219048096
Median_Predicate_Execution_Time_Ms : 2.0
Standard_Deviation_Ms              : 1571.0660218647345
Total_Serialized_Execution_Time_s  : 3897.887
Mean_Query_Execution_Time_s        : 0.0975911219048095
Median_Predicate_Execution_Time_s  : 0.002
Percentile95_Ms                    : 198.0
Number_of_Predicates               : 39941

Release                            : 179
Platform                           : x86-linux
Language                           : c
Total_Serialized_Execution_Time_Ms : 2939349
Mean_Predicate_Execution_Time_Ms   : 110.62660895747084
Median_Predicate_Execution_Time_Ms : 2.0
Standard_Deviation_Ms              : 1823.0411480848848
Total_Serialized_Execution_Time_s  : 2939.349
Mean_Query_Execution_Time_s        : 0.1106266089574708
Median_Predicate_Execution_Time_s  : 0.002
Percentile95_Ms                    : 244.0
Number_of_Predicates               : 26570


```
🏁 Below are the slowest predicates for the last 2 releases vs this PR. <br><br>
``` 

Release           : v2.13.0
Run               : 2023-01-18_21-49-06
Platform          : x86-linux
Language          : c
Suite             : misra-default
Predicate         : #select#cpe#1#f#antijoin_rhs
Execution_Time_Ms : 29501

Release           : v2.13.0
Run               : 2023-01-18_21-49-06
Platform          : x86-windows
Language          : cpp
Suite             : cert-default
Predicate         : SSAConstruction::DefUse::hasNonPhiDefinition#2b11997e#ffff
Execution_Time_Ms : 36250

Release           : v2.13.0
Run               : 2023-01-18_21-49-06
Platform          : x86-linux
Language          : c
Suite             : misra-default
Predicate         : #select#ff#antijoin_rhs
Execution_Time_Ms : 200444

Release           : v2.13.0
Run               : 2023-01-18_21-49-06
Platform          : x86-linux
Language          : c
Suite             : misra-default
Predicate         : #select#cpe#134#fff#shared
Execution_Time_Ms : 143720

Release           : v2.13.0
Run               : 2023-01-18_21-49-06
Platform          : x86-linux
Language          : c
Suite             : misra-default
Predicate         : #select#cpe#13456#fffff#shared
Execution_Time_Ms : 96963

Release           : v2.13.0
Run               : 2023-01-18_21-49-06
Platform          : x86-windows
Language          : cpp
Suite             : autosar-default
Predicate         : UnusedIncludeDirectives::getANonLocalDependency#574b69bc#ff
Execution_Time_Ms : 35398

Release           : v2.13.0
Run               : 2023-01-18_21-49-06
Platform          : x86-linux
Language          : cpp
Suite             : autosar-default
Predicate         : Dependency::dependsOnTransitive#b0c9183e#ff
Execution_Time_Ms : 180277

Release           : v2.13.0
Run               : 2023-01-18_21-49-06
Platform          : x86-linux
Language          : cpp
Suite             : autosar-default
Predicate         : m##DataFlowUtil::localFlowStep#7572fbecPlus#bf
Execution_Time_Ms : 165026

Release           : v2.13.0
Run               : 2023-01-18_21-49-06
Platform      [...]

2023-03-01 04:40 UTC, jsinglet commented
https://github.com/github/codeql-coding-standards-release-engineering/actions/runs/4297714160 

GTG

2023-03-01 04:40 UTC, merged