Implement C Memory2 package
github/codeql-coding-standards pull request #265
Opened 2023-03-23 01:59 UTC by kraiouchkine

## Description

This pull request implements the C Memory2 package.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [x] Queries have been added for the following rules:
     - ARR36-C (closes github/coding-standards-team#748)
     - EXP43-C (closes github/coding-standards-team#749)
     - MEM31-C (closes github/coding-standards-team#750)
     - MEM33-C (closes github/coding-standards-team#751)
     - MEM34-C (closes github/coding-standards-team#752)
     - MEM36-C (closes github/coding-standards-team#754)
     - RULE-22-1 (closes github/coding-standards-team#760)
     - RULE-22-2 (closes github/coding-standards-team#761)
 - [x] Queries have been modified for the following rules:
     - FIO42-C (minor bug-fix and creation of shared implementation)

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2023-03-23 02:03 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 02:03 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 02:04 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 02:05 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 02:06 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : True
SUITE                : CERT-C
PACKAGE              : Memory2
TEST_DIFFERENCE      : 
QUERY                : CopyStructsWithAFlexibleArrayMemberDynamically
RULE                 : MEM33-C
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True

COMPILE_PASS         : True
SUITE                : CERT-C
PACKAGE              : Memory2
TEST_DIFFERENCE      : 
QUERY                : AllocStructsWithAFlexibleArrayMemberDynamically
RULE                 : MEM33-C
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True

COMPILE_PASS         : True
SUITE                : CERT-C
PACKAGE              : Memory2
TEST_DIFFERENCE      : 
QUERY                : DoNotModifyAlignmentOfMemoryWithRealloc
RULE                 : MEM36-C
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True

COMPILE_PASS         : True
SUITE                : MISRA-C-2012
PACKAGE              : Memory2
TEST_DIFFERENCE      : 
QUERY                : FreeMemoryWhenNoLongerNeededMisra
RULE                 : RULE-22-1
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True

COMPILE_PASS         : True
SUITE                : MISRA-C-2012
PACKAGE              : Memory2
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 comp 35.1s eval 1.1s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
QUERY                : CloseFileHandleWhenNoLongerNeededMisra
RULE                 : RULE-22-1
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : False

COMPILE_PASS         : True
SUITE                : CERT-C
PACKAGE              : IO1
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 eval 859ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
QUERY                : CloseFilesWhenTheyAreNoLongerNeeded
RULE                 : FIO42-C
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : False

COMPILE_PASS         : True
SUITE                : CERT-C
PACKAGE              : Memory2
TEST_DIFFERENCE      : 
QUERY                : FreeMemoryWhenNoLongerNeededCert
RULE                 : MEM31-C
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True

COMPILE_PASS         : True
SUITE                : CERT-C
PACKAGE              : Memory2
TEST_DIFFERENCE      : 
QUERY                : DoNotComparePaddingData
RULE                 : EXP42-C
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True

COMPILE_PASS         : True
SUITE                : MISRA-C-2012
PACKAGE              : Memory2
TEST_DIFFERENCE      : 
QUERY                : OnlyFreeMemoryAllocatedDynamicallyMisra
RULE                 : RULE-22-2
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True

COMPILE_PASS         : True
SUITE                : CERT-C
PACKAGE              : Memory2
TEST_DIFFERENCE      : 
QUERY                : OnlyFreeMemoryAllocatedDynamicallyCert
RULE                 : MEM34-C
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True


```

2023-03-23 02:07 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

QUERY                : MemcpyUsedToAccessObjectRepresentation
RULE                 : EXP62-CPP
TEST_PASS            : False
COMPILE_PASS         : False
TEST_DIFFERENCE      : 
SUITE                : CERT-C++
COMPILE_ERROR_OUTPUT : [2023-03-23 02:07:48] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 02:07:48] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:07:48] [build-stderr]   ~~~~~^
                       [2023-03-23 02:07:48] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 02:07:48] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:07:48] [build-stderr]   ~~~~~^
                       [2023-03-23 02:07:48] [build-stderr] 2 errors generated.
                       [2023-03-23 02:07:49] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
PACKAGE              : Representation

QUERY                : MemcmpUsedToAccessObjectRepresentation
RULE                 : EXP62-CPP
TEST_PASS            : False
COMPILE_PASS         : False
TEST_DIFFERENCE      : 
SUITE                : CERT-C++
COMPILE_ERROR_OUTPUT : [2023-03-23 02:07:48] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 02:07:48] [build-stderr]   if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 02:07:48] [build-stderr]        ~~~~~^
                       [2023-03-23 02:07:48] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 02:07:48] [build-stderr]   if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 02:07:48] [build-stderr]        ~~~~~^
                       [2023-03-23 02:07:48] [build-stderr] 2 errors generated.
                       [2023-03-23 02:07:49] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       
PACKAGE              : Representation

QUERY                : MemsetUsedToAccessObjectRepresentation
RULE                 : EXP62-CPP
TEST_PASS            : False
COMPILE_PASS         : False
TEST_DIFFERENCE      : 
SUITE                : CERT-C++
COMPILE_ERROR_OUTPUT : [2023-03-23 02:07:48] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 02:07:48] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:07:48] [build-stderr]   ~~~~~^
                       [2023-03-23 02:07:48] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 02:07:48] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:07:48] [build-stderr]   ~~~~~^
                       [2023-03-23 02:07:48] [build-stderr] 2 errors generated.
                       [2023-03-23 02:07:49] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
PACKAGE              : Representation

QUERY                : UsingDefaultOperatorNewForOverAlignedTypes
RULE                 : MEM57-CPP
TEST_PASS            : False
COMPILE_PASS         : True
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,6 @@
                       -| test.cpp:13:28:13:51 | new | Use of default operator new for over-aligned type $@ (alignment: 32, max_align_t: 16). | test.cpp:7:20:7:37 | StructAOverAligned | StructAOverAligned |
                       +ERROR: Predicate getGlobalMaxAlignT/0 is ambiguous between: predicate Alignment::getGlobalMaxAlignT() from Alignment.qll:22, predicate Allocations::getGlobalMaxAlignT() from Allocations.qll:185. You can resolve the ambiguity by casting to the desired type. (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:26,36-54)
                       +ERROR: Predicate getGlobalMaxAlignT/0 is ambiguous between: predicate Alignment::getGlobalMaxAlignT() from Alignment.qll:22, predicate Allocations::getGlobalMaxAlignT() from Allocations.qll:185. You can resolve the ambiguity by casting to the desired type. (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:29,69-87)
                       +ERROR: The class Alignment::MaxAlignT, which was brought into scope by this import, conflicts with existing declarations: class Allocations::MaxAlignT from Allocations.qll:172 (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:17,1-37)
                       +ERROR: The class Allocations::MaxAlignT, which was brought into scope by this import, conflicts with existing declarations: class Alignment::MaxAlignT from Alignment.qll:14 (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:18,1-39)
                       +ERROR: The predicate Alignment::getGlobalMaxAlignT(), which was brought into scope by this import, conflicts with existing declarations: predicate Allocations::getGlobalMaxAlignT() from Allocations.qll:185 (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:17,1-37)
             [...]

2023-03-23 02:08 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_ERROR_OUTPUT : [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 02:07:54] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:07:54] [build-stderr]         ^~~~~~
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 02:07:54] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:07:54] [build-stderr]         ^~~~~~
                       [2023-03-23 02:07:54] [build-stderr]         decay
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 02:07:54] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:07:54] [build-stderr]         ^~~~~~
                       [2023-03-23 02:07:55] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
RULE                 : EXP62-CPP
TEST_DIFFERENCE      : 
QUERY                : MemcpyUsedToAccessObjectRepresentation
TEST_PASS            : False
COMPILE_PASS         : False
SUITE                : CERT-C++
PACKAGE              : Representation

COMPILE_ERROR_OUTPUT : [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 02:07:54] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:07:54] [build-stderr]         ^~~~~~
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 02:07:54] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:07:54] [build-stderr]         ^~~~~~
                       [2023-03-23 02:07:54] [build-stderr]         decay
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 02:07:54] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:07:54] [build-stderr]         ^~~~~~
                       [2023-03-23 02:07:55] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
RULE                 : EXP62-CPP
TEST_DIFFERENCE      : 
QUERY                : MemsetUsedToAccessObjectRepresentation
TEST_PASS            : False
COMPILE_PASS         : False
SUITE                : CERT-C++
PACKAGE              : Representation

COMPILE_ERROR_OUTPUT : [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f1(const S1&, const S1&)':
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 02:07:54] [build-stderr]    if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 02:07:54] [build-stderr]              ^~~~~~
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f2(const S2&, const S2&)':
                       [2023-03-23 02:07:54] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 02:07:54] [build-stderr]    if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 02:07:54] [build-stderr]              ^~~~~~
                       [2023-03-23 02:07:55] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       
RULE                 : EXP62-CPP
TEST_DIFFERENCE      : 
QUERY                : MemcmpUsedToAccessObjectRepresentation
TEST_PASS            : False
COMPILE_PASS         : False
SUITE                : CERT-C++
PACKAGE              : Representation

COMPILE_ERROR_OUTPUT : 
RULE                 : MEM57-CPP
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,6 @@
                       -| test.cpp:13:28:13:51 | new | Use of default operator new for over-aligned type $@ (alignment: 32, max_align_t: 16). | test.cpp:7:20:7:37 | StructAOverAligned | StructAOverAligned |
       [...]

2023-03-23 02:08 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

QUERY                : MemcpyUsedToAccessObjectRepresentation
RULE                 : EXP62-CPP
PACKAGE              : Representation
COMPILE_PASS         : False
SUITE                : CERT-C++
TEST_PASS            : False
COMPILE_ERROR_OUTPUT : [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 02:08:20] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:08:20] [build-stderr]         ^~~~~~
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 02:08:20] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:08:20] [build-stderr]         ^~~~~~
                       [2023-03-23 02:08:20] [build-stderr]         decay
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 02:08:20] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:08:20] [build-stderr]         ^~~~~~
                       [2023-03-23 02:08:21] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
TEST_DIFFERENCE      : 

QUERY                : MemsetUsedToAccessObjectRepresentation
RULE                 : EXP62-CPP
PACKAGE              : Representation
COMPILE_PASS         : False
SUITE                : CERT-C++
TEST_PASS            : False
COMPILE_ERROR_OUTPUT : [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 02:08:20] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:08:20] [build-stderr]         ^~~~~~
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 02:08:20] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:08:20] [build-stderr]         ^~~~~~
                       [2023-03-23 02:08:20] [build-stderr]         decay
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 02:08:20] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:08:20] [build-stderr]         ^~~~~~
                       [2023-03-23 02:08:21] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
TEST_DIFFERENCE      : 

QUERY                : MemcmpUsedToAccessObjectRepresentation
RULE                 : EXP62-CPP
PACKAGE              : Representation
COMPILE_PASS         : False
SUITE                : CERT-C++
TEST_PASS            : False
COMPILE_ERROR_OUTPUT : [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f1(const S1&, const S1&)':
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 02:08:20] [build-stderr]    if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 02:08:20] [build-stderr]              ^~~~~~
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f2(const S2&, const S2&)':
                       [2023-03-23 02:08:20] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 02:08:20] [build-stderr]    if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 02:08:20] [build-stderr]              ^~~~~~
                       [2023-03-23 02:08:21] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       
TEST_DIFFERENCE      : 

QUERY                : UsingDefaultOperatorNewForOverAlignedTypes
RULE                 : MEM57-CPP
PACKAGE              : Allocations
COMPILE_PASS         : True
SUITE                : CERT-C++
TEST_PASS            : False
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,6 @@
                        [...]

2023-03-23 02:08 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

SUITE                : CERT-C++
QUERY                : MemsetUsedToAccessObjectRepresentation
RULE                 : EXP62-CPP
COMPILE_PASS         : False
TEST_PASS            : False
TEST_DIFFERENCE      : 
PACKAGE              : Representation
COMPILE_ERROR_OUTPUT : [2023-03-23 02:08:22] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 02:08:22] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:08:22] [build-stderr]   ~~~~~^
                       [2023-03-23 02:08:22] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 02:08:22] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:08:22] [build-stderr]   ~~~~~^
                       [2023-03-23 02:08:22] [build-stderr] 2 errors generated.
                       [2023-03-23 02:08:23] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       

SUITE                : CERT-C++
QUERY                : MemcpyUsedToAccessObjectRepresentation
RULE                 : EXP62-CPP
COMPILE_PASS         : False
TEST_PASS            : False
TEST_DIFFERENCE      : 
PACKAGE              : Representation
COMPILE_ERROR_OUTPUT : [2023-03-23 02:08:22] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 02:08:22] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:08:22] [build-stderr]   ~~~~~^
                       [2023-03-23 02:08:22] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 02:08:22] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:08:22] [build-stderr]   ~~~~~^
                       [2023-03-23 02:08:22] [build-stderr] 2 errors generated.
                       [2023-03-23 02:08:23] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       

SUITE                : CERT-C++
QUERY                : MemcmpUsedToAccessObjectRepresentation
RULE                 : EXP62-CPP
COMPILE_PASS         : False
TEST_PASS            : False
TEST_DIFFERENCE      : 
PACKAGE              : Representation
COMPILE_ERROR_OUTPUT : [2023-03-23 02:08:22] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 02:08:22] [build-stderr]   if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 02:08:22] [build-stderr]        ~~~~~^
                       [2023-03-23 02:08:22] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 02:08:22] [build-stderr]   if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 02:08:22] [build-stderr]        ~~~~~^
                       [2023-03-23 02:08:22] [build-stderr] 2 errors generated.
                       [2023-03-23 02:08:23] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       

SUITE                : CERT-C++
QUERY                : UsingDefaultOperatorNewForOverAlignedTypes
RULE                 : MEM57-CPP
COMPILE_PASS         : True
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,6 @@
                       -| test.cpp:13:28:13:51 | new | Use of default operator new for over-aligned type $@ (alignment: 32, max_align_t: 16). | test.cpp:7:20:7:37 | StructAOverAligned | StructAOverAligned |
                       +ERROR: Predicate getGlobalMaxAlignT/0 is ambiguous between: predicate Alignment::getGlobalMaxAlignT() from Alignment.qll:22, predicate Allocations::getGlobalMaxAlignT() from Allocations.qll:185. You can resolve the ambiguity by casting to the desired type. (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:26,36-54)
                       +ERROR: Predicate getGlobalMaxAlignT/0 is ambiguous between: predicate Alignment::getGlobalMaxAlignT() from Alignment.qll:22, predicate Allocations::getGlobalMaxAlignT() from Allocations.qll:185. You can resolve the ambiguity by casting to the desired type. (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:29,69-87)
                       +ERROR: The class Alignment::MaxAlignT, which was brought into scope by this import, conflicts with existing declarations: class Allocations::MaxAlignT from Allocations.qll:172 (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:17,1-37)
                       +ERROR: The class Allocations::MaxAlignT, which was brought into scope by this import, conflicts with existing declarations: class Alignment::MaxAlignT from Alignment.qll:14 (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:18,1-39)
                       +ERROR: The predicate Alignment::getGlobalMaxAlignT(), which was brought into scope by this import, conflicts with existing declarations: predicate Allocations::getGlobalMaxAlignT() from Allocations.qll:185 (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlign [...]

2023-03-23 02:08 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

SUITE                : CERT-C
PACKAGE              : Memory2
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : CopyStructsWithAFlexibleArrayMemberDynamically
RULE                 : MEM33-C
TEST_PASS            : True
TEST_DIFFERENCE      : 

SUITE                : CERT-C
PACKAGE              : Memory2
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : AllocStructsWithAFlexibleArrayMemberDynamically
RULE                 : MEM33-C
TEST_PASS            : True
TEST_DIFFERENCE      : 

SUITE                : CERT-C
PACKAGE              : Memory2
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : DoNotModifyAlignmentOfMemoryWithRealloc
RULE                 : MEM36-C
TEST_PASS            : True
TEST_DIFFERENCE      : 

SUITE                : MISRA-C-2012
PACKAGE              : Memory2
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : CloseFileHandleWhenNoLongerNeededMisra
RULE                 : RULE-22-1
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 comp 36.3s eval 1.1s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       

SUITE                : MISRA-C-2012
PACKAGE              : Memory2
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : FreeMemoryWhenNoLongerNeededMisra
RULE                 : RULE-22-1
TEST_PASS            : True
TEST_DIFFERENCE      : 

SUITE                : CERT-C
PACKAGE              : IO1
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : CloseFilesWhenTheyAreNoLongerNeeded
RULE                 : FIO42-C
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 eval 962ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       

SUITE                : CERT-C
PACKAGE              : Memory2
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : FreeMemoryWhenNoLongerNeededCert
RULE                 : MEM31-C
TEST_PASS            : True
TEST_DIFFERENCE      : 

SUITE                : CERT-C
PACKAGE              : Memory2
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : DoNotComparePaddingData
RULE                 : EXP42-C
TEST_PASS            : True
TEST_DIFFERENCE      : 

SUITE                : MISRA-C-2012
PACKAGE              : Memory2
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : OnlyFreeMemoryAllocatedDynamicallyMisra
RULE                 : RULE-22-2
TEST_PASS            : True
TEST_DIFFERENCE      : 

SUITE                : CERT-C
PACKAGE              : Memory2
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
QUERY                : OnlyFreeMemoryAllocatedDynamicallyCert
RULE                 : MEM34-C
TEST_PASS            : True
TEST_DIFFERENCE      : 


```

2023-03-23 02:09 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
RULE                 : MEM33-C
COMPILE_PASS         : True
SUITE                : CERT-C
QUERY                : CopyStructsWithAFlexibleArrayMemberDynamically
PACKAGE              : Memory2
TEST_PASS            : True

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
RULE                 : MEM33-C
COMPILE_PASS         : True
SUITE                : CERT-C
QUERY                : AllocStructsWithAFlexibleArrayMemberDynamically
PACKAGE              : Memory2
TEST_PASS            : True

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
RULE                 : MEM36-C
COMPILE_PASS         : True
SUITE                : CERT-C
QUERY                : DoNotModifyAlignmentOfMemoryWithRealloc
PACKAGE              : Memory2
TEST_PASS            : True

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 comp 37s eval 867ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
RULE                 : RULE-22-1
COMPILE_PASS         : True
SUITE                : MISRA-C-2012
QUERY                : CloseFileHandleWhenNoLongerNeededMisra
PACKAGE              : Memory2
TEST_PASS            : False

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
RULE                 : RULE-22-1
COMPILE_PASS         : True
SUITE                : MISRA-C-2012
QUERY                : FreeMemoryWhenNoLongerNeededMisra
PACKAGE              : Memory2
TEST_PASS            : True

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 eval 835ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
RULE                 : FIO42-C
COMPILE_PASS         : True
SUITE                : CERT-C
QUERY                : CloseFilesWhenTheyAreNoLongerNeeded
PACKAGE              : IO1
TEST_PASS            : False

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
RULE                 : MEM31-C
COMPILE_PASS         : True
SUITE                : CERT-C
QUERY                : FreeMemoryWhenNoLongerNeededCert
PACKAGE              : Memory2
TEST_PASS            : True

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
RULE                 : EXP42-C
COMPILE_PASS         : True
SUITE                : CERT-C
QUERY                : DoNotComparePaddingData
PACKAGE              : Memory2
TEST_PASS            : True

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
RULE                 : RULE-22-2
COMPILE_PASS         : True
SUITE                : MISRA-C-2012
QUERY                : OnlyFreeMemoryAllocatedDynamicallyMisra
PACKAGE              : Memory2
TEST_PASS            : True

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
RULE                 : MEM34-C
COMPILE_PASS         : True
SUITE                : CERT-C
QUERY                : OnlyFreeMemoryAllocatedDynamicallyCert
PACKAGE              : Memory2
TEST_PASS            : True


```

2023-03-23 02:09 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Memory2
QUERY                : CopyStructsWithAFlexibleArrayMemberDynamically
TEST_PASS            : True
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
SUITE                : CERT-C
RULE                 : MEM33-C

PACKAGE              : Memory2
QUERY                : AllocStructsWithAFlexibleArrayMemberDynamically
TEST_PASS            : True
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
SUITE                : CERT-C
RULE                 : MEM33-C

PACKAGE              : Memory2
QUERY                : DoNotModifyAlignmentOfMemoryWithRealloc
TEST_PASS            : True
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
SUITE                : CERT-C
RULE                 : MEM36-C

PACKAGE              : Memory2
QUERY                : CloseFileHandleWhenNoLongerNeededMisra
TEST_PASS            : False
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 comp 36.5s eval 848ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
SUITE                : MISRA-C-2012
RULE                 : RULE-22-1

PACKAGE              : Memory2
QUERY                : FreeMemoryWhenNoLongerNeededMisra
TEST_PASS            : True
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
SUITE                : MISRA-C-2012
RULE                 : RULE-22-1

PACKAGE              : IO1
QUERY                : CloseFilesWhenTheyAreNoLongerNeeded
TEST_PASS            : False
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 eval 868ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
SUITE                : CERT-C
RULE                 : FIO42-C

PACKAGE              : Memory2
QUERY                : FreeMemoryWhenNoLongerNeededCert
TEST_PASS            : True
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
SUITE                : CERT-C
RULE                 : MEM31-C

PACKAGE              : Memory2
QUERY                : DoNotComparePaddingData
TEST_PASS            : True
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
SUITE                : CERT-C
RULE                 : EXP42-C

PACKAGE              : Memory2
QUERY                : OnlyFreeMemoryAllocatedDynamicallyMisra
TEST_PASS            : True
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
SUITE                : MISRA-C-2012
RULE                 : RULE-22-2

PACKAGE              : Memory2
QUERY                : OnlyFreeMemoryAllocatedDynamicallyCert
TEST_PASS            : True
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
SUITE                : CERT-C
RULE                 : MEM34-C


```

2023-03-23 02:09 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-03-23 02:10 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 02:10 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-03-23 02:10 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 02:14 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

SUITE                : CERT-C++
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 02:14:10] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:14:10] [build-stderr]         ^~~~~~
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 02:14:10] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:14:10] [build-stderr]         ^~~~~~
                       [2023-03-23 02:14:10] [build-stderr]         decay
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 02:14:10] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:14:10] [build-stderr]         ^~~~~~
                       [2023-03-23 02:14:11] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
QUERY                : MemcpyUsedToAccessObjectRepresentation
COMPILE_PASS         : False
PACKAGE              : Representation
RULE                 : EXP62-CPP
TEST_PASS            : False

SUITE                : CERT-C++
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 02:14:10] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:14:10] [build-stderr]         ^~~~~~
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 02:14:10] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:14:10] [build-stderr]         ^~~~~~
                       [2023-03-23 02:14:10] [build-stderr]         decay
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 02:14:10] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:14:10] [build-stderr]         ^~~~~~
                       [2023-03-23 02:14:11] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
QUERY                : MemsetUsedToAccessObjectRepresentation
COMPILE_PASS         : False
PACKAGE              : Representation
RULE                 : EXP62-CPP
TEST_PASS            : False

SUITE                : CERT-C++
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f1(const S1&, const S1&)':
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 02:14:10] [build-stderr]    if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 02:14:10] [build-stderr]              ^~~~~~
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f2(const S2&, const S2&)':
                       [2023-03-23 02:14:10] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 02:14:10] [build-stderr]    if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 02:14:10] [build-stderr]              ^~~~~~
                       [2023-03-23 02:14:11] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       
QUERY                : MemcmpUsedToAccessObjectRepresentation
COMPILE_PASS         : False
PACKAGE              : Representation
RULE                 : EXP62-CPP
TEST_PASS            : False

SUITE                : CERT-C++
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,6 @@
                       -| test.cpp:13:28:13:51 | new | Use of default operator new for over-aligned type $@ (alignment: 32, max_align_t: 16). | test.cpp:7:20:7:37 | StructAOverAligned | StructAOverAligned |
                       +ERROR:  [...]

2023-03-23 02:14 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

SUITE                : CERT-C++
PACKAGE              : Representation
COMPILE_ERROR_OUTPUT : [2023-03-23 02:14:11] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 02:14:11] [build-stderr]   if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 02:14:11] [build-stderr]        ~~~~~^
                       [2023-03-23 02:14:11] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 02:14:11] [build-stderr]   if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 02:14:11] [build-stderr]        ~~~~~^
                       [2023-03-23 02:14:11] [build-stderr] 2 errors generated.
                       [2023-03-23 02:14:12] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       
RULE                 : EXP62-CPP
COMPILE_PASS         : False
TEST_PASS            : False
QUERY                : MemcmpUsedToAccessObjectRepresentation
TEST_DIFFERENCE      : 

SUITE                : CERT-C++
PACKAGE              : Representation
COMPILE_ERROR_OUTPUT : [2023-03-23 02:14:11] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 02:14:11] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:14:11] [build-stderr]   ~~~~~^
                       [2023-03-23 02:14:11] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 02:14:11] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:14:11] [build-stderr]   ~~~~~^
                       [2023-03-23 02:14:11] [build-stderr] 2 errors generated.
                       [2023-03-23 02:14:12] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
RULE                 : EXP62-CPP
COMPILE_PASS         : False
TEST_PASS            : False
QUERY                : MemsetUsedToAccessObjectRepresentation
TEST_DIFFERENCE      : 

SUITE                : CERT-C++
PACKAGE              : Representation
COMPILE_ERROR_OUTPUT : [2023-03-23 02:14:11] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 02:14:11] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:14:11] [build-stderr]   ~~~~~^
                       [2023-03-23 02:14:11] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 02:14:11] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:14:11] [build-stderr]   ~~~~~^
                       [2023-03-23 02:14:11] [build-stderr] 2 errors generated.
                       [2023-03-23 02:14:12] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
RULE                 : EXP62-CPP
COMPILE_PASS         : False
TEST_PASS            : False
QUERY                : MemcpyUsedToAccessObjectRepresentation
TEST_DIFFERENCE      : 

SUITE                : CERT-C++
PACKAGE              : Allocations
COMPILE_ERROR_OUTPUT : 
RULE                 : MEM57-CPP
COMPILE_PASS         : True
TEST_PASS            : False
QUERY                : UsingDefaultOperatorNewForOverAlignedTypes
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,6 @@
                       -| test.cpp:13:28:13:51 | new | Use of default operator new for over-aligned type $@ (alignment: 32, max_align_t: 16). | test.cpp:7:20:7:37 | StructAOverAligned | StructAOverAligned |
                       +ERROR: Predicate getGlobalMaxAlignT/0 is ambiguous between: predicate Alignment::getGlobalMaxAlignT() from Alignment.qll:22, predicate Allocations::getGlobalMaxAlignT() from Allocations.qll:185. You can resolve the ambiguity by casting to the desired type. (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:26,36-54)
                       +ERROR: Predicate getGlobalMaxAlignT/0 is ambiguous between: predicate Alignment::getGlobalMaxAlignT() from Alignment.qll:22, predicate Allocations::getGlobalMaxAlignT() from Allocations.qll:185. You can resolve the ambiguity by casting to the desired type. (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:29,69-87)
                       +ERROR: The class Alignment::MaxAlignT, which was brought into scope by this import, conflicts with existing declarations: class Allocations::MaxAlignT from Allocations.qll:172 (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:17,1-37)
                       +ERROR: The class Allocations::MaxAlignT, which was brought into scope by this import, conflicts with existing declarations: class Alignment::MaxAlignT from Alignment.qll:14 (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/src/rules/MEM57-CPP/UsingDefaultOperatorNewForOverAlignedTypes.ql:18,1-39)
                       +ERROR: The predicate Alignment::getGlobalMaxAlignT(), which was brought into scope by this import, conflicts with existing declarations: predicate Allocations::getGlobalMaxAlignT() from Allocations.qll:185 (/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/c [...]

2023-03-23 02:14 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Memory2
QUERY                : CopyStructsWithAFlexibleArrayMemberDynamically
COMPILE_PASS         : True
RULE                 : MEM33-C
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C

PACKAGE              : Memory2
QUERY                : AllocStructsWithAFlexibleArrayMemberDynamically
COMPILE_PASS         : True
RULE                 : MEM33-C
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C

PACKAGE              : Memory2
QUERY                : DoNotModifyAlignmentOfMemoryWithRealloc
COMPILE_PASS         : True
RULE                 : MEM36-C
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C

PACKAGE              : Memory2
QUERY                : CloseFileHandleWhenNoLongerNeededMisra
COMPILE_PASS         : True
RULE                 : RULE-22-1
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 comp 34.8s eval 871ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
COMPILE_ERROR_OUTPUT : 
SUITE                : MISRA-C-2012

PACKAGE              : Memory2
QUERY                : FreeMemoryWhenNoLongerNeededMisra
COMPILE_PASS         : True
RULE                 : RULE-22-1
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
SUITE                : MISRA-C-2012

PACKAGE              : IO1
QUERY                : CloseFilesWhenTheyAreNoLongerNeeded
COMPILE_PASS         : True
RULE                 : FIO42-C
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 eval 914ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C

PACKAGE              : Memory2
QUERY                : FreeMemoryWhenNoLongerNeededCert
COMPILE_PASS         : True
RULE                 : MEM31-C
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C

PACKAGE              : Memory2
QUERY                : DoNotComparePaddingData
COMPILE_PASS         : True
RULE                 : EXP42-C
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C

PACKAGE              : Memory2
QUERY                : OnlyFreeMemoryAllocatedDynamicallyMisra
COMPILE_PASS         : True
RULE                 : RULE-22-2
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
SUITE                : MISRA-C-2012

PACKAGE              : Memory2
QUERY                : OnlyFreeMemoryAllocatedDynamicallyCert
COMPILE_PASS         : True
RULE                 : MEM34-C
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C


```

2023-03-23 02:15 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

QUERY                : CopyStructsWithAFlexibleArrayMemberDynamically
SUITE                : CERT-C
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
PACKAGE              : Memory2
RULE                 : MEM33-C
COMPILE_PASS         : True
TEST_PASS            : True

QUERY                : AllocStructsWithAFlexibleArrayMemberDynamically
SUITE                : CERT-C
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
PACKAGE              : Memory2
RULE                 : MEM33-C
COMPILE_PASS         : True
TEST_PASS            : True

QUERY                : DoNotModifyAlignmentOfMemoryWithRealloc
SUITE                : CERT-C
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
PACKAGE              : Memory2
RULE                 : MEM36-C
COMPILE_PASS         : True
TEST_PASS            : True

QUERY                : CloseFileHandleWhenNoLongerNeededMisra
SUITE                : MISRA-C-2012
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 comp 36.6s eval 923ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
PACKAGE              : Memory2
RULE                 : RULE-22-1
COMPILE_PASS         : True
TEST_PASS            : False

QUERY                : FreeMemoryWhenNoLongerNeededMisra
SUITE                : MISRA-C-2012
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
PACKAGE              : Memory2
RULE                 : RULE-22-1
COMPILE_PASS         : True
TEST_PASS            : True

QUERY                : CloseFilesWhenTheyAreNoLongerNeeded
SUITE                : CERT-C
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 eval 920ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
PACKAGE              : IO1
RULE                 : FIO42-C
COMPILE_PASS         : True
TEST_PASS            : False

QUERY                : FreeMemoryWhenNoLongerNeededCert
SUITE                : CERT-C
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
PACKAGE              : Memory2
RULE                 : MEM31-C
COMPILE_PASS         : True
TEST_PASS            : True

QUERY                : DoNotComparePaddingData
SUITE                : CERT-C
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
PACKAGE              : Memory2
RULE                 : EXP42-C
COMPILE_PASS         : True
TEST_PASS            : True

QUERY                : OnlyFreeMemoryAllocatedDynamicallyMisra
SUITE                : MISRA-C-2012
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
PACKAGE              : Memory2
RULE                 : RULE-22-2
COMPILE_PASS         : True
TEST_PASS            : True

QUERY                : OnlyFreeMemoryAllocatedDynamicallyCert
SUITE                : CERT-C
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
PACKAGE              : Memory2
RULE                 : MEM34-C
COMPILE_PASS         : True
TEST_PASS            : True


```

2023-03-23 02:15 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-03-23 02:15 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 02:16 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 02:21 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Representation
TEST_PASS            : False
SUITE                : CERT-C++
QUERY                : MemcpyUsedToAccessObjectRepresentation
COMPILE_PASS         : False
TEST_DIFFERENCE      : 
RULE                 : EXP62-CPP
COMPILE_ERROR_OUTPUT : [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 02:20:40] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:20:40] [build-stderr]         ^~~~~~
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 02:20:40] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:20:40] [build-stderr]         ^~~~~~
                       [2023-03-23 02:20:40] [build-stderr]         decay
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 02:20:40] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:20:40] [build-stderr]         ^~~~~~
                       [2023-03-23 02:20:41] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       

PACKAGE              : Representation
TEST_PASS            : False
SUITE                : CERT-C++
QUERY                : MemsetUsedToAccessObjectRepresentation
COMPILE_PASS         : False
TEST_DIFFERENCE      : 
RULE                 : EXP62-CPP
COMPILE_ERROR_OUTPUT : [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 02:20:40] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:20:40] [build-stderr]         ^~~~~~
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 02:20:40] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:20:40] [build-stderr]         ^~~~~~
                       [2023-03-23 02:20:40] [build-stderr]         decay
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 02:20:40] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:20:40] [build-stderr]         ^~~~~~
                       [2023-03-23 02:20:41] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       

PACKAGE              : Representation
TEST_PASS            : False
SUITE                : CERT-C++
QUERY                : MemcmpUsedToAccessObjectRepresentation
COMPILE_PASS         : False
TEST_DIFFERENCE      : 
RULE                 : EXP62-CPP
COMPILE_ERROR_OUTPUT : [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f1(const S1&, const S1&)':
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 02:20:40] [build-stderr]    if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 02:20:40] [build-stderr]              ^~~~~~
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f2(const S2&, const S2&)':
                       [2023-03-23 02:20:40] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 02:20:40] [build-stderr]    if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 02:20:40] [build-stderr]              ^~~~~~
                       [2023-03-23 02:20:41] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       

PACKAGE              : Allocations
TEST_PASS            : True
SUITE                : CERT-C++
QUERY                : UsingDefaultOperatorNewForOverAlignedTypes
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
RULE                 : MEM57-CPP
COMPILE_ERROR_OUTPUT : 


```

2023-03-23 02:21 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : True
RULE                 : MEM33-C
TEST_DIFFERENCE      : 
SUITE                : CERT-C
TEST_PASS            : True
PACKAGE              : Memory2
QUERY                : CopyStructsWithAFlexibleArrayMemberDynamically
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
RULE                 : MEM33-C
TEST_DIFFERENCE      : 
SUITE                : CERT-C
TEST_PASS            : True
PACKAGE              : Memory2
QUERY                : AllocStructsWithAFlexibleArrayMemberDynamically
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
RULE                 : MEM36-C
TEST_DIFFERENCE      : 
SUITE                : CERT-C
TEST_PASS            : True
PACKAGE              : Memory2
QUERY                : DoNotModifyAlignmentOfMemoryWithRealloc
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
RULE                 : RULE-22-1
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 comp 36s eval 983ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
SUITE                : MISRA-C-2012
TEST_PASS            : False
PACKAGE              : Memory2
QUERY                : CloseFileHandleWhenNoLongerNeededMisra
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
RULE                 : RULE-22-1
TEST_DIFFERENCE      : 
SUITE                : MISRA-C-2012
TEST_PASS            : True
PACKAGE              : Memory2
QUERY                : FreeMemoryWhenNoLongerNeededMisra
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
RULE                 : FIO42-C
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 eval 932ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       
SUITE                : CERT-C
TEST_PASS            : False
PACKAGE              : IO1
QUERY                : CloseFilesWhenTheyAreNoLongerNeeded
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
RULE                 : MEM31-C
TEST_DIFFERENCE      : 
SUITE                : CERT-C
TEST_PASS            : True
PACKAGE              : Memory2
QUERY                : FreeMemoryWhenNoLongerNeededCert
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
RULE                 : EXP42-C
TEST_DIFFERENCE      : 
SUITE                : CERT-C
TEST_PASS            : True
PACKAGE              : Memory2
QUERY                : DoNotComparePaddingData
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
RULE                 : RULE-22-2
TEST_DIFFERENCE      : 
SUITE                : MISRA-C-2012
TEST_PASS            : True
PACKAGE              : Memory2
QUERY                : OnlyFreeMemoryAllocatedDynamicallyMisra
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
RULE                 : MEM34-C
TEST_DIFFERENCE      : 
SUITE                : CERT-C
TEST_PASS            : True
PACKAGE              : Memory2
QUERY                : OnlyFreeMemoryAllocatedDynamicallyCert
COMPILE_ERROR_OUTPUT : 


```

2023-03-23 02:21 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C
TEST_PASS            : True
COMPILE_PASS         : True
RULE                 : MEM33-C
QUERY                : CopyStructsWithAFlexibleArrayMemberDynamically
PACKAGE              : Memory2
TEST_DIFFERENCE      : 

COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C
TEST_PASS            : True
COMPILE_PASS         : True
RULE                 : MEM33-C
QUERY                : AllocStructsWithAFlexibleArrayMemberDynamically
PACKAGE              : Memory2
TEST_DIFFERENCE      : 

COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C
TEST_PASS            : True
COMPILE_PASS         : True
RULE                 : MEM36-C
QUERY                : DoNotModifyAlignmentOfMemoryWithRealloc
PACKAGE              : Memory2
TEST_DIFFERENCE      : 

COMPILE_ERROR_OUTPUT : 
SUITE                : MISRA-C-2012
TEST_PASS            : False
COMPILE_PASS         : True
RULE                 : RULE-22-1
QUERY                : CloseFileHandleWhenNoLongerNeededMisra
PACKAGE              : Memory2
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 comp 36.3s eval 958ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       

COMPILE_ERROR_OUTPUT : 
SUITE                : MISRA-C-2012
TEST_PASS            : True
COMPILE_PASS         : True
RULE                 : RULE-22-1
QUERY                : FreeMemoryWhenNoLongerNeededMisra
PACKAGE              : Memory2
TEST_DIFFERENCE      : 

COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C
TEST_PASS            : False
COMPILE_PASS         : True
RULE                 : FIO42-C
QUERY                : CloseFilesWhenTheyAreNoLongerNeeded
PACKAGE              : IO1
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,8 +1,6 @@
                        | test.c:7:13:7:17 | call to fopen | The file opened here may not be closed at $@. | test.c:6:31:13:1 | { ... } | this location |
                        | test.c:16:13:16:19 | call to freopen | The file opened here may not be closed at $@. | test.c:15:31:22:1 | { ... } | this location |
                        | test.c:25:13:25:19 | call to freopen | The file opened here may not be closed at $@. | test.c:24:32:31:1 | { ... } | this location |
                       -| test.c:46:13:46:17 | call to fopen | The file opened here may not be closed at $@. | test.c:56:3:56:11 | return ... | this location |
                       -| test.c:85:13:85:17 | call to fopen | The file opened here may not be closed at $@. | test.c:89:3:89:27 | return ... | this location |
                        | test.c:93:13:93:19 | call to freopen | The file opened here may not be closed at $@. | test.c:92:33:104:1 | { ... } | this location |
                        | test.c:107:13:107:17 | call to fopen | The file opened here may not be closed at $@. | test.c:106:30:113:1 | { ... } | this location |
                        | test.c:128:12:128:15 | call to open | The file opened here may not be closed at $@. | test.c:127:30:134:1 | { ... } | this location |
                       [1/1 eval 840ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/c/common/test/rules/closefilehandlewhennolongerneededshared/CloseFileHandleWhenNoLongerNeededShared.ql
                       

COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C
TEST_PASS            : True
COMPILE_PASS         : True
RULE                 : MEM31-C
QUERY                : FreeMemoryWhenNoLongerNeededCert
PACKAGE              : Memory2
TEST_DIFFERENCE      : 

COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C
TEST_PASS            : True
COMPILE_PASS         : True
RULE                 : EXP42-C
QUERY                : DoNotComparePaddingData
PACKAGE              : Memory2
TEST_DIFFERENCE      : 

COMPILE_ERROR_OUTPUT : 
SUITE                : MISRA-C-2012
TEST_PASS            : True
COMPILE_PASS         : True
RULE                 : RULE-22-2
QUERY                : OnlyFreeMemoryAllocatedDynamicallyMisra
PACKAGE              : Memory2
TEST_DIFFERENCE      : 

COMPILE_ERROR_OUTPUT : 
SUITE                : CERT-C
TEST_PASS            : True
COMPILE_PASS         : True
RULE                 : MEM34-C
QUERY                : OnlyFreeMemoryAllocatedDynamicallyCert
PACKAGE              : Memory2
TEST_DIFFERENCE      : 


```

2023-03-23 02:21 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : False
TEST_DIFFERENCE      : 
PACKAGE              : Representation
COMPILE_ERROR_OUTPUT : [2023-03-23 02:21:02] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 02:21:02] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:21:02] [build-stderr]   ~~~~~^
                       [2023-03-23 02:21:02] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 02:21:02] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:21:02] [build-stderr]   ~~~~~^
                       [2023-03-23 02:21:02] [build-stderr] 2 errors generated.
                       [2023-03-23 02:21:03] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
TEST_PASS            : False
QUERY                : MemsetUsedToAccessObjectRepresentation
SUITE                : CERT-C++
RULE                 : EXP62-CPP

COMPILE_PASS         : False
TEST_DIFFERENCE      : 
PACKAGE              : Representation
COMPILE_ERROR_OUTPUT : [2023-03-23 02:21:02] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 02:21:02] [build-stderr]   if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 02:21:02] [build-stderr]        ~~~~~^
                       [2023-03-23 02:21:02] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 02:21:02] [build-stderr]   if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 02:21:02] [build-stderr]        ~~~~~^
                       [2023-03-23 02:21:02] [build-stderr] 2 errors generated.
                       [2023-03-23 02:21:03] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       
TEST_PASS            : False
QUERY                : MemcmpUsedToAccessObjectRepresentation
SUITE                : CERT-C++
RULE                 : EXP62-CPP

COMPILE_PASS         : False
TEST_DIFFERENCE      : 
PACKAGE              : Representation
COMPILE_ERROR_OUTPUT : [2023-03-23 02:21:02] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 02:21:02] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 02:21:02] [build-stderr]   ~~~~~^
                       [2023-03-23 02:21:02] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 02:21:02] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 02:21:02] [build-stderr]   ~~~~~^
                       [2023-03-23 02:21:02] [build-stderr] 2 errors generated.
                       [2023-03-23 02:21:03] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
TEST_PASS            : False
QUERY                : MemcpyUsedToAccessObjectRepresentation
SUITE                : CERT-C++
RULE                 : EXP62-CPP

COMPILE_PASS         : True
TEST_DIFFERENCE      : 
PACKAGE              : Allocations
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
QUERY                : UsingDefaultOperatorNewForOverAlignedTypes
SUITE                : CERT-C++
RULE                 : MEM57-CPP


```

2023-03-23 02:22 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-03-23 11:02 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 11:03 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 11:06 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

SUITE                : CERT-C
RULE                 : MEM33-C
QUERY                : CopyStructsWithAFlexibleArrayMemberDynamically
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Memory2
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True

SUITE                : CERT-C
RULE                 : MEM33-C
QUERY                : AllocStructsWithAFlexibleArrayMemberDynamically
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Memory2
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True

SUITE                : CERT-C
RULE                 : MEM36-C
QUERY                : DoNotModifyAlignmentOfMemoryWithRealloc
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Memory2
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True

SUITE                : MISRA-C-2012
RULE                 : RULE-22-1
QUERY                : CloseFileHandleWhenNoLongerNeededMisra
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Memory2
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True

SUITE                : MISRA-C-2012
RULE                 : RULE-22-1
QUERY                : FreeMemoryWhenNoLongerNeededMisra
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Memory2
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True

SUITE                : CERT-C
RULE                 : FIO42-C
QUERY                : CloseFilesWhenTheyAreNoLongerNeeded
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : IO1
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True

SUITE                : CERT-C
RULE                 : MEM31-C
QUERY                : FreeMemoryWhenNoLongerNeededCert
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Memory2
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True

SUITE                : CERT-C
RULE                 : EXP42-C
QUERY                : DoNotComparePaddingData
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Memory2
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True

SUITE                : MISRA-C-2012
RULE                 : RULE-22-2
QUERY                : OnlyFreeMemoryAllocatedDynamicallyMisra
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Memory2
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True

SUITE                : CERT-C
RULE                 : MEM34-C
QUERY                : OnlyFreeMemoryAllocatedDynamicallyCert
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Memory2
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True


```

2023-03-23 11:07 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Representation
COMPILE_PASS         : False
RULE                 : EXP62-CPP
TEST_PASS            : False
SUITE                : CERT-C++
QUERY                : MemcmpUsedToAccessObjectRepresentation
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f1(const S1&, const S1&)':
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 11:07:13] [build-stderr]    if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 11:07:13] [build-stderr]              ^~~~~~
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp: In function 'void f2(const S2&, const S2&)':
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: 'memcmp' is not a member of 'std'
                       [2023-03-23 11:07:13] [build-stderr]    if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 11:07:13] [build-stderr]              ^~~~~~
                       [2023-03-23 11:07:14] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       

PACKAGE              : Representation
COMPILE_PASS         : False
RULE                 : EXP62-CPP
TEST_PASS            : False
SUITE                : CERT-C++
QUERY                : MemsetUsedToAccessObjectRepresentation
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 11:07:13] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 11:07:13] [build-stderr]         ^~~~~~
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 11:07:13] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 11:07:13] [build-stderr]         ^~~~~~
                       [2023-03-23 11:07:13] [build-stderr]         decay
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 11:07:13] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 11:07:13] [build-stderr]         ^~~~~~
                       [2023-03-23 11:07:14] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       

PACKAGE              : Representation
COMPILE_PASS         : False
RULE                 : EXP62-CPP
TEST_PASS            : False
SUITE                : CERT-C++
QUERY                : MemcpyUsedToAccessObjectRepresentation
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f2()':
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: 'memcpy' is not a member of 'std'
                       [2023-03-23 11:07:13] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 11:07:13] [build-stderr]         ^~~~~~
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: note: suggested alternative: 'decay'
                       [2023-03-23 11:07:13] [build-stderr]    std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 11:07:13] [build-stderr]         ^~~~~~
                       [2023-03-23 11:07:13] [build-stderr]         decay
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp: In function 'void f4()':
                       [2023-03-23 11:07:13] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: 'memset' is not a member of 'std'
                       [2023-03-23 11:07:13] [build-stderr]    std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 11:07:13] [build-stderr]         ^~~~~~
                       [2023-03-23 11:07:14] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       

PACKAGE              : Allocations
COMPILE_PASS         : True
RULE                 : MEM57-CPP
TEST_PASS            : True
SUITE                : CERT-C++
QUERY                : UsingDefaultOperatorNewForOverAlignedTypes
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 


```

2023-03-23 11:08 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

RULE                 : EXP62-CPP
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-03-23 11:07:21] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:23:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 11:07:21] [build-stderr]   if (!std::memcmp(&s1, &s2, sizeof(S1))) { // NON_COMPLIANT
                       [2023-03-23 11:07:21] [build-stderr]        ~~~~~^
                       [2023-03-23 11:07:21] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp:28:13: error: no member named 'memcmp' in namespace 'std'
                       [2023-03-23 11:07:21] [build-stderr]   if (!std::memcmp(&s1.buff, &s2.buff, sizeof(S2::buff))) { // COMPLIANT
                       [2023-03-23 11:07:21] [build-stderr]        ~~~~~^
                       [2023-03-23 11:07:21] [build-stderr] 2 errors generated.
                       [2023-03-23 11:07:22] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/common/test/rules/memcmpusedtocomparepaddingdata/test.cpp])
                       
COMPILE_PASS         : False
SUITE                : CERT-C++
QUERY                : MemcmpUsedToAccessObjectRepresentation
PACKAGE              : Representation
TEST_PASS            : False

RULE                 : EXP62-CPP
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-03-23 11:07:21] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 11:07:21] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 11:07:21] [build-stderr]   ~~~~~^
                       [2023-03-23 11:07:21] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 11:07:21] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 11:07:21] [build-stderr]   ~~~~~^
                       [2023-03-23 11:07:21] [build-stderr] 2 errors generated.
                       [2023-03-23 11:07:22] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
COMPILE_PASS         : False
SUITE                : CERT-C++
QUERY                : MemcpyUsedToAccessObjectRepresentation
PACKAGE              : Representation
TEST_PASS            : False

RULE                 : EXP62-CPP
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-03-23 11:07:21] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:12:8: error: no member named 'memcpy' in namespace 'std'
                       [2023-03-23 11:07:21] [build-stderr]   std::memcpy(s1, 0, sizeof(S1)); // NON_COMPLIANT
                       [2023-03-23 11:07:21] [build-stderr]   ~~~~~^
                       [2023-03-23 11:07:21] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp:39:8: error: no member named 'memset' in namespace 'std'
                       [2023-03-23 11:07:21] [build-stderr]   std::memset(s3, 0, sizeof(S3)); // NON_COMPLIANT
                       [2023-03-23 11:07:21] [build-stderr]   ~~~~~^
                       [2023-03-23 11:07:21] [build-stderr] 2 errors generated.
                       [2023-03-23 11:07:22] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/cert/test/rules/EXP62-CPP/test.cpp])
                       
COMPILE_PASS         : False
SUITE                : CERT-C++
QUERY                : MemsetUsedToAccessObjectRepresentation
PACKAGE              : Representation
TEST_PASS            : False

RULE                 : MEM57-CPP
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
SUITE                : CERT-C++
QUERY                : UsingDefaultOperatorNewForOverAlignedTypes
PACKAGE              : Allocations
TEST_PASS            : True


```

2023-03-23 11:08 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-03-23 21:33 UTC, kraiouchkine commented
/test-performance

2023-03-23 22:07 UTC, jsinglet commented
🏁 Beep Boop! One or things failed during performance testing. Please check the release engineering repo for details.

2023-03-24 12:00 UTC, lcartey requested changes
Good job! I've made a few comments and suggestions around identifying different types of allocations and free expressions, but otherwise looks good.

2023-03-28 17:57 UTC, kraiouchkine commented on cpp/common/src/codingstandards/cpp/rules/freememorywhennolongerneededshared/FreeMemoryWhenNoLongerNeededShared.qll
note: I've also accidentally addressed the change to this file (`freeExprOrIndirect` instead of `freed`) in e073f4ab4 which does not mention the change in the commit message.

2023-03-28 21:15 UTC, lcartey approved these changes

2023-03-28 22:04 UTC, merged