Address False Positives for Autosar
github/codeql-coding-standards pull request #266
Opened 2023-03-23 03:36 UTC by jeongsoolee09

## Description

Address FPs for AUTOSAR `A5-2-6`, `A0-1-1`, `A2-7-3`, and `A15-4-4`.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [x] Queries have been modified for the following rules:
     - A5-2-6 (https://github.com/github/codeql-coding-standards/issues/231)
     - A0-1-1 (https://github.com/github/codeql-coding-standards/issues/230)
     - A2-7-3 (https://github.com/github/codeql-coding-standards/issues/229)
     - A15-4-4 (https://github.com/github/codeql-coding-standards/issues/228)

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2023-03-23 03:37 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-03-23 03:37 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-03-23 03:39 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 03:39 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

TEST_PASS            : True
SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
QUERY                : MissingNoExcept
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
RULE                 : A15-4-4
PACKAGE              : Exceptions1

TEST_PASS            : True
SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
QUERY                : UndocumentedUserDefinedType
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
RULE                 : A2-7-3
PACKAGE              : Comments

TEST_PASS            : True
SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
QUERY                : OperandsOfALogicalAndOrNotParenthesized
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
RULE                 : A5-2-6
PACKAGE              : OrderOfEvaluation

TEST_PASS            : False
SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
QUERY                : UselessAssignment
COMPILE_PASS         : False
COMPILE_ERROR_OUTPUT : [2023-03-23 03:39:52] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:34:9: error: redefinition of 'b5'
                       [2023-03-23 03:39:52] [build-stderr]   auto &b5 = new B();
                       [2023-03-23 03:39:52] [build-stderr]         ^
                       [2023-03-23 03:39:52] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:32:9: note: previous definition is here
                       [2023-03-23 03:39:52] [build-stderr]   auto &b5 = *new B();
                       [2023-03-23 03:39:52] [build-stderr]         ^
                       [2023-03-23 03:39:52] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:68:6: warning: expression result unused [-Wunused-value]
                       [2023-03-23 03:39:52] [build-stderr]   l2 + 5;
                       [2023-03-23 03:39:52] [build-stderr]   ~~ ^ ~
                       [2023-03-23 03:39:52] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:71:5: warning: expression result unused [-Wunused-value]
                       [2023-03-23 03:39:52] [build-stderr]   p + 5;
                       [2023-03-23 03:39:52] [build-stderr]   ~ ^ ~
                       [2023-03-23 03:39:52] [build-stderr] 2 warnings and 1 error generated.
                       [2023-03-23 03:39:52] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp])
                       
RULE                 : A0-1-1
PACKAGE              : DeadCode


```

2023-03-23 03:40 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 03:40 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-03-23 03:40 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-03-23 03:41 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 03:41 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR won't happen because it is outside of license window!

2023-03-23 03:42 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : True
SUITE                : AUTOSAR
PACKAGE              : Exceptions1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : MissingNoExcept
RULE                 : A15-4-4
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
SUITE                : AUTOSAR
PACKAGE              : Comments
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : UndocumentedUserDefinedType
RULE                 : A2-7-3
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
SUITE                : AUTOSAR
PACKAGE              : OrderOfEvaluation
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : OperandsOfALogicalAndOrNotParenthesized
RULE                 : A5-2-6
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : False
SUITE                : AUTOSAR
PACKAGE              : DeadCode
TEST_DIFFERENCE      : 
TEST_PASS            : False
QUERY                : UselessAssignment
RULE                 : A0-1-1
COMPILE_ERROR_OUTPUT : [2023-03-23 03:42:29] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp: In function 'void foo(B&)':
                       [2023-03-23 03:42:29] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:34:9: error: conflicting declaration 'auto& b5'
                       [2023-03-23 03:42:29] [build-stderr]    auto &b5 = new B();
                       [2023-03-23 03:42:29] [build-stderr]          ^~
                       [2023-03-23 03:42:29] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:32:9: note: previous declaration as 'B& b5'
                       [2023-03-23 03:42:29] [build-stderr]    auto &b5 = *new B();
                       [2023-03-23 03:42:29] [build-stderr]          ^~
                       [2023-03-23 03:42:29] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp])
                       


```

2023-03-23 03:42 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Exceptions1
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
RULE                 : A15-4-4
TEST_PASS            : True
SUITE                : AUTOSAR
QUERY                : MissingNoExcept
TEST_DIFFERENCE      : 

PACKAGE              : Comments
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
RULE                 : A2-7-3
TEST_PASS            : True
SUITE                : AUTOSAR
QUERY                : UndocumentedUserDefinedType
TEST_DIFFERENCE      : 

PACKAGE              : OrderOfEvaluation
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
RULE                 : A5-2-6
TEST_PASS            : True
SUITE                : AUTOSAR
QUERY                : OperandsOfALogicalAndOrNotParenthesized
TEST_DIFFERENCE      : 

PACKAGE              : DeadCode
COMPILE_ERROR_OUTPUT : [2023-03-23 03:42:29] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp: In function 'void foo(B&)':
                       [2023-03-23 03:42:29] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:34:9: error: conflicting declaration 'auto& b5'
                       [2023-03-23 03:42:29] [build-stderr]    auto &b5 = new B();
                       [2023-03-23 03:42:29] [build-stderr]          ^~
                       [2023-03-23 03:42:29] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:32:9: note: previous declaration as 'B& b5'
                       [2023-03-23 03:42:29] [build-stderr]    auto &b5 = *new B();
                       [2023-03-23 03:42:29] [build-stderr]          ^~
                       [2023-03-23 03:42:30] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp])
                       
COMPILE_PASS         : False
RULE                 : A0-1-1
TEST_PASS            : False
SUITE                : AUTOSAR
QUERY                : UselessAssignment
TEST_DIFFERENCE      : 


```

2023-03-23 03:42 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

TEST_DIFFERENCE      : 
PACKAGE              : Exceptions1
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
QUERY                : MissingNoExcept
COMPILE_PASS         : True
RULE                 : A15-4-4
SUITE                : AUTOSAR

TEST_DIFFERENCE      : 
PACKAGE              : Comments
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
QUERY                : UndocumentedUserDefinedType
COMPILE_PASS         : True
RULE                 : A2-7-3
SUITE                : AUTOSAR

TEST_DIFFERENCE      : 
PACKAGE              : OrderOfEvaluation
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
QUERY                : OperandsOfALogicalAndOrNotParenthesized
COMPILE_PASS         : True
RULE                 : A5-2-6
SUITE                : AUTOSAR

TEST_DIFFERENCE      : 
PACKAGE              : DeadCode
COMPILE_ERROR_OUTPUT : [2023-03-23 03:42:31] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:34:9: error: redefinition of 'b5'
                       [2023-03-23 03:42:31] [build-stderr]   auto &b5 = new B();
                       [2023-03-23 03:42:31] [build-stderr]         ^
                       [2023-03-23 03:42:31] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:32:9: note: previous definition is here
                       [2023-03-23 03:42:31] [build-stderr]   auto &b5 = *new B();
                       [2023-03-23 03:42:31] [build-stderr]         ^
                       [2023-03-23 03:42:31] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:68:6: warning: expression result unused [-Wunused-value]
                       [2023-03-23 03:42:31] [build-stderr]   l2 + 5;
                       [2023-03-23 03:42:31] [build-stderr]   ~~ ^ ~
                       [2023-03-23 03:42:31] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp:71:5: warning: expression result unused [-Wunused-value]
                       [2023-03-23 03:42:31] [build-stderr]   p + 5;
                       [2023-03-23 03:42:31] [build-stderr]   ~ ^ ~
                       [2023-03-23 03:42:31] [build-stderr] 2 warnings and 1 error generated.
                       [2023-03-23 03:42:32] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, clang++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/test.cpp])
                       
TEST_PASS            : False
QUERY                : UselessAssignment
COMPILE_PASS         : False
RULE                 : A0-1-1
SUITE                : AUTOSAR


```

2023-03-23 03:42 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-03-23 03:42 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-03-24 17:39 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-03-24 17:39 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-03-24 17:41 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

QUERY                : MissingNoExcept
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Exceptions1
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
RULE                 : A15-4-4
TEST_DIFFERENCE      : 

QUERY                : UndocumentedUserDefinedType
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Comments
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
RULE                 : A2-7-3
TEST_DIFFERENCE      : 

QUERY                : OperandsOfALogicalAndOrNotParenthesized
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : OrderOfEvaluation
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
RULE                 : A5-2-6
TEST_DIFFERENCE      : 

QUERY                : UselessAssignment
SUITE                : AUTOSAR
TEST_PASS            : False
PACKAGE              : DeadCode
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
RULE                 : A0-1-1
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,14 +1,14 @@
                       -| test.cpp:22:10:22:11 | 0 | Definition of $@ is unused. | test.cpp:22:7:22:7 | y | y |
                       -| test.cpp:25:3:25:5 | ... ++ | Definition of $@ is unused. | test.cpp:24:7:24:7 | z | z |
                       -| test.cpp:42:3:42:7 | ... = ... | Definition of $@ is unused. | test.cpp:20:41:20:41 | p | p |
                       -| test.cpp:44:10:44:11 | 0 | Definition of $@ is unused. | test.cpp:44:7:44:8 | l3 | l3 |
                       -| test.cpp:45:13:45:22 | new | Definition of $@ is unused. | test.cpp:45:8:45:9 | l4 | l4 |
                       -| test.cpp:48:8:48:8 | {...} | Definition of $@ is unused. | test.cpp:48:5:48:6 | a2 | a2 |
                       -| test.cpp:49:11:49:15 | new | Definition of $@ is unused. | test.cpp:49:6:49:7 | a3 | a3 |
                       -| test.cpp:50:11:50:17 | new | Definition of $@ is unused. | test.cpp:50:6:50:7 | a4 | a4 |
                       -| test.cpp:51:11:51:17 | 0 | Definition of $@ is unused. | test.cpp:51:6:51:7 | a5 | a5 |
                       -| test.cpp:55:3:55:10 | ... = ... | Definition of $@ is unused. | test.cpp:52:5:52:6 | a6 | a6 |
                       -| test.cpp:60:11:60:15 | new | Definition of $@ is unused. | test.cpp:60:6:60:7 | b3 | b3 |
                       -| test.cpp:61:11:61:17 | new | Definition of $@ is unused. | test.cpp:61:6:61:7 | b4 | b4 |
                       -| test.cpp:62:11:62:17 | 0 | Definition of $@ is unused. | test.cpp:62:6:62:7 | b5 | b5 |
                       -| test.cpp:70:11:70:17 | 0 | Definition of $@ is unused. | test.cpp:70:6:70:7 | c5 | c5 |
                       +| test.cpp:55:10:55:11 | 0 | Definition of $@ is unused. | test.cpp:55:7:55:7 | y | y |
                       +| test.cpp:58:3:58:5 | ... ++ | Definition of $@ is unused. | test.cpp:57:7:57:7 | z | z |
                       +| test.cpp:75:3:75:7 | ... = ... | Definition of $@ is unused. | test.cpp:53:41:53:41 | p | p |
                       +| test.cpp:77:10:77:11 | 0 | Definition of $@ is unused. | test.cpp:77:7:77:8 | l3 | l3 |
                       +| test.cpp:78:13:78:22 | new | Definition of $@ is unused. | test.cpp:78:8:78:9 | l4 | l4 |
                       +| test.cpp:81:8:81:8 | {...} | Definition of $@ is unused. | test.cpp:81:5:81:6 | a2 | a2 |
                       +| test.cpp:82:11:82:15 | new | Definition of $@ is unused. | test.cpp:82:6:82:7 | a3 | a3 |
                       +| test.cpp:83:11:83:17 | new | Definition of $@ is unused. | test.cpp:83:6:83:7 | a4 | a4 |
                       +| test.cpp:84:11:84:17 | 0 | Definition of $@ is unused. | test.cpp:84:6:84:7 | a5 | a5 |
                       +| test.cpp:88:3:88:10 | ... = ... | Definition of $@ is unused. | test.cpp:85:5:85:6 | a6 | a6 |
                       +| test.cpp:93:11:93:15 | new | Definition of $@ is unused. | test.cpp:93:6:93:7 | b3 | b3 |
                       +| test.cpp:94:11:94:17 | new | Definition of $@ is unused. | test.cpp:94:6:94:7 | b4 | b4 |
                       +| test.cpp:95:11:95:17 | 0 | Definition of $@ is unused. | test.cpp:95:6:95:7 | b5 | b5 |
                       +| test.cpp:103:11:103:17 | 0 | Definition of $@ is unused. | test.cpp:103:6:103:7 | c5 | c5 |
                       [1/1 comp 24.4s eval 1.6s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/UselessAssignment.qlref
                       


```

2023-03-24 17:41 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : True
TEST_DIFFERENCE      : 
QUERY                : MissingNoExcept
RULE                 : A15-4-4
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Exceptions1
TEST_PASS            : True

COMPILE_PASS         : True
TEST_DIFFERENCE      : 
QUERY                : UndocumentedUserDefinedType
RULE                 : A2-7-3
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Comments
TEST_PASS            : True

COMPILE_PASS         : True
TEST_DIFFERENCE      : 
QUERY                : OperandsOfALogicalAndOrNotParenthesized
RULE                 : A5-2-6
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : OrderOfEvaluation
TEST_PASS            : True

COMPILE_PASS         : True
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,14 +1,14 @@
                       -| test.cpp:22:10:22:11 | 0 | Definition of $@ is unused. | test.cpp:22:7:22:7 | y | y |
                       -| test.cpp:25:3:25:5 | ... ++ | Definition of $@ is unused. | test.cpp:24:7:24:7 | z | z |
                       -| test.cpp:42:3:42:7 | ... = ... | Definition of $@ is unused. | test.cpp:20:41:20:41 | p | p |
                       -| test.cpp:44:10:44:11 | 0 | Definition of $@ is unused. | test.cpp:44:7:44:8 | l3 | l3 |
                       -| test.cpp:45:13:45:22 | new | Definition of $@ is unused. | test.cpp:45:8:45:9 | l4 | l4 |
                       -| test.cpp:48:8:48:8 | {...} | Definition of $@ is unused. | test.cpp:48:5:48:6 | a2 | a2 |
                       -| test.cpp:49:11:49:15 | new | Definition of $@ is unused. | test.cpp:49:6:49:7 | a3 | a3 |
                       -| test.cpp:50:11:50:17 | new | Definition of $@ is unused. | test.cpp:50:6:50:7 | a4 | a4 |
                       -| test.cpp:51:11:51:17 | 0 | Definition of $@ is unused. | test.cpp:51:6:51:7 | a5 | a5 |
                       -| test.cpp:55:3:55:10 | ... = ... | Definition of $@ is unused. | test.cpp:52:5:52:6 | a6 | a6 |
                       -| test.cpp:60:11:60:15 | new | Definition of $@ is unused. | test.cpp:60:6:60:7 | b3 | b3 |
                       -| test.cpp:61:11:61:17 | new | Definition of $@ is unused. | test.cpp:61:6:61:7 | b4 | b4 |
                       -| test.cpp:62:11:62:17 | 0 | Definition of $@ is unused. | test.cpp:62:6:62:7 | b5 | b5 |
                       -| test.cpp:70:11:70:17 | 0 | Definition of $@ is unused. | test.cpp:70:6:70:7 | c5 | c5 |
                       +| test.cpp:55:10:55:11 | 0 | Definition of $@ is unused. | test.cpp:55:7:55:7 | y | y |
                       +| test.cpp:58:3:58:5 | ... ++ | Definition of $@ is unused. | test.cpp:57:7:57:7 | z | z |
                       +| test.cpp:75:3:75:7 | ... = ... | Definition of $@ is unused. | test.cpp:53:41:53:41 | p | p |
                       +| test.cpp:77:10:77:11 | 0 | Definition of $@ is unused. | test.cpp:77:7:77:8 | l3 | l3 |
                       +| test.cpp:78:13:78:22 | new | Definition of $@ is unused. | test.cpp:78:8:78:9 | l4 | l4 |
                       +| test.cpp:81:8:81:8 | {...} | Definition of $@ is unused. | test.cpp:81:5:81:6 | a2 | a2 |
                       +| test.cpp:82:11:82:15 | new | Definition of $@ is unused. | test.cpp:82:6:82:7 | a3 | a3 |
                       +| test.cpp:83:11:83:17 | new | Definition of $@ is unused. | test.cpp:83:6:83:7 | a4 | a4 |
                       +| test.cpp:84:11:84:17 | 0 | Definition of $@ is unused. | test.cpp:84:6:84:7 | a5 | a5 |
                       +| test.cpp:88:3:88:10 | ... = ... | Definition of $@ is unused. | test.cpp:85:5:85:6 | a6 | a6 |
                       +| test.cpp:93:11:93:15 | new | Definition of $@ is unused. | test.cpp:93:6:93:7 | b3 | b3 |
                       +| test.cpp:94:11:94:17 | new | Definition of $@ is unused. | test.cpp:94:6:94:7 | b4 | b4 |
                       +| test.cpp:95:11:95:17 | 0 | Definition of $@ is unused. | test.cpp:95:6:95:7 | b5 | b5 |
                       +| test.cpp:103:11:103:17 | 0 | Definition of $@ is unused. | test.cpp:103:6:103:7 | c5 | c5 |
                       [1/1 comp 27s eval 1.7s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/UselessAssignment.qlref
                       
QUERY                : UselessAssignment
RULE                 : A0-1-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : DeadCode
TEST_PASS            : False


```

2023-03-24 17:41 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

TEST_PASS            : True
SUITE                : AUTOSAR
RULE                 : A15-4-4
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : MissingNoExcept
PACKAGE              : Exceptions1

TEST_PASS            : True
SUITE                : AUTOSAR
RULE                 : A2-7-3
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : UndocumentedUserDefinedType
PACKAGE              : Comments

TEST_PASS            : True
SUITE                : AUTOSAR
RULE                 : A5-2-6
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : OperandsOfALogicalAndOrNotParenthesized
PACKAGE              : OrderOfEvaluation

TEST_PASS            : False
SUITE                : AUTOSAR
RULE                 : A0-1-1
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,14 +1,14 @@
                       -| test.cpp:22:10:22:11 | 0 | Definition of $@ is unused. | test.cpp:22:7:22:7 | y | y |
                       -| test.cpp:25:3:25:5 | ... ++ | Definition of $@ is unused. | test.cpp:24:7:24:7 | z | z |
                       -| test.cpp:42:3:42:7 | ... = ... | Definition of $@ is unused. | test.cpp:20:41:20:41 | p | p |
                       -| test.cpp:44:10:44:11 | 0 | Definition of $@ is unused. | test.cpp:44:7:44:8 | l3 | l3 |
                       -| test.cpp:45:13:45:22 | new | Definition of $@ is unused. | test.cpp:45:8:45:9 | l4 | l4 |
                       -| test.cpp:48:8:48:8 | {...} | Definition of $@ is unused. | test.cpp:48:5:48:6 | a2 | a2 |
                       -| test.cpp:49:11:49:15 | new | Definition of $@ is unused. | test.cpp:49:6:49:7 | a3 | a3 |
                       -| test.cpp:50:11:50:17 | new | Definition of $@ is unused. | test.cpp:50:6:50:7 | a4 | a4 |
                       -| test.cpp:51:11:51:17 | 0 | Definition of $@ is unused. | test.cpp:51:6:51:7 | a5 | a5 |
                       -| test.cpp:55:3:55:10 | ... = ... | Definition of $@ is unused. | test.cpp:52:5:52:6 | a6 | a6 |
                       -| test.cpp:60:11:60:15 | new | Definition of $@ is unused. | test.cpp:60:6:60:7 | b3 | b3 |
                       -| test.cpp:61:11:61:17 | new | Definition of $@ is unused. | test.cpp:61:6:61:7 | b4 | b4 |
                       -| test.cpp:62:11:62:17 | 0 | Definition of $@ is unused. | test.cpp:62:6:62:7 | b5 | b5 |
                       -| test.cpp:70:11:70:17 | 0 | Definition of $@ is unused. | test.cpp:70:6:70:7 | c5 | c5 |
                       +| test.cpp:55:10:55:11 | 0 | Definition of $@ is unused. | test.cpp:55:7:55:7 | y | y |
                       +| test.cpp:58:3:58:5 | ... ++ | Definition of $@ is unused. | test.cpp:57:7:57:7 | z | z |
                       +| test.cpp:75:3:75:7 | ... = ... | Definition of $@ is unused. | test.cpp:53:41:53:41 | p | p |
                       +| test.cpp:77:10:77:11 | 0 | Definition of $@ is unused. | test.cpp:77:7:77:8 | l3 | l3 |
                       +| test.cpp:78:13:78:22 | new | Definition of $@ is unused. | test.cpp:78:8:78:9 | l4 | l4 |
                       +| test.cpp:81:8:81:8 | {...} | Definition of $@ is unused. | test.cpp:81:5:81:6 | a2 | a2 |
                       +| test.cpp:82:11:82:15 | new | Definition of $@ is unused. | test.cpp:82:6:82:7 | a3 | a3 |
                       +| test.cpp:83:11:83:17 | new | Definition of $@ is unused. | test.cpp:83:6:83:7 | a4 | a4 |
                       +| test.cpp:84:11:84:17 | 0 | Definition of $@ is unused. | test.cpp:84:6:84:7 | a5 | a5 |
                       +| test.cpp:88:3:88:10 | ... = ... | Definition of $@ is unused. | test.cpp:85:5:85:6 | a6 | a6 |
                       +| test.cpp:93:11:93:15 | new | Definition of $@ is unused. | test.cpp:93:6:93:7 | b3 | b3 |
                       +| test.cpp:94:11:94:17 | new | Definition of $@ is unused. | test.cpp:94:6:94:7 | b4 | b4 |
                       +| test.cpp:95:11:95:17 | 0 | Definition of $@ is unused. | test.cpp:95:6:95:7 | b5 | b5 |
                       +| test.cpp:103:11:103:17 | 0 | Definition of $@ is unused. | test.cpp:103:6:103:7 | c5 | c5 |
                       [1/1 comp 25.7s eval 1.6s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/UselessAssignment.qlref
                       
QUERY                : UselessAssignment
PACKAGE              : DeadCode


```

2023-03-24 17:41 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

TEST_DIFFERENCE      : 
QUERY                : MissingNoExcept
COMPILE_PASS         : True
PACKAGE              : Exceptions1
TEST_PASS            : True
RULE                 : A15-4-4
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

TEST_DIFFERENCE      : 
QUERY                : UndocumentedUserDefinedType
COMPILE_PASS         : True
PACKAGE              : Comments
TEST_PASS            : True
RULE                 : A2-7-3
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

TEST_DIFFERENCE      : 
QUERY                : OperandsOfALogicalAndOrNotParenthesized
COMPILE_PASS         : True
PACKAGE              : OrderOfEvaluation
TEST_PASS            : True
RULE                 : A5-2-6
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,14 +1,14 @@
                       -| test.cpp:22:10:22:11 | 0 | Definition of $@ is unused. | test.cpp:22:7:22:7 | y | y |
                       -| test.cpp:25:3:25:5 | ... ++ | Definition of $@ is unused. | test.cpp:24:7:24:7 | z | z |
                       -| test.cpp:42:3:42:7 | ... = ... | Definition of $@ is unused. | test.cpp:20:41:20:41 | p | p |
                       -| test.cpp:44:10:44:11 | 0 | Definition of $@ is unused. | test.cpp:44:7:44:8 | l3 | l3 |
                       -| test.cpp:45:13:45:22 | new | Definition of $@ is unused. | test.cpp:45:8:45:9 | l4 | l4 |
                       -| test.cpp:48:8:48:8 | {...} | Definition of $@ is unused. | test.cpp:48:5:48:6 | a2 | a2 |
                       -| test.cpp:49:11:49:15 | new | Definition of $@ is unused. | test.cpp:49:6:49:7 | a3 | a3 |
                       -| test.cpp:50:11:50:17 | new | Definition of $@ is unused. | test.cpp:50:6:50:7 | a4 | a4 |
                       -| test.cpp:51:11:51:17 | 0 | Definition of $@ is unused. | test.cpp:51:6:51:7 | a5 | a5 |
                       -| test.cpp:55:3:55:10 | ... = ... | Definition of $@ is unused. | test.cpp:52:5:52:6 | a6 | a6 |
                       -| test.cpp:60:11:60:15 | new | Definition of $@ is unused. | test.cpp:60:6:60:7 | b3 | b3 |
                       -| test.cpp:61:11:61:17 | new | Definition of $@ is unused. | test.cpp:61:6:61:7 | b4 | b4 |
                       -| test.cpp:62:11:62:17 | 0 | Definition of $@ is unused. | test.cpp:62:6:62:7 | b5 | b5 |
                       -| test.cpp:70:11:70:17 | 0 | Definition of $@ is unused. | test.cpp:70:6:70:7 | c5 | c5 |
                       +| test.cpp:55:10:55:11 | 0 | Definition of $@ is unused. | test.cpp:55:7:55:7 | y | y |
                       +| test.cpp:58:3:58:5 | ... ++ | Definition of $@ is unused. | test.cpp:57:7:57:7 | z | z |
                       +| test.cpp:75:3:75:7 | ... = ... | Definition of $@ is unused. | test.cpp:53:41:53:41 | p | p |
                       +| test.cpp:77:10:77:11 | 0 | Definition of $@ is unused. | test.cpp:77:7:77:8 | l3 | l3 |
                       +| test.cpp:78:13:78:22 | new | Definition of $@ is unused. | test.cpp:78:8:78:9 | l4 | l4 |
                       +| test.cpp:81:8:81:8 | {...} | Definition of $@ is unused. | test.cpp:81:5:81:6 | a2 | a2 |
                       +| test.cpp:82:11:82:15 | new | Definition of $@ is unused. | test.cpp:82:6:82:7 | a3 | a3 |
                       +| test.cpp:83:11:83:17 | new | Definition of $@ is unused. | test.cpp:83:6:83:7 | a4 | a4 |
                       +| test.cpp:84:11:84:17 | 0 | Definition of $@ is unused. | test.cpp:84:6:84:7 | a5 | a5 |
                       +| test.cpp:88:3:88:10 | ... = ... | Definition of $@ is unused. | test.cpp:85:5:85:6 | a6 | a6 |
                       +| test.cpp:93:11:93:15 | new | Definition of $@ is unused. | test.cpp:93:6:93:7 | b3 | b3 |
                       +| test.cpp:94:11:94:17 | new | Definition of $@ is unused. | test.cpp:94:6:94:7 | b4 | b4 |
                       +| test.cpp:95:11:95:17 | 0 | Definition of $@ is unused. | test.cpp:95:6:95:7 | b5 | b5 |
                       +| test.cpp:103:11:103:17 | 0 | Definition of $@ is unused. | test.cpp:103:6:103:7 | c5 | c5 |
                       [1/1 comp 25.3s eval 1.7s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/UselessAssignment.qlref
                       
QUERY                : UselessAssignment
COMPILE_PASS         : True
PACKAGE              : DeadCode
TEST_PASS            : False
RULE                 : A0-1-1
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR


```

2023-03-24 17:42 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Exceptions1
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : MissingNoExcept
RULE                 : A15-4-4
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Comments
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : UndocumentedUserDefinedType
RULE                 : A2-7-3
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : OrderOfEvaluation
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : OperandsOfALogicalAndOrNotParenthesized
RULE                 : A5-2-6
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : DeadCode
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR
TEST_PASS            : False
QUERY                : UselessAssignment
RULE                 : A0-1-1
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,14 +1,14 @@
                       -| test.cpp:22:10:22:11 | 0 | Definition of $@ is unused. | test.cpp:22:7:22:7 | y | y |
                       -| test.cpp:25:3:25:5 | ... ++ | Definition of $@ is unused. | test.cpp:24:7:24:7 | z | z |
                       -| test.cpp:42:3:42:7 | ... = ... | Definition of $@ is unused. | test.cpp:20:41:20:41 | p | p |
                       -| test.cpp:44:10:44:11 | 0 | Definition of $@ is unused. | test.cpp:44:7:44:8 | l3 | l3 |
                       -| test.cpp:45:13:45:22 | new | Definition of $@ is unused. | test.cpp:45:8:45:9 | l4 | l4 |
                       -| test.cpp:48:8:48:8 | {...} | Definition of $@ is unused. | test.cpp:48:5:48:6 | a2 | a2 |
                       -| test.cpp:49:11:49:15 | new | Definition of $@ is unused. | test.cpp:49:6:49:7 | a3 | a3 |
                       -| test.cpp:50:11:50:17 | new | Definition of $@ is unused. | test.cpp:50:6:50:7 | a4 | a4 |
                       -| test.cpp:51:11:51:17 | 0 | Definition of $@ is unused. | test.cpp:51:6:51:7 | a5 | a5 |
                       -| test.cpp:55:3:55:10 | ... = ... | Definition of $@ is unused. | test.cpp:52:5:52:6 | a6 | a6 |
                       -| test.cpp:60:11:60:15 | new | Definition of $@ is unused. | test.cpp:60:6:60:7 | b3 | b3 |
                       -| test.cpp:61:11:61:17 | new | Definition of $@ is unused. | test.cpp:61:6:61:7 | b4 | b4 |
                       -| test.cpp:62:11:62:17 | 0 | Definition of $@ is unused. | test.cpp:62:6:62:7 | b5 | b5 |
                       -| test.cpp:70:11:70:17 | 0 | Definition of $@ is unused. | test.cpp:70:6:70:7 | c5 | c5 |
                       +| test.cpp:55:10:55:11 | 0 | Definition of $@ is unused. | test.cpp:55:7:55:7 | y | y |
                       +| test.cpp:58:3:58:5 | ... ++ | Definition of $@ is unused. | test.cpp:57:7:57:7 | z | z |
                       +| test.cpp:75:3:75:7 | ... = ... | Definition of $@ is unused. | test.cpp:53:41:53:41 | p | p |
                       +| test.cpp:77:10:77:11 | 0 | Definition of $@ is unused. | test.cpp:77:7:77:8 | l3 | l3 |
                       +| test.cpp:78:13:78:22 | new | Definition of $@ is unused. | test.cpp:78:8:78:9 | l4 | l4 |
                       +| test.cpp:81:8:81:8 | {...} | Definition of $@ is unused. | test.cpp:81:5:81:6 | a2 | a2 |
                       +| test.cpp:82:11:82:15 | new | Definition of $@ is unused. | test.cpp:82:6:82:7 | a3 | a3 |
                       +| test.cpp:83:11:83:17 | new | Definition of $@ is unused. | test.cpp:83:6:83:7 | a4 | a4 |
                       +| test.cpp:84:11:84:17 | 0 | Definition of $@ is unused. | test.cpp:84:6:84:7 | a5 | a5 |
                       +| test.cpp:88:3:88:10 | ... = ... | Definition of $@ is unused. | test.cpp:85:5:85:6 | a6 | a6 |
                       +| test.cpp:93:11:93:15 | new | Definition of $@ is unused. | test.cpp:93:6:93:7 | b3 | b3 |
                       +| test.cpp:94:11:94:17 | new | Definition of $@ is unused. | test.cpp:94:6:94:7 | b4 | b4 |
                       +| test.cpp:95:11:95:17 | 0 | Definition of $@ is unused. | test.cpp:95:6:95:7 | b5 | b5 |
                       +| test.cpp:103:11:103:17 | 0 | Definition of $@ is unused. | test.cpp:103:6:103:7 | c5 | c5 |
                       [1/1 comp 25.8s eval 1.6s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/UselessAssignment.qlref
                       
COMPILE_PASS         : True


```

2023-03-24 17:45 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : True
PACKAGE              : Exceptions1
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A15-4-4
QUERY                : MissingNoExcept
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
PACKAGE              : Comments
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A2-7-3
QUERY                : UndocumentedUserDefinedType
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
PACKAGE              : OrderOfEvaluation
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A5-2-6
QUERY                : OperandsOfALogicalAndOrNotParenthesized
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 

COMPILE_PASS         : True
PACKAGE              : DeadCode
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,14 +1,14 @@
                       -| test.cpp:22:10:22:11 | 0 | Definition of $@ is unused. | test.cpp:22:7:22:7 | y | y |
                       -| test.cpp:25:3:25:5 | ... ++ | Definition of $@ is unused. | test.cpp:24:7:24:7 | z | z |
                       -| test.cpp:42:3:42:7 | ... = ... | Definition of $@ is unused. | test.cpp:20:41:20:41 | p | p |
                       -| test.cpp:44:10:44:11 | 0 | Definition of $@ is unused. | test.cpp:44:7:44:8 | l3 | l3 |
                       -| test.cpp:45:13:45:22 | new | Definition of $@ is unused. | test.cpp:45:8:45:9 | l4 | l4 |
                       -| test.cpp:48:8:48:8 | {...} | Definition of $@ is unused. | test.cpp:48:5:48:6 | a2 | a2 |
                       -| test.cpp:49:11:49:15 | new | Definition of $@ is unused. | test.cpp:49:6:49:7 | a3 | a3 |
                       -| test.cpp:50:11:50:17 | new | Definition of $@ is unused. | test.cpp:50:6:50:7 | a4 | a4 |
                       -| test.cpp:51:11:51:17 | 0 | Definition of $@ is unused. | test.cpp:51:6:51:7 | a5 | a5 |
                       -| test.cpp:55:3:55:10 | ... = ... | Definition of $@ is unused. | test.cpp:52:5:52:6 | a6 | a6 |
                       -| test.cpp:60:11:60:15 | new | Definition of $@ is unused. | test.cpp:60:6:60:7 | b3 | b3 |
                       -| test.cpp:61:11:61:17 | new | Definition of $@ is unused. | test.cpp:61:6:61:7 | b4 | b4 |
                       -| test.cpp:62:11:62:17 | 0 | Definition of $@ is unused. | test.cpp:62:6:62:7 | b5 | b5 |
                       -| test.cpp:70:11:70:17 | 0 | Definition of $@ is unused. | test.cpp:70:6:70:7 | c5 | c5 |
                       +| test.cpp:55:10:55:11 | 0 | Definition of $@ is unused. | test.cpp:55:7:55:7 | y | y |
                       +| test.cpp:58:3:58:5 | ... ++ | Definition of $@ is unused. | test.cpp:57:7:57:7 | z | z |
                       +| test.cpp:75:3:75:7 | ... = ... | Definition of $@ is unused. | test.cpp:53:41:53:41 | p | p |
                       +| test.cpp:77:10:77:11 | 0 | Definition of $@ is unused. | test.cpp:77:7:77:8 | l3 | l3 |
                       +| test.cpp:78:13:78:22 | new | Definition of $@ is unused. | test.cpp:78:8:78:9 | l4 | l4 |
                       +| test.cpp:81:8:81:8 | {...} | Definition of $@ is unused. | test.cpp:81:5:81:6 | a2 | a2 |
                       +| test.cpp:82:11:82:15 | new | Definition of $@ is unused. | test.cpp:82:6:82:7 | a3 | a3 |
                       +| test.cpp:83:11:83:17 | new | Definition of $@ is unused. | test.cpp:83:6:83:7 | a4 | a4 |
                       +| test.cpp:84:11:84:17 | 0 | Definition of $@ is unused. | test.cpp:84:6:84:7 | a5 | a5 |
                       +| test.cpp:88:3:88:10 | ... = ... | Definition of $@ is unused. | test.cpp:85:5:85:6 | a6 | a6 |
                       +| test.cpp:93:11:93:15 | new | Definition of $@ is unused. | test.cpp:93:6:93:7 | b3 | b3 |
                       +| test.cpp:94:11:94:17 | new | Definition of $@ is unused. | test.cpp:94:6:94:7 | b4 | b4 |
                       +| test.cpp:95:11:95:17 | 0 | Definition of $@ is unused. | test.cpp:95:6:95:7 | b5 | b5 |
                       +| test.cpp:103:11:103:17 | 0 | Definition of $@ is unused. | test.cpp:103:6:103:7 | c5 | c5 |
                       [1/1 comp 25.7s eval 1.6s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-1-1/UselessAssignment.qlref
                       
TEST_PASS            : False
RULE                 : A0-1-1
QUERY                : UselessAssignment
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 


```

2023-03-24 17:47 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-03-24 17:47 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-03-24 17:48 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-03-24 17:48 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-04-25 16:58 UTC, lcartey requested changes

2023-04-25 16:58 UTC, lcartey commented on cpp/autosar/src/rules/A5-2-6/OperandsOfALogicalAndOrNotParenthesized.ql
> -from BinaryLogicalOperation op, BinaryOperation binop
Given the query, I don't see how the false positives that were reported can occur. Let's exclude this query for now.

2023-04-25 18:59 UTC, jeongsoolee09 commented
/test-performance

2023-04-25 20:46 UTC, jsinglet commented
🏁 Beep Boop! Performance testing complete! See below for performance of the last 3 runs vs your PR. Times are based on predicate performance. You can **find full graphs and stats** in the PR that was created for this test in the release engineering repo. <br><br>
``` 

Release                            : v2.16.0
Platform                           : x86-windows
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 4331785
Mean_Predicate_Execution_Time_Ms   : 105.99973082758284
Median_Predicate_Execution_Time_Ms : 3.0
Standard_Deviation_Ms              : 1637.699653887729
Total_Serialized_Execution_Time_s  : 4331.785
Mean_Query_Execution_Time_s        : 0.1059997308275828
Median_Predicate_Execution_Time_s  : 0.003
Percentile95_Ms                    : 212.75
Number_of_Predicates               : 40866

Release                            : v2.16.0
Platform                           : x86-windows
Language                           : c
Total_Serialized_Execution_Time_Ms : 3999178
Mean_Predicate_Execution_Time_Ms   : 113.4228991179557
Median_Predicate_Execution_Time_Ms : 3.0
Standard_Deviation_Ms              : 1103.0147423251333
Total_Serialized_Execution_Time_s  : 3999.178
Mean_Query_Execution_Time_s        : 0.1134228991179557
Median_Predicate_Execution_Time_s  : 0.003
Percentile95_Ms                    : 259.09999999999854
Number_of_Predicates               : 35259

Release                            : v2.16.0
Platform                           : x86-linux
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 3777037
Mean_Predicate_Execution_Time_Ms   : 91.0502374466649
Median_Predicate_Execution_Time_Ms : 2.0
Standard_Deviation_Ms              : 1411.7135113472114
Total_Serialized_Execution_Time_s  : 3777.037
Mean_Query_Execution_Time_s        : 0.0910502374466648
Median_Predicate_Execution_Time_s  : 0.002
Percentile95_Ms                    : 184.0
Number_of_Predicates               : 41483

Release                            : v2.16.0
Platform                           : x86-linux
Language                           : c
Total_Serialized_Execution_Time_Ms : 3379162
Mean_Predicate_Execution_Time_Ms   : 96.03711703518444
Median_Predicate_Execution_Time_Ms : 2.0
Standard_Deviation_Ms              : 944.2535967382436
Total_Serialized_Execution_Time_s  : 3379.162
Mean_Query_Execution_Time_s        : 0.0960371170351844
Median_Predicate_Execution_Time_s  : 0.002
Percentile95_Ms                    : 222.0
Number_of_Predicates               : 35186

Release                            : v2.17.0
Platform                           : x86-windows
Language                           : c
Total_Serialized_Execution_Time_Ms : 4053540
Mean_Predicate_Execution_Time_Ms   : 108.2098238120662
Median_Predicate_Execution_Time_Ms : 3.0
Standard_Deviation_Ms              : 1088.808074483044
Total_Serialized_Execution_Time_s  : 4053.54
Mean_Query_Execution_Time_s        : 0.1082098238120662
Median_Predicate_Execution_Time_s  : 0.003
Percentile95_Ms                    : 242.04999999999563
Number_of_Predicates               : 37460

Release                            : v2.17.0
Platform                           : x86-linux
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 3858250
Mean_Predicate_Execution_Time_Ms   : 93.85871019534386
Median_Predicate_Execution_Time_Ms : 2.0
Standard_Deviation_Ms              : 1447.0414494039944
Total_Serialized_Execution_Time_s  : 3858.25
Mean_Query_Execution_Time_s        : 0.0938587101953438
Median_Predicate_Execution_Time_s  : 0.002
Percentile95_Ms                    : 192.0
Number_of_Predicates               : 41107

Release                            : v2.17.0
Platform                           : x86-linux
Language                           : c
Total_Serialized_Execution_Time_Ms : 3525590
Mean_Predicate_Execution_Time_Ms   : 94.9884146998599
Median_Predicate_Execution_Time_Ms : 2.0
Standard_Deviation_Ms              : 941.8790232205084
Total_Serialized_Execution_Time_s  : 3525.59
Mean_Query_Execution_Time_s        : 0.0949884146998599
Median_Predicate_Execution_Time_s  : 0.002
Percentile95_Ms                    : 219.0
Number_of_Predicates               : 37116

Release                            : v2.17.0
Platform                           : x86-windows
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 4466387
Mean_Predicate_Execution_Time_Ms   : 109.18926781567046
Median_Predicate_Execution_Time_Ms : 3.0
Standard_Deviation_Ms              : 1678.6709579121289
Total_Serialized_Execution_Time_s  : 4466.387
Mean_Query_Execution_Time_s        : 0.1091892678156704
Median_Predicate_Execution_Time_s  : 0.003
Percentile95_Ms                    : 217.0
Number_of_Predicates               : 40905

Release                            : 266
Platform                           : x86-linux
Language                           : cpp
Total_Serialized_Execution_Time_Ms : 3167973
Mean_Predicate_Execution_Time_Ms   : 76.94671006290835
Median_Predicate_Execution_Time_Ms : 1.0
Standard_Deviation_Ms              : 1159.6684638738432
Total_Serialized_Execution_Time_s  : 3167.973
Mean_Query_Execution_Time_s        : 0.0769467100629083
Median_Predicate_Execution_Time_s  : 0.001
Percentile95_Ms                    : 154.0
Number_of_Predicates               : 41171

Release                            : 266
Platform                           : x86-linux
Language                           : c
Total_Serialized_Execution_Time_Ms : 2921654
Mean_Predicate_Execution_Time_Ms   : 78.80175855000539
Median_Predicate_Execution_Time_Ms : 1.0
Standard_Deviation_Ms              : 769.4812208819408
Total_Serialized_Execution_Time_s  : 2921.654
Mean_Query_Execution_Time_s        : 0.0788017585500053
Median_Predicate_Execution_Time_s  : 0.001
Percentile95_Ms                    : 183.0
Number_of_Predicates               : 37076


```
🏁 Below are the slowest predicates for the last 2 releases vs this PR. <br><br>
``` 

Release           : v2.17.0
Run               : 2023-04-10_14-55-22
Platform          : x86-windows
Language          : cpp
Suite             : autosar-default
Predicate         : UnusedIncludeDirectives#574b69bc::getANonLocalDependency#1#ff
Execution_Time_Ms : 36338

Release           : v2.17.0
Run               : 2023-04-10_14-55-22
Platform          : x86-linux
Language          : c
Suite             : misra-default
Predicate         : RepeatedInitializationOfAggregateObjectElement#76b22bdc::hasMultipleInitializerExprsForSameField#2#ff
Execution_Time_Ms : 68210

Release           : v2.17.0
Run               : 2023-04-10_14-55-22
Platform          : x86-windows
Language          : cpp
Suite             : cert-default
Predicate         : SSAConstruction#2b11997e::DefUse::hasNonPhiDefinition#4#ffff
Execution_Time_Ms : 37638

Release           : v2.17.0
Run               : 2023-04-10_14-55-22
Platform          : x86-windows
Language          : cpp
Suite             : autosar-default
Predicate         : m##DataFlowUtil#7572fbec::localFlowStep#2Plus#bf
Execution_Time_Ms : 185165

Release           : v2.17.0
Run               : 2023-04-10_14-55-22
Platform          : x86-windows
Language          : cpp
Suite             : autosar-default
Predicate         : Dependency#b0c9183e::dependsOnTransitive#2#ff
Execution_Time_Ms : 224805

Release           : v2.17.0
Run               : 2023-04-10_14-55-22
Platform          : x86-windows
Language          : cpp
Suite             : autosar-default
Predicate         : SSAConstruction#2b11997e::DefUse::hasNonPhiDefinition#4#ffff
Execution_Time_Ms : 34669

Release           : v2.17.0
Run               : 2023-04-10_14-55-22
Platform          : x86-windows
Language          : c
Suite             : cert-default
Predicate         : SSAConstruction#2b11997e::PhiInsertion::definitionHasRedefinition#3#fff
Execution_Time_Ms : 36622

Release           : v2.17.0
Run               : 2023-04-10_14-55-22
Platform          : x86-windows
Language          :  [...]

2023-04-26 16:16 UTC, jeongsoolee09 commented
/test-matrix

2023-04-26 16:21 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : MissingNoExcept
COMPILE_PASS         : True
RULE                 : A15-4-4
SUITE                : AUTOSAR
PACKAGE              : Exceptions1
COMPILE_ERROR_OUTPUT : 

TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : UndocumentedUserDefinedType
COMPILE_PASS         : True
RULE                 : A2-7-3
SUITE                : AUTOSAR
PACKAGE              : Comments
COMPILE_ERROR_OUTPUT : 

TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : UselessAssignment
COMPILE_PASS         : True
RULE                 : A0-1-1
SUITE                : AUTOSAR
PACKAGE              : DeadCode
COMPILE_ERROR_OUTPUT : 

TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : OperandsOfALogicalAndOrNotParenthesized
COMPILE_PASS         : True
RULE                 : A5-2-6
SUITE                : AUTOSAR
PACKAGE              : OrderOfEvaluation
COMPILE_ERROR_OUTPUT : 


```

2023-04-26 16:21 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Exceptions1
RULE                 : A15-4-4
COMPILE_PASS         : True
TEST_PASS            : True
SUITE                : AUTOSAR
QUERY                : MissingNoExcept
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 

PACKAGE              : Comments
RULE                 : A2-7-3
COMPILE_PASS         : True
TEST_PASS            : True
SUITE                : AUTOSAR
QUERY                : UndocumentedUserDefinedType
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 

PACKAGE              : DeadCode
RULE                 : A0-1-1
COMPILE_PASS         : True
TEST_PASS            : True
SUITE                : AUTOSAR
QUERY                : UselessAssignment
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 

PACKAGE              : OrderOfEvaluation
RULE                 : A5-2-6
COMPILE_PASS         : True
TEST_PASS            : True
SUITE                : AUTOSAR
QUERY                : OperandsOfALogicalAndOrNotParenthesized
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 


```

2023-04-26 16:21 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_ERROR_OUTPUT : 
PACKAGE              : Exceptions1
QUERY                : MissingNoExcept
COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A15-4-4

COMPILE_ERROR_OUTPUT : 
PACKAGE              : Comments
QUERY                : UndocumentedUserDefinedType
COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A2-7-3

COMPILE_ERROR_OUTPUT : 
PACKAGE              : DeadCode
QUERY                : UselessAssignment
COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A0-1-1

COMPILE_ERROR_OUTPUT : 
PACKAGE              : OrderOfEvaluation
QUERY                : OperandsOfALogicalAndOrNotParenthesized
COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A5-2-6


```

2023-04-26 16:23 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-04-26 16:23 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-04-26 16:34 UTC, lcartey requested changes

2023-04-26 16:34 UTC, lcartey commented on change_notes/2023-03-15-fix-reported-fp-for-A0-1-1.md
> +- `A0-1-1` - `UselessAssignment.ql`:
We need to remove the change notes for the queries we haven't modified.

2023-04-26 19:28 UTC, jeongsoolee09 commented
/test-matrix

2023-04-26 19:29 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-04-26 19:31 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-04-26 19:31 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

TEST_PASS            : True
RULE                 : A15-4-4
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Exceptions1
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
QUERY                : MissingNoExcept
SUITE                : AUTOSAR

TEST_PASS            : True
RULE                 : A2-7-3
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Comments
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
QUERY                : UndocumentedUserDefinedType
SUITE                : AUTOSAR

TEST_PASS            : True
RULE                 : A0-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : DeadCode
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
QUERY                : UselessAssignment
SUITE                : AUTOSAR

TEST_PASS            : True
RULE                 : A5-2-6
COMPILE_ERROR_OUTPUT : 
PACKAGE              : OrderOfEvaluation
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
QUERY                : OperandsOfALogicalAndOrNotParenthesized
SUITE                : AUTOSAR


```

2023-04-26 19:33 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : True
RULE                 : A15-4-4
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Exceptions1
QUERY                : MissingNoExcept
SUITE                : AUTOSAR

COMPILE_PASS         : True
RULE                 : A2-7-3
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : Comments
QUERY                : UndocumentedUserDefinedType
SUITE                : AUTOSAR

COMPILE_PASS         : True
RULE                 : A0-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : DeadCode
QUERY                : UselessAssignment
SUITE                : AUTOSAR

COMPILE_PASS         : True
RULE                 : A5-2-6
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True
PACKAGE              : OrderOfEvaluation
QUERY                : OperandsOfALogicalAndOrNotParenthesized
SUITE                : AUTOSAR


```

2023-04-26 19:33 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

TEST_DIFFERENCE      : 
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Exceptions1
QUERY                : MissingNoExcept
RULE                 : A15-4-4
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 

TEST_DIFFERENCE      : 
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Comments
QUERY                : UndocumentedUserDefinedType
RULE                 : A2-7-3
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 

TEST_DIFFERENCE      : 
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : DeadCode
QUERY                : UselessAssignment
RULE                 : A0-1-1
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 

TEST_DIFFERENCE      : 
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : OrderOfEvaluation
QUERY                : OperandsOfALogicalAndOrNotParenthesized
RULE                 : A5-2-6
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 


```

2023-04-26 19:34 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-04-26 19:35 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-04-26 20:28 UTC, lcartey approved these changes
Good job!

2023-04-28 08:59 UTC, merged