Pass all `c++` tests when compiled with `qcc`
github/codeql-coding-standards pull request #304
Opened 2023-05-03 12:25 UTC by mbaluda

## Description
This PR fixes issues identified with matrix testing when running test cases on databases built using the `qcc` compiler. They fall under 6 categories:

### Add compiler options
`A1-1-2` `A1-1-3`

### Fix `.expected` file
`A5-0-4` `A16-2-2` `A20-8-1` `M17-0-5` `EXP60-CPP` `MEM56-CPP` 

### Fix test compilation issues
`A1-1-1` `A2-3-1` `A4-5-1` `A4-10-1` `A5-2-2` `A7-1-1` `A18-0-1` `A18-5-6` `M4-10-2` `M6-4-2`

### Fix False Negatives issues
- `A1-1-1`: restrict alerts to mentioned types
- `A5-2-5`: get type for `value_type`
- `A18-1-2` `A18-1-3` `A18-9-1`: support std inline namespaces (`std::__1`)
- `A23-0-1` `A23-0-2`: functions in `std` might be defined in inline namespaces
- `M0-1-4`: removed test case
- `M6-5-2`: equality operator alternative implementations
- `M17-0-5`: `longjmp` might be a macro
- `CTR51-CPP` `CTR53-CPP` `ERR50-CPP` `ERR52-CPP` `STR52-CPP`: fixed by library changes
- `MSC51-CPP`: `time` can be in the global scope
- `STR51-CPP`: String constructor might have 1 parameter. 

### Fix False Positives issues
- `STR53-CPP`: compute initial container size for copy constructor
- `A0-4-1`: numeric limits might be defined in `__libcpp_numeric_limits`
- `A0-4-3`: the rule now only checks the last `-std` compilation flag

### Fix exclusion criteria using the `isExcluded()` predicate
- `A2-13-3` `A8-4-4`

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [x] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [x] Queries have been modified for the following rules:
     - `A0-1-1`
     - `A0-4-1`
     - `A0-4-3`
     - `A1-1-1`
     - `A1-1-2`
     - `A1-1-3`
     - `A2-3-1`
     - `A2-13-3` 
     - `A4-5-1`
     - `A4-10-1`
     - `A5-0-4`
     - `A5-2-2`
     - `A5-2-5`
     - `A7-1-1`
     - `A8-4-4`
     - `A16-2-2`
     - `A18-0-1`
     - `A18-1-2` 
     - `A18-1-3` 
     - `A18-5-6`
     - `A18-9-1`
     - `A20-8-1`
     - `A23-0-1`
     - `A23-0-2`
     - `M0-1-4`
     - `M4-10-2`
     - `M6-4-2`
     - `M6-5-2`
     - `M17-0-5`
     - `CTR51-CPP`
     - `CTR53-CPP` 
     - `ERR50-CPP` 
     - `ERR52-CPP`
     - `EXP60-CPP`
     - `MEM56-CPP`
     - `MSC51-CPP`
     - `STR51-CPP`
     - `STR52-CPP`
     - `STR53-CPP`

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [x] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [x] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2023-05-04 15:45 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/aarch64le** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

RULE                 : A18-1-2
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : BannedTypes
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : VectorboolSpecializationUsed
COMPILE_PASS         : True

RULE                 : A18-1-3
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : BannedTypes
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : AutoPtrTypeUsed
COMPILE_PASS         : True

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
COMPILE_PASS         : True

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
COMPILE_PASS         : True

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : RegisterKeywordIsDeprecated
COMPILE_PASS         : True

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : DynamicExceptionsAreDeprecated
COMPILE_PASS         : True

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : ImplicitCopyConstructorIsDeprecated
COMPILE_PASS         : True

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
QUERY                : CStandardLibraryHeadersAreDeprecated
COMPILE_PASS         : True

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : False
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,14 +1,21 @@
                       -| StrstreamTypesAreDeprecated.cpp:4:21:4:21 | x | Use of <strstream> class 'std::strstreambuf' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:7:20:7:21 | f1 | Use of <strstream> class 'std::strstreambuf' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:12:19:12:20 | i1 | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:12:22:12:27 | call to istrstream | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:14:19:14:20 | i2 | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:14:22:14:23 | call to istrstream | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:16:19:16:20 | i3 | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:16:22:16:37 | call to istrstream | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:19:18:19:19 | f2 | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:20:10:20:31 | call to istrstream | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:24:19:24:19 | call to ostrstream | Use of <strstream> class 'std::ostrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:24:19:24:19 | o | Use of <strstream> class 'std::ostrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:27:18:27:19 | f3 | Use of <strstream> class 'std::ostrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:28:10:28:30 | call to ostrstream | Use of <strstream> class 'std::ostrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:4:21:4:21 | call to strstreambuf | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:4:21:4:21 | x | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:5:1:5:1 | call to ~strstreambuf | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:7:20:7:21 | f1 | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:8:10:8:32 | call to strstreambuf | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:12:19:12:20 | i1 | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:12:22:12:27 | call to istrstream | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:14:19:14:20 | i2 | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:14:22:14:23 | call to istrstream | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:16:19:16:20 | i3 | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:16:22:16:37 | call to istrstream | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:17:1:17:1 | call to ~istrstream | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:17:1:17:1 | call to ~istrstream | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:17:1:17:1 | call to ~istrstream | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:19:18:19:19 | f2 | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:20:10:20:31 | call to istrstream | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:24:19:24:19 | call to ostrstream | Use of <strstream> class 'std::__1::ostrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:24:19:24:19 | o | Use of <strstream> class 'std::__1::ostrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:25:1:25:1 | call to ~ostrstream | Use of <strstream> class 'std::__1::ostrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:27:18:27:19 | f3 | Use of <strstream> class 'std::__1::ostrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:28:10:28:30 | call to ostrstream | Use of <strstream> class 'std::__1::ostrstream' is deprecated. |
                       [1/1 comp 17.3s eval 2.1s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A1-1-1/StrstreamTypesAreDeprecated.qlref
                       
QUERY                : StrstreamTypesAreDeprecated
COMPILE_PASS         : True

RULE                 [...]

2023-05-05 15:24 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/aarch64le** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : BannedTypes
COMPILE_ERROR_OUTPUT : 
RULE                 : A18-1-2
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : VectorboolSpecializationUsed
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : BannedTypes
COMPILE_ERROR_OUTPUT : 
RULE                 : A18-1-3
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : AutoPtrTypeUsed
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : BannedFunctions
COMPILE_ERROR_OUTPUT : 
RULE                 : A18-9-1
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : BindUsed
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,3 +1,3 @@
                       -| test.cpp:9:13:9:21 | call to bind | Prefer lambdas to using std::bind. |
                       -| test.cpp:10:13:10:24 | call to bind1st | Prefer lambdas to using std::bind1st. |
                       -| test.cpp:11:13:11:24 | call to bind2nd | Prefer lambdas to using std::bind2nd. |
                       +| test.cpp:9:13:9:21 | call to bind | Prefer lambdas to using std::__1::bind. |
                       +| test.cpp:10:13:10:24 | call to bind1st | Prefer lambdas to using std::__1::bind1st. |
                       +| test.cpp:11:13:11:24 | call to bind2nd | Prefer lambdas to using std::__1::bind2nd. |
                       [1/1 comp 17.4s eval 1.5s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-9-1/BindUsed.qlref
                       

PACKAGE              : BannedFunctions
COMPILE_ERROR_OUTPUT : 
RULE                 : M17-0-5
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : SetjmpMacroAndTheLongjmpFunctionUsed
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,4 +1,4 @@
                        | test.cpp:7:9:7:19 | setjmp(__env) | Use of banned setjmp macro. |
                       -| test.cpp:12:3:12:9 | longjmp(__env,__val) | Use of banned longjmp function. |
                       -| test.cpp:14:3:14:9 | longjmp(__env,__val) | Use of banned longjmp function. |
                       +| test.cpp:12:3:12:19 | longjmp(__env,__val) | Use of banned longjmp function. |
                       +| test.cpp:14:3:14:19 | longjmp(__env,__val) | Use of banned longjmp function. |
                        | test.cpp:16:9:16:19 | setjmp(__env) | Use of banned setjmp macro. |
                       [1/1 comp 17s eval 968ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/M17-0-5/SetjmpMacroAndTheLongjmpFunctionUsed.qlref
                       

PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : RegisterKeywordIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : ImplicitCopyConstructorIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : DynamicExceptionsAreDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : CStandardLibraryHeadersAreDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_PASS         : True
QUERY                : StrstreamTypesAreDeprecated
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,14 +1,21 @@
                       -| StrstreamTypesAreDeprecated.cpp:4:21:4:21 | x | Use of <strstream> class 'std::strstreambuf' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:7:20:7:21 | f1 | Use of <strstream> class 'std::strstreambuf' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:12:19:12:20 | i1 | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:12:22:12:27 | call to istrstream | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:14:19:14:20 | i2 | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:14:22:14:23 | call to istrstream | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:16:19:16:20 | i3 | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:16:22:16:37 | call to istrstream | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:19:18:19:19 | f2 | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:20:10:20:31 | call to istrstream | Use of <strstream> class 'std::istrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:24:19:24:19 | call to ostrstream | Use of <strstream> class 'std::ostrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:24:19:24:19 | o | Use of <strstream> class 'std::ostrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:27:18:27:19 | f3 | Use of <strstream> class 'std::ostrstream' is deprecated. |
                       -| StrstreamTypesAreDeprecated.cpp:28:10:28:30 | call to ostrstream | Use of <strstream> class 'std::ostrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:4:21:4:21 | call to strstreambuf | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:4:21:4:21 | x | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:5:1:5:1 | call to ~strstreambuf | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:7:20:7:21 | f1 | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:8:10:8:32 | call to strstreambuf | Use of <strstream> class 'std::__1::strstreambuf' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:12:19:12:20 | i1 | Use of <strstream> class 'std::__1::istrstream' is deprecated. |
                       +| StrstreamTypesAreDeprecated.cpp:12:22:12:27 | call to istrstream | Use of <strstream> class 'std:: [...]

2023-05-05 16:54 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/aarch64le** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : True
RULE                 : A1-1-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : RegisterKeywordIsDeprecated
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
RULE                 : A1-1-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
RULE                 : A1-1-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : DynamicExceptionsAreDeprecated
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
RULE                 : A1-1-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
RULE                 : A1-1-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : ImplicitCopyConstructorIsDeprecated
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
RULE                 : A1-1-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : CStandardLibraryHeadersAreDeprecated
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
RULE                 : A1-1-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : StrstreamTypesAreDeprecated
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
RULE                 : A18-1-2
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : VectorboolSpecializationUsed
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedTypes

COMPILE_PASS         : True
RULE                 : A18-1-3
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : AutoPtrTypeUsed
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedTypes

COMPILE_PASS         : True
RULE                 : A18-9-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : BindUsed
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedFunctions

COMPILE_PASS         : True
RULE                 : M17-0-5
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : SetjmpMacroAndTheLongjmpFunctionUsed
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedFunctions

COMPILE_PASS         : True
RULE                 : A18-0-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedLibraries

COMPILE_PASS         : True
RULE                 : A18-5-6
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : DynamicMemoryManagementFailureMode
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Allocations

COMPILE_PASS         : True
RULE                 : A2-3-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : CharacterOutsideTheLanguageStandardBasicSourceCharacterSetUsedInTheSourceCode
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Naming

COMPILE_PASS         : True
RULE                 : A2-3-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : InvalidCharacterInStringLiteral
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Naming

COMPILE_PASS         : True
RULE                 : A2-3-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : InvalidCharacterInComment
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Naming

COMPILE_PASS         : True
RULE                 : A23-0-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : IteratorImplicitlyConvertedToConstIterator
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Iterators

COMPILE_PASS         : True
RULE                 : A4-10-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : NullPointerConstantNotNullptr
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Literals

COMPILE_PASS         : True
RULE                 : A4-5-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : EnumUsedInArithmeticContexts
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Expressions

COMPILE_PASS         : True
RULE                 : A5-2-2
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : TraditionalCStyleCastsUsed
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedSyntax

COMPILE_PASS         : True
RULE                 : A7-1-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : DeclarationUnmodifiedParamMissingConstSpecifier
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Const

COMPILE_PASS         : True
RULE                 : A7-1-1
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : DeclarationUnmodifiedObjectMissingConstSpecifier
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Const

COMPILE_PASS         : True
RULE                 : M0-1-4
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : SingleUseLocalPODVariable
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : DeadCode

COMPILE_PASS         : True
RULE                 : M0-1-4
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : SingleUseGlobalOrNamespacePODVariable
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : DeadCode

COMPILE_PASS         : True
RULE                 : M0-1-4
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : SingleUseMemberPODVariable
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : DeadCode

COMPILE_PASS         : True
RULE                 : M6-5-2
TEST_DIFFERENCE      : 
TEST_PASS            : True
QUERY                : NotEqualsInLoopCondition
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Loops


```

2023-05-08 15:42 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-05-08 15:44 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-05-08 15:49 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/aarch64le** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

QUERY                : DynamicExceptionsAreDeprecated
PACKAGE              : Toolchain
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : CStandardLibraryHeadersAreDeprecated
PACKAGE              : Toolchain
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : RegisterKeywordIsDeprecated
PACKAGE              : Toolchain
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
PACKAGE              : Toolchain
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
PACKAGE              : Toolchain
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : ImplicitCopyConstructorIsDeprecated
PACKAGE              : Toolchain
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : StrstreamTypesAreDeprecated
PACKAGE              : Toolchain
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : VectorboolSpecializationUsed
PACKAGE              : BannedTypes
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A18-1-2
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : AutoPtrTypeUsed
PACKAGE              : BannedTypes
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A18-1-3
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : BindUsed
PACKAGE              : BannedFunctions
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A18-9-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : SetjmpMacroAndTheLongjmpFunctionUsed
PACKAGE              : BannedFunctions
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : M17-0-5
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
PACKAGE              : BannedLibraries
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A18-0-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : DynamicMemoryManagementFailureMode
PACKAGE              : Allocations
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A18-5-6
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : CharacterOutsideTheLanguageStandardBasicSourceCharacterSetUsedInTheSourceCode
PACKAGE              : Naming
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A2-3-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : InvalidCharacterInComment
PACKAGE              : Naming
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A2-3-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : InvalidCharacterInStringLiteral
PACKAGE              : Naming
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A2-3-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : IteratorImplicitlyConvertedToConstIterator
PACKAGE              : Iterators
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A23-0-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : NullPointerConstantNotNullptr
PACKAGE              : Literals
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A4-10-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : EnumUsedInArithmeticContexts
PACKAGE              : Expressions
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A4-5-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : TraditionalCStyleCastsUsed
PACKAGE              : BannedSyntax
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A5-2-2
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : DeclarationUnmodifiedParamMissingConstSpecifier
PACKAGE              : Const
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A7-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : DeclarationUnmodifiedObjectMissingConstSpecifier
PACKAGE              : Const
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : A7-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : SingleUseLocalPODVariable
PACKAGE              : DeadCode
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : M0-1-4
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : SingleUseGlobalOrNamespacePODVariable
PACKAGE              : DeadCode
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : M0-1-4
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : SingleUseMemberPODVariable
PACKAGE              : DeadCode
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : M0-1-4
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : NotEqualsInLoopCondition
PACKAGE              : Loops
SUITE                : AUTOSAR
COMPILE_PASS         : True
RULE                 : M6-5-2
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : BadlySeededRandomNumberGenerator
PACKAGE              : Initialization
SUITE                : CERT-C++
COMPILE_PASS         : True
RULE                 : MSC51-CPP
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : UseValidIteratorRanges
PACKAGE              : Iterators
SUITE                : CERT-C++
COMPILE_PASS         : True
RULE                 : CTR53-CPP
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
TEST_PASS            : True

QUERY                : DoNotUseSetjmpOrLongjmp
PACKAGE              : BannedFunctions
SUITE                : CERT-C++
COMPILE_PASS         : True
RULE                 : ERR52-CPP
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,2 +1,1 @@
                       -| test.cpp:7:9:7:19 | setjmp(env) | Use of banned setjmp macro. |
                       -| test.cpp:12:3:12:9 | call to longjmp | Use of banned longjmp function. |
                       +| test.cpp:7:9:7:19 | setjmp(__env) | Use of banned setjmp macro. |
                       [1/1 comp 17.3s eval 919ms] FAILED(RESULT) /__w/codeql-co [...]

2023-05-08 15:51 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-05-08 15:51 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-05-08 16:00 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Toolchain
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : RegisterKeywordIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : CStandardLibraryHeadersAreDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : ImplicitCopyConstructorIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : StrstreamTypesAreDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Toolchain
RULE                 : A1-1-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : DynamicExceptionsAreDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : BannedTypes
RULE                 : A18-1-2
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : VectorboolSpecializationUsed
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -3,5 +3,4 @@
                        | test.cpp:20:8:20:9 | l3 | Use of std::vector<bool> specialization. |
                        | test.cpp:23:34:23:35 | l6 | Use of std::vector<bool> specialization. |
                        | test.cpp:24:47:24:48 | l7 | Use of std::vector<bool> specialization. |
                       -| test.cpp:27:36:27:37 | it | Use of std::vector<bool> specialization. |
                        | test.cpp:34:40:34:41 | d3 | Use of std::vector<bool> specialization. |
                       [1/1 comp 17.7s eval 1.3s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-1-2/VectorboolSpecializationUsed.qlref
                       

PACKAGE              : BannedTypes
RULE                 : A18-1-3
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : AutoPtrTypeUsed
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : BannedFunctions
RULE                 : A18-9-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : BindUsed
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : BannedFunctions
RULE                 : M17-0-5
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : SetjmpMacroAndTheLongjmpFunctionUsed
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : BannedLibraries
RULE                 : A18-0-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Allocations
RULE                 : A18-5-6
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : DynamicMemoryManagementFailureMode
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Naming
RULE                 : A2-3-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : InvalidCharacterInStringLiteral
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Naming
RULE                 : A2-3-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : CharacterOutsideTheLanguageStandardBasicSourceCharacterSetUsedInTheSourceCode
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Naming
RULE                 : A2-3-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : InvalidCharacterInComment
TEST_PASS            : True
TEST_DIFFERENCE      : 

PACKAGE              : Iterators
RULE                 : A23-0-1
SUITE                : AUTOSAR
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
QUERY                : IteratorImplicitlyConvertedToConstIterator
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,10 +1,14 @@
                       -| test.cpp:10:39:10:48 | call to __iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:10:39:10:48 | call to __normal_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:12:38:12:43 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:13:38:13:42 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:15:44:15:49 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:16:44:16:48 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:19:43:19:47 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:22:50:22:54 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:25:8:25:16 | call to __iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:19:41:19:50 | call to _Rb_tree_const_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:22:47:22:57 | call to _Rb_tree_const_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:25:8:25:16 | call to __normal_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:26:10:26:15 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:27:10:27:14 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:28:11:28:16 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:29:11:29:15 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:31:10:31:14 | call to begin | Non-const version of container call immed [...]

2023-05-08 17:55 UTC, jsinglet commented
🤖 Beep Boop! **clang/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-05-08 17:55 UTC, jsinglet commented
🤖 Beep Boop! **gcc/c/X86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-05-08 18:06 UTC, jsinglet commented
🤖 Beep Boop! **clang/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Toolchain
RULE                 : A1-1-1
QUERY                : CStandardLibraryHeadersAreDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Toolchain
RULE                 : A1-1-1
QUERY                : RegisterKeywordIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Toolchain
RULE                 : A1-1-1
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Toolchain
RULE                 : A1-1-1
QUERY                : ImplicitCopyConstructorIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Toolchain
RULE                 : A1-1-1
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Toolchain
RULE                 : A1-1-1
QUERY                : DynamicExceptionsAreDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Toolchain
RULE                 : A1-1-1
QUERY                : StrstreamTypesAreDeprecated
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : BannedTypes
RULE                 : A18-1-2
QUERY                : VectorboolSpecializationUsed
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -3,5 +3,4 @@
                        | test.cpp:20:8:20:9 | l3 | Use of std::vector<bool> specialization. |
                        | test.cpp:23:34:23:35 | l6 | Use of std::vector<bool> specialization. |
                        | test.cpp:24:47:24:48 | l7 | Use of std::vector<bool> specialization. |
                       -| test.cpp:27:36:27:37 | it | Use of std::vector<bool> specialization. |
                        | test.cpp:34:40:34:41 | d3 | Use of std::vector<bool> specialization. |
                       [1/1 comp 17.8s eval 1.4s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-1-2/VectorboolSpecializationUsed.qlref
                       
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : BannedTypes
RULE                 : A18-1-3
QUERY                : AutoPtrTypeUsed
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : BannedFunctions
RULE                 : A18-9-1
QUERY                : BindUsed
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : BannedLibraries
RULE                 : A18-0-1
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Allocations
RULE                 : A18-5-6
QUERY                : DynamicMemoryManagementFailureMode
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Naming
RULE                 : A2-3-1
QUERY                : CharacterOutsideTheLanguageStandardBasicSourceCharacterSetUsedInTheSourceCode
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Naming
RULE                 : A2-3-1
QUERY                : InvalidCharacterInComment
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Naming
RULE                 : A2-3-1
QUERY                : InvalidCharacterInStringLiteral
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
COMPILE_ERROR_OUTPUT : 
SUITE                : AUTOSAR

PACKAGE              : Iterators
RULE                 : A23-0-1
QUERY                : IteratorImplicitlyConvertedToConstIterator
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,10 +1,14 @@
                       -| test.cpp:10:39:10:48 | call to __iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:10:39:10:48 | call to __normal_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:12:38:12:43 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:13:38:13:42 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:15:44:15:49 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:16:44:16:48 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:19:43:19:47 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:22:50:22:54 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:25:8:25:16 | call to __iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:19:41:19:50 | call to _Rb_tree_const_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:22:47:22:57 | call to _Rb_tree_const_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:25:8:25:16 | call to __normal_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:26:10:26:15 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:27:10:27:14 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:28:11:28:16 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:29:11:29:15 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:31:10:31:14 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:33:12:33:16 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:31:8:31:16 | call to _Rb_tree_const_iterator | Non-const version of container call immediately converted to a `const_iterato [...]

2023-05-08 18:06 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/X86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_PASS         : True
QUERY                : RegisterKeywordIsDeprecated
SUITE                : AUTOSAR
PACKAGE              : Toolchain

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_PASS         : True
QUERY                : DynamicExceptionsAreDeprecated
SUITE                : AUTOSAR
PACKAGE              : Toolchain

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_PASS         : True
QUERY                : ImplicitCopyConstructorIsDeprecated
SUITE                : AUTOSAR
PACKAGE              : Toolchain

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_PASS         : True
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
SUITE                : AUTOSAR
PACKAGE              : Toolchain

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_PASS         : True
QUERY                : CStandardLibraryHeadersAreDeprecated
SUITE                : AUTOSAR
PACKAGE              : Toolchain

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_PASS         : True
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
SUITE                : AUTOSAR
PACKAGE              : Toolchain

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_PASS         : True
QUERY                : StrstreamTypesAreDeprecated
SUITE                : AUTOSAR
PACKAGE              : Toolchain

TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -3,5 +3,4 @@
                        | test.cpp:20:8:20:9 | l3 | Use of std::vector<bool> specialization. |
                        | test.cpp:23:34:23:35 | l6 | Use of std::vector<bool> specialization. |
                        | test.cpp:24:47:24:48 | l7 | Use of std::vector<bool> specialization. |
                       -| test.cpp:27:36:27:37 | it | Use of std::vector<bool> specialization. |
                        | test.cpp:34:40:34:41 | d3 | Use of std::vector<bool> specialization. |
                       [1/1 comp 17.6s eval 1.3s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-1-2/VectorboolSpecializationUsed.qlref
                       
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : False
RULE                 : A18-1-2
COMPILE_PASS         : True
QUERY                : VectorboolSpecializationUsed
SUITE                : AUTOSAR
PACKAGE              : BannedTypes

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A18-1-3
COMPILE_PASS         : True
QUERY                : AutoPtrTypeUsed
SUITE                : AUTOSAR
PACKAGE              : BannedTypes

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A18-9-1
COMPILE_PASS         : True
QUERY                : BindUsed
SUITE                : AUTOSAR
PACKAGE              : BannedFunctions

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A18-0-1
COMPILE_PASS         : True
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
SUITE                : AUTOSAR
PACKAGE              : BannedLibraries

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-05-08 18:00:55] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-5-6/test.cpp: In function 'void* malloc3(int)':
                       [2023-05-08 18:00:55] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-5-6/test.cpp:8:20: sorry, unimplemented: SSE instructions aren't allowed in function with no_caller_saved_registers attribute
                       [2023-05-08 18:00:55] [build-stderr]  void *malloc3(int b) { return nullptr; } // NON_COMPLIANT
                       [2023-05-08 18:00:55] [build-stderr]                     ^
                       [2023-05-08 18:00:55] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-5-6/test.cpp])
                       
TEST_PASS            : False
RULE                 : A18-5-6
COMPILE_PASS         : False
QUERY                : DynamicMemoryManagementFailureMode
SUITE                : AUTOSAR
PACKAGE              : Allocations

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A2-3-1
COMPILE_PASS         : True
QUERY                : InvalidCharacterInStringLiteral
SUITE                : AUTOSAR
PACKAGE              : Naming

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A2-3-1
COMPILE_PASS         : True
QUERY                : CharacterOutsideTheLanguageStandardBasicSourceCharacterSetUsedInTheSourceCode
SUITE                : AUTOSAR
PACKAGE              : Naming

TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A2-3-1
COMPILE_PASS         : True
QUERY                : InvalidCharacterInComment
SUITE                : AUTOSAR
PACKAGE              : Naming

TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,10 +1,14 @@
                       -| test.cpp:10:39:10:48 | call to __iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:10:39:10:48 | call to __normal_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:12:38:12:43 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:13:38:13:42 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:15:44:15:49 | call to cbegin | Non-const version of container call immediately converted to a `const_iterator`. |
                        | test.cpp:16:44:16:48 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:19:43:19:47 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:22:50:22:54 | call to begin | Non-const version of container call immediately converted to a `const_iterator`. |
                       -| test.cpp:25:8:25:16 | call to __iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:19:41:19:50 | call to _Rb_tree_const_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:22:47:22:57 | call to _Rb_tree_const_iterator | Non-const version of container call immediately converted to a `const_iterator`. |
                       +| test.cpp:25:8:25:16 | call to __normal_iterator | Non-const version of container call immediately converted to a `const_iterat [...]

2023-05-08 18:08 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/AARCH64LE** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : StrstreamTypesAreDeprecated
TEST_DIFFERENCE      : 
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : RegisterKeywordIsDeprecated
TEST_DIFFERENCE      : 
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
TEST_DIFFERENCE      : 
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
TEST_DIFFERENCE      : 
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : ImplicitCopyConstructorIsDeprecated
TEST_DIFFERENCE      : 
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : DynamicExceptionsAreDeprecated
TEST_DIFFERENCE      : 
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : CStandardLibraryHeadersAreDeprecated
TEST_DIFFERENCE      : 
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Toolchain

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : VectorboolSpecializationUsed
TEST_DIFFERENCE      : 
RULE                 : A18-1-2
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedTypes

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : AutoPtrTypeUsed
TEST_DIFFERENCE      : 
RULE                 : A18-1-3
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedTypes

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : BindUsed
TEST_DIFFERENCE      : 
RULE                 : A18-9-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedFunctions

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
TEST_DIFFERENCE      : 
RULE                 : A18-0-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedLibraries

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : DynamicMemoryManagementFailureMode
TEST_DIFFERENCE      : 
RULE                 : A18-5-6
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Allocations

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : InvalidCharacterInStringLiteral
TEST_DIFFERENCE      : 
RULE                 : A2-3-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Naming

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : InvalidCharacterInComment
TEST_DIFFERENCE      : 
RULE                 : A2-3-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Naming

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : CharacterOutsideTheLanguageStandardBasicSourceCharacterSetUsedInTheSourceCode
TEST_DIFFERENCE      : 
RULE                 : A2-3-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Naming

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : IteratorImplicitlyConvertedToConstIterator
TEST_DIFFERENCE      : 
RULE                 : A23-0-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Iterators

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : NullPointerConstantNotNullptr
TEST_DIFFERENCE      : 
RULE                 : A4-10-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Literals

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : EnumUsedInArithmeticContexts
TEST_DIFFERENCE      : 
RULE                 : A4-5-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Expressions

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : TraditionalCStyleCastsUsed
TEST_DIFFERENCE      : 
RULE                 : A5-2-2
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedSyntax

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : DeclarationUnmodifiedParamMissingConstSpecifier
TEST_DIFFERENCE      : 
RULE                 : A7-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Const

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : DeclarationUnmodifiedObjectMissingConstSpecifier
TEST_DIFFERENCE      : 
RULE                 : A7-1-1
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Const

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : SingleUseGlobalOrNamespacePODVariable
TEST_DIFFERENCE      : 
RULE                 : M0-1-4
COMPILE_ERROR_OUTPUT : 
PACKAGE              : DeadCode

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : SingleUseLocalPODVariable
TEST_DIFFERENCE      : 
RULE                 : M0-1-4
COMPILE_ERROR_OUTPUT : 
PACKAGE              : DeadCode

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : SingleUseMemberPODVariable
TEST_DIFFERENCE      : 
RULE                 : M0-1-4
COMPILE_ERROR_OUTPUT : 
PACKAGE              : DeadCode

COMPILE_PASS         : True
SUITE                : CERT-C++
TEST_PASS            : True
QUERY                : BadlySeededRandomNumberGenerator
TEST_DIFFERENCE      : 
RULE                 : MSC51-CPP
COMPILE_ERROR_OUTPUT : 
PACKAGE              : Initialization

COMPILE_PASS         : True
SUITE                : CERT-C++
TEST_PASS            : True
QUERY                : DoNotPassANonstandardObjectAcrossBoundaries
TEST_DIFFERENCE      : 
RULE                 : EXP60-CPP
COMPILE_ERROR_OUTPUT : 
PACKAGE              : TrustBoundaries

COMPILE_PASS         : True
SUITE                : CERT-C++
TEST_PASS            : True
QUERY                : DoNotUseSetjmpOrLongjmp
TEST_DIFFERENCE      : 
RULE                 : ERR52-CPP
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedFunctions

COMPILE_PASS         : True
SUITE                : AUTOSAR
TEST_PASS            : True
QUERY                : SetjmpMacroAndTheLongjmpFunctionUsed
TEST_DIFFERENCE      : 
RULE                 : M17-0-5
COMPILE_ERROR_OUTPUT : 
PACKAGE              : BannedFunctions


```

2023-05-08 20:09 UTC, jsinglet commented
🤖 Beep Boop! **qcc/c/AARCH64LE** Matrix Testing for this PR has been completed but I didn't find anything to test!

2023-05-08 20:10 UTC, jsinglet commented
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

2023-05-10 23:42 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/x86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A0-4-1
QUERY                : FloatingPointImplementationShallComplyWithIeeeStandard
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
QUERY                : RegisterKeywordIsDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
QUERY                : ImplicitCopyConstructorIsDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
QUERY                : DynamicExceptionsAreDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
QUERY                : CStandardLibraryHeadersAreDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-1
QUERY                : StrstreamTypesAreDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A17-1-1
QUERY                : CStandardLibraryFunctionCalls
PACKAGE              : Functions
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -3,5 +3,4 @@
                        | test.cpp:20:8:20:9 | l3 | Use of std::vector<bool> specialization. |
                        | test.cpp:23:34:23:35 | l6 | Use of std::vector<bool> specialization. |
                        | test.cpp:24:47:24:48 | l7 | Use of std::vector<bool> specialization. |
                       -| test.cpp:27:36:27:37 | it | Use of std::vector<bool> specialization. |
                        | test.cpp:34:40:34:41 | d3 | Use of std::vector<bool> specialization. |
                       [1/1 comp 16.9s eval 1.3s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-1-2/VectorboolSpecializationUsed.qlref
                       
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : False
RULE                 : A18-1-2
QUERY                : VectorboolSpecializationUsed
PACKAGE              : BannedTypes
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A18-1-3
QUERY                : AutoPtrTypeUsed
PACKAGE              : BannedTypes
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A18-9-1
QUERY                : BindUsed
PACKAGE              : BannedFunctions
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,1 @@
                       -| test.cpp:0:0:0:0 | test.cpp | File 'test.cpp' compiled with flag '-std=gnu++14' which does not strictly comply with ISO C++14. |
                       +
                       [1/1 comp 15.8s eval 944ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A0-4-3/CompilerImplementationShallComplyWithCPP14Standard.qlref
                       
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : False
RULE                 : A0-4-3
QUERY                : CompilerImplementationShallComplyWithCPP14Standard
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-2
QUERY                : CompilerWarningLevelNotInCompliance
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-2
QUERY                : CompilerWarningLevelNotInCompliance
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A1-1-2
QUERY                : CompilerWarningLevelNotInCompliance
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,1 @@
                       -| test.cpp:0:0:0:0 | test.cpp | No warning-level options were used in the compilation of 'test.cpp'. |
                       +
                       [1/1 eval 988ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A1-1-2.3/CompilerWarningLevelNotInCompliance.qlref
                       
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : False
RULE                 : A1-1-2
QUERY                : CompilerWarningLevelNotInCompliance
PACKAGE              : Toolchain
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-05-10 23:35:05] [build-stderr] g++: error: unrecognized command line option '-fno-signed-zeroes'; did you mean '-fno-signed-zeros'?
                       [2023-05-10 23:35:05] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, -Ofast, -ffast-math, -fgnu-keywords, -fno-signed-zeroes, -ffinite-math-only, -ffloat-store, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A1-1-3/test.cpp])
                       
TEST_PASS            : False
RULE                 : A1-1-3
QUERY                : UncompliantOptimizationOptionMustBeDisabledInCompiler
PACKAGE              : Toolchain
COMPILE_PASS         : False

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A16-2-2
QUERY                : UnusedIncludeDirectives
PACKAGE              : Includes
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
RULE                 : A18-0-1
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
PACKAGE              : BannedLibraries
COMPILE_PASS         : True

SUITE                : AUTOSAR
TEST_DIFFERENCE      : 
COMPILE_ERROR_OUTPUT : [2023-05-10 23:35:58] [build-st [...]

2023-05-11 00:17 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/x86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : FloatingPointImplementationShallComplyWithIeeeStandard
TEST_PASS            : True
RULE                 : A0-4-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : ImplicitCopyConstructorIsDeprecated
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : RegisterKeywordIsDeprecated
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : DynamicExceptionsAreDeprecated
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : CStandardLibraryHeadersAreDeprecated
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : StrstreamTypesAreDeprecated
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Functions
SUITE                : AUTOSAR
QUERY                : CStandardLibraryFunctionCalls
TEST_PASS            : True
RULE                 : A17-1-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : BannedTypes
SUITE                : AUTOSAR
QUERY                : VectorboolSpecializationUsed
TEST_PASS            : False
RULE                 : A18-1-2
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -3,5 +3,4 @@
                        | test.cpp:20:8:20:9 | l3 | Use of std::vector<bool> specialization. |
                        | test.cpp:23:34:23:35 | l6 | Use of std::vector<bool> specialization. |
                        | test.cpp:24:47:24:48 | l7 | Use of std::vector<bool> specialization. |
                       -| test.cpp:27:36:27:37 | it | Use of std::vector<bool> specialization. |
                        | test.cpp:34:40:34:41 | d3 | Use of std::vector<bool> specialization. |
                       [1/1 comp 16.8s eval 1.5s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-1-2/VectorboolSpecializationUsed.qlref
                       
COMPILE_PASS         : True

PACKAGE              : BannedTypes
SUITE                : AUTOSAR
QUERY                : AutoPtrTypeUsed
TEST_PASS            : True
RULE                 : A18-1-3
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : BannedFunctions
SUITE                : AUTOSAR
QUERY                : BindUsed
TEST_PASS            : True
RULE                 : A18-9-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : CompilerImplementationShallComplyWithCPP14Standard
TEST_PASS            : True
RULE                 : A0-4-3
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : CompilerWarningLevelNotInCompliance
TEST_PASS            : True
RULE                 : A1-1-2
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : CompilerWarningLevelNotInCompliance
TEST_PASS            : True
RULE                 : A1-1-2
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : CompilerWarningLevelNotInCompliance
TEST_PASS            : True
RULE                 : A1-1-2
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : CompilerWarningLevelNotInCompliance
TEST_PASS            : False
RULE                 : A1-1-2
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,1 @@
                       -| test.cpp:0:0:0:0 | test.cpp | No warning-level options were used in the compilation of 'test.cpp'. |
                       +
                       [1/1 eval 914ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A1-1-2.3/CompilerWarningLevelNotInCompliance.qlref
                       
COMPILE_PASS         : True

PACKAGE              : Toolchain
SUITE                : AUTOSAR
QUERY                : UncompliantOptimizationOptionMustBeDisabledInCompiler
TEST_PASS            : False
RULE                 : A1-1-3
COMPILE_ERROR_OUTPUT : [2023-05-11 00:09:39] [build-stderr] g++: error: unrecognized command line option '-fno-signed-zeroes'; did you mean '-fno-signed-zeros'?
                       [2023-05-11 00:09:39] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, -Ofast, -ffast-math, -fgnu-keywords, -fno-signed-zeroes, -ffinite-math-only, -ffloat-store, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A1-1-3/test.cpp])
                       
TEST_DIFFERENCE      : 
COMPILE_PASS         : False

PACKAGE              : Includes
SUITE                : AUTOSAR
QUERY                : UnusedIncludeDirectives
TEST_PASS            : True
RULE                 : A16-2-2
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : BannedLibraries
SUITE                : AUTOSAR
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
TEST_PASS            : True
RULE                 : A18-0-1
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
COMPILE_PASS         : True

PACKAGE              : Allocations
SUITE                : AUTOSAR
QUERY                : DynamicMemoryManagementFailureMode
TEST_PASS            : False
RULE                 : A18-5-6
COMPILE_ERROR_OUTPUT : [2023-05-11 00:10:31] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-5-6/test.cpp: In function 'void* malloc3(int)':
                       [2023-05-11 00:10:31] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-5-6/test.cpp:8:20: sorry, uni [...]

2023-05-11 00:45 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/x86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

RULE                 : A0-4-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : FloatingPointImplementationShallComplyWithIeeeStandard

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : RegisterKeywordIsDeprecated

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : ImplicitCopyConstructorIsDeprecated

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : DynamicExceptionsAreDeprecated

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : StrstreamTypesAreDeprecated

RULE                 : A1-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CStandardLibraryHeadersAreDeprecated

RULE                 : A1-1-3
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : UncompliantOptimizationOptionMustBeDisabledInCompiler

RULE                 : A17-1-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Functions
COMPILE_ERROR_OUTPUT : 
QUERY                : CStandardLibraryFunctionCalls

RULE                 : A18-1-2
SUITE                : AUTOSAR
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -3,5 +3,4 @@
                        | test.cpp:20:8:20:9 | l3 | Use of std::vector<bool> specialization. |
                        | test.cpp:23:34:23:35 | l6 | Use of std::vector<bool> specialization. |
                        | test.cpp:24:47:24:48 | l7 | Use of std::vector<bool> specialization. |
                       -| test.cpp:27:36:27:37 | it | Use of std::vector<bool> specialization. |
                        | test.cpp:34:40:34:41 | d3 | Use of std::vector<bool> specialization. |
                       [1/1 comp 16.3s eval 1.7s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-1-2/VectorboolSpecializationUsed.qlref
                       
COMPILE_PASS         : True
PACKAGE              : BannedTypes
COMPILE_ERROR_OUTPUT : 
QUERY                : VectorboolSpecializationUsed

RULE                 : A18-1-3
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : BannedTypes
COMPILE_ERROR_OUTPUT : 
QUERY                : AutoPtrTypeUsed

RULE                 : A18-9-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : BannedFunctions
COMPILE_ERROR_OUTPUT : 
QUERY                : BindUsed

RULE                 : A0-4-3
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerImplementationShallComplyWithCPP14Standard

RULE                 : A1-1-2
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerWarningLevelNotInCompliance

RULE                 : A1-1-2
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerWarningLevelNotInCompliance

RULE                 : A1-1-2
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerWarningLevelNotInCompliance

RULE                 : A1-1-2
SUITE                : AUTOSAR
TEST_PASS            : False
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,1 @@
                       -| test.cpp:0:0:0:0 | test.cpp | No warning-level options were used in the compilation of 'test.cpp'. |
                       +
                       [1/1 eval 1.2s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A1-1-2.3/CompilerWarningLevelNotInCompliance.qlref
                       
COMPILE_PASS         : True
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerWarningLevelNotInCompliance

RULE                 : A16-2-2
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : Includes
COMPILE_ERROR_OUTPUT : 
QUERY                : UnusedIncludeDirectives

RULE                 : A18-0-1
SUITE                : AUTOSAR
TEST_PASS            : True
TEST_DIFFERENCE      : 
COMPILE_PASS         : True
PACKAGE              : BannedLibraries
COMPILE_ERROR_OUTPUT : 
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders

RULE                 : A18-5-6
SUITE                : AUTOSAR
TEST_PASS            : False
TEST_DIFFERENCE      : 
COMPILE_PASS         : False
PACKAGE              : Allocations
COMPILE_ERROR_OUTPUT : [2023-05-11 00:38:37] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-5-6/test.cpp: In function 'void* malloc3(int)':
                       [2023-05-11 00:38:37] [build-stderr] /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-5-6/test.cpp:8:20: sorry, unimplemented: SSE instructions aren't allowed in function with no_caller_saved_registers attribute
                       [2023-05-11 00:38:37] [build-stderr]  void *malloc3(int b) { return nullptr; } // NON_COMPLIANT
                       [2023-05-11 00:38:37] [build-stderr]                     ^
                       [2023-05-11 00:38:37] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql/tools/linux64/preload_tracer, g++, -std=c++14, -fsyntax-only, /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/ [...]

2023-05-12 15:27 UTC, lcartey requested changes
Nice job! Nothing major, just a few suggestions.

2023-05-12 15:27 UTC, lcartey commented on cpp/autosar/test/rules/A1-1-1/CStandardLibraryHeadersAreDeprecated.cpp
> +#include <cassert>       // COMPLIANT
Why this change?

2023-05-12 15:27 UTC, lcartey commented on cpp/autosar/test/rules/A16-2-2/test.cpp.clang
> +#include <vector>   //COMPLIANT
This line is duplicated. I would also like to see a "non_compliant" std library include, if we could find one.

2023-05-12 15:27 UTC, lcartey commented on cpp/common/src/codingstandards/cpp/standardlibrary/String.qll
> +  PointerType getValueType() {
I think we could have retained the original name, as that's how it's described in the standard. The `value_type` is defined as `charT`, so technically even if we use `getValueType()` it should be `getConstValueTypePointer()`. I'll leave it up to you if you want to change it, though - not merge-blocking.

2023-05-16 18:34 UTC, jsinglet commented
🤖 Beep Boop! **qcc/cpp/aarch64le** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

TEST_DIFFERENCE      : 
RULE                 : A0-4-1
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : FloatingPointImplementationShallComplyWithIeeeStandard
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A0-4-3
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerImplementationShallComplyWithCPP14Standard
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : RegisterKeywordIsDeprecated
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : ImplicitCopyConstructorIsDeprecated
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : DynamicExceptionsAreDeprecated
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CStandardLibraryHeadersAreDeprecated
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-1
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : StrstreamTypesAreDeprecated
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-3
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : UncompliantOptimizationOptionMustBeDisabledInCompiler
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A17-1-1
SUITE                : AUTOSAR
PACKAGE              : Functions
COMPILE_ERROR_OUTPUT : 
QUERY                : CStandardLibraryFunctionCalls
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A18-1-2
SUITE                : AUTOSAR
PACKAGE              : BannedTypes
COMPILE_ERROR_OUTPUT : 
QUERY                : VectorboolSpecializationUsed
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A18-1-3
SUITE                : AUTOSAR
PACKAGE              : BannedTypes
COMPILE_ERROR_OUTPUT : 
QUERY                : AutoPtrTypeUsed
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A18-9-1
SUITE                : AUTOSAR
PACKAGE              : BannedFunctions
COMPILE_ERROR_OUTPUT : 
QUERY                : BindUsed
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-2
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerWarningLevelNotInCompliance
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-2
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerWarningLevelNotInCompliance
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-2
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerWarningLevelNotInCompliance
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A1-1-2
SUITE                : AUTOSAR
PACKAGE              : Toolchain
COMPILE_ERROR_OUTPUT : 
QUERY                : CompilerWarningLevelNotInCompliance
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A16-2-2
SUITE                : AUTOSAR
PACKAGE              : Includes
COMPILE_ERROR_OUTPUT : 
QUERY                : UnusedIncludeDirectives
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A18-0-1
SUITE                : AUTOSAR
PACKAGE              : BannedLibraries
COMPILE_ERROR_OUTPUT : 
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A18-5-6
SUITE                : AUTOSAR
PACKAGE              : Allocations
COMPILE_ERROR_OUTPUT : 
QUERY                : DynamicMemoryManagementFailureMode
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A2-3-1
SUITE                : AUTOSAR
PACKAGE              : Naming
COMPILE_ERROR_OUTPUT : 
QUERY                : InvalidCharacterInComment
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A2-3-1
SUITE                : AUTOSAR
PACKAGE              : Naming
COMPILE_ERROR_OUTPUT : 
QUERY                : InvalidCharacterInStringLiteral
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A2-3-1
SUITE                : AUTOSAR
PACKAGE              : Naming
COMPILE_ERROR_OUTPUT : 
QUERY                : CharacterOutsideTheLanguageStandardBasicSourceCharacterSetUsedInTheSourceCode
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A23-0-1
SUITE                : AUTOSAR
PACKAGE              : Iterators
COMPILE_ERROR_OUTPUT : 
QUERY                : IteratorImplicitlyConvertedToConstIterator
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A4-10-1
SUITE                : AUTOSAR
PACKAGE              : Literals
COMPILE_ERROR_OUTPUT : 
QUERY                : NullPointerConstantNotNullptr
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A4-5-1
SUITE                : AUTOSAR
PACKAGE              : Expressions
COMPILE_ERROR_OUTPUT : 
QUERY                : EnumUsedInArithmeticContexts
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A5-2-2
SUITE                : AUTOSAR
PACKAGE              : BannedSyntax
COMPILE_ERROR_OUTPUT : 
QUERY                : TraditionalCStyleCastsUsed
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A7-1-1
SUITE                : AUTOSAR
PACKAGE              : Const
COMPILE_ERROR_OUTPUT : 
QUERY                : DeclarationUnmodifiedParamMissingConstSpecifier
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : A7-1-1
SUITE                : AUTOSAR
PACKAGE              : Const
COMPILE_ERROR_OUTPUT : 
QUERY                : DeclarationUnmodifiedObjectMissingConstSpecifier
TEST_PASS            : True
COMPILE_PASS         : True

TEST_DIFFERENCE      : 
RULE                 : M0-1-4
SUITE                : AUTOSAR
PACKAGE [...]

2023-05-17 12:30 UTC, jsinglet commented
🤖 Beep Boop! **gcc/cpp/x86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

SUITE                : AUTOSAR
QUERY                : FloatingPointImplementationShallComplyWithIeeeStandard
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A0-4-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : CompilerImplementationShallComplyWithCPP14Standard
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A0-4-3
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : RegisterKeywordIsDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : IncrementOperatorWithBoolOperandIsDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : ImplicitCopyAssignmentOperatorIsDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : ImplicitCopyConstructorIsDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : CStandardLibraryHeadersAreDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : DynamicExceptionsAreDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : StrstreamTypesAreDeprecated
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : UncompliantOptimizationOptionMustBeDisabledInCompiler
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-3
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : CStandardLibraryFunctionCalls
PACKAGE              : Functions
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A17-1-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : VectorboolSpecializationUsed
PACKAGE              : BannedTypes
COMPILE_PASS         : True
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -3,5 +3,4 @@
                        | test.cpp:20:8:20:9 | l3 | Use of std::vector<bool> specialization. |
                        | test.cpp:23:34:23:35 | l6 | Use of std::vector<bool> specialization. |
                        | test.cpp:24:47:24:48 | l7 | Use of std::vector<bool> specialization. |
                       -| test.cpp:27:36:27:37 | it | Use of std::vector<bool> specialization. |
                        | test.cpp:34:40:34:41 | d3 | Use of std::vector<bool> specialization. |
                       [1/1 comp 16.6s eval 1.4s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A18-1-2/VectorboolSpecializationUsed.qlref
                       
TEST_PASS            : False
RULE                 : A18-1-2
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : AutoPtrTypeUsed
PACKAGE              : BannedTypes
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A18-1-3
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : BindUsed
PACKAGE              : BannedFunctions
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A18-9-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : TypeWcharTUsed
PACKAGE              : BannedTypes
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A2-13-3
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : FunctionReturnMultipleValueCondition
PACKAGE              : Functions
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A8-4-4
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : CompilerWarningLevelNotInCompliance
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-2
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : CompilerWarningLevelNotInCompliance
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-2
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : CompilerWarningLevelNotInCompliance
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A1-1-2
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : CompilerWarningLevelNotInCompliance
PACKAGE              : Toolchain
COMPILE_PASS         : True
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,1 +1,1 @@
                       -| test.cpp:0:0:0:0 | test.cpp | No warning-level options were used in the compilation of 'test.cpp'. |
                       +
                       [1/1 eval 947ms] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A1-1-2.3/CompilerWarningLevelNotInCompliance.qlref
                       
TEST_PASS            : False
RULE                 : A1-1-2
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : UnusedIncludeDirectives
PACKAGE              : Includes
COMPILE_PASS         : True
TEST_DIFFERENCE      : --- expected
                       +++ actual
                       @@ -1,2 +1,1 @@
                        | test.cpp:1:1:1:19 | #include "test.hpp" | Nothing in this file uses anything from "test.hpp" |
                       -| test.cpp:2:1:2:20 | #include <algorithm> | Nothing in this file uses anything from <algorithm> |
                       [1/1 comp 20.4s eval 1.8s] FAILED(RESULT) /__w/codeql-coding-standards-release-engineering/codeql-coding-standards-release-engineering/codeql-coding-standards/cpp/autosar/test/rules/A16-2-2/UnusedIncludeDirectives.qlref
                       
TEST_PASS            : False
RULE                 : A16-2-2
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : CLibraryFacilitiesNotAccessedThroughCPPLibraryHeaders
PACKAGE              : BannedLibraries
COMPILE_PASS         : True
TEST_DIFFERENCE      : 
TEST_PASS            : True
RULE                 : A18-0-1
COMPILE_ERROR_OUTPUT : 

SUITE                : AUTOSAR
QUERY                : DynamicMemoryManagementFailureMode
PACKAGE              : Allocations
COMPILE_PASS         : False
TEST_DIFFERENCE      : 
TEST_PASS            : False
RULE                 : A18-5-6
COMPILE_ERROR_OUTPUT : [...]

2023-05-22 12:26 UTC, lcartey requested changes
Only one remaining comment, otherwise looks good.

2023-05-22 12:26 UTC, lcartey commented on cpp/autosar/test/rules/A16-2-2/UnusedIncludeDirectives.expected.clang
> -| test.cpp:1:1:1:19 | #include "test.hpp" | Nothing in this file uses anything from "test.hpp" |
How come we have lost this result with clang/qcc/gcc?

2023-05-22 12:26 UTC, lcartey commented on scripts/build_test_database.py
> -res = subprocess.run(['codeql', 'version', '--format', 'json'], stdout=subprocess.PIPE)
I presume you didn't mean to commit this 😂

2023-05-22 12:26 UTC, lcartey commented on scripts/build_test_database.py
> -os.system(f"codeql database create -l cpp -s {LANGUAGE}/{STANDARD}/test/rules/{RULE} --command=\"{BUILD_COMMAND}\" databases/{RULE}+{ITERATION}@{CODEQL_VERSION}")
And this..

2023-05-22 12:45 UTC, lcartey approved these changes

2023-05-22 13:49 UTC, merged