Rule 11.4 improvements
github/codeql-coding-standards pull request #332
Opened 2023-07-29 00:10 UTC by lcartey

## Description

This pull request makes the following improvements to the query for Rule 11.4:
 * Consider `0` to be a null pointer constant (fixes https://github.com/github/codeql-coding-standards/issues/331).
 * Report the actual types and order in the error message.
 * If the result arises from a macro invocation that is not function-like, then report the macro itself. This helps reduce the overall number of results, and reduces the duplication by not reporting expansions of the same macro multiple times.
 * If the result arises from a macro invocation which is function-like we now report the macro in addition to the regular result, to aid with debugging.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [x] Queries have been modified for the following rules:
     - `RULE-11-4`

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

### Reviewer 

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [x] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [x] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

2023-09-08 14:17 UTC, lcartey commented on c/common/src/codingstandards/c/Pointers.qll
> +  e instanceof Zero
Note to self: this affects Rule 11.9, which is incorrect. `0` is a null pointer constant, but not permitted according to 11.9.

2024-04-24 13:53 UTC, knewbury01 commented on change_notes/2023-07-28-rule-11-4-improvements.md
> + - `RULE-11-4`
```suggestion
- `RULE-11-4` - `ConversionBetweenPointerToObjectAndIntegerType.ql`:
   - Fixed issue #331 - consider `0` a null pointer constant.
```

2024-04-24 13:53 UTC, knewbury01 commented on change_notes/2023-07-28-rule-11-4-improvements.md
> +   - Reduce false positives by considering `0` a null pointer constant.
```suggestion
```

2024-04-24 13:55 UTC, knewbury01 requested changes
minor comments only, otherwise looks good! @lcartey 

needs a merge resolve, 
and I think you accidentally marked the reviewer's checkboxes , not the author's ones, I agree with the completion of those, but please also mark the author ones!

2024-09-06 09:22 UTC, lcartey commented on c/common/src/codingstandards/c/Pointers.qll
> +  e instanceof Zero
I fixed the incompatibility with Rule 11.9, which didn't change the behaviour of Rule 11.9 itself. However, I did notice and fix a small issue, for which I have included a change note entry.

2024-09-06 09:23 UTC, lcartey commented
@knewbury01 this has been updated, and ready for re-review.

2024-09-11 14:36 UTC, lcartey commented
/test-matrix

2024-09-11 21:29 UTC, lcartey commented
/test-matrix

2024-09-12 12:29 UTC, lcartey commented
/test-matrix

2024-09-12 21:49 UTC, lcartey commented
/test-matrix

2024-09-25 14:04 UTC, knewbury01 approved these changes
lgtm!

2024-09-25 15:25 UTC, merged