Fixes false positives for M0-1-3.
github/codeql-coding-standards pull request #350
Opened 2023-08-23 06:51 UTC by rak3-sh

## Description

This PR fixes issue [349](https://github.com/github/codeql-coding-standards/issues/349)
Constexpr variables which are used in template instantiations are not considered "used".

### Example

```cpp

template <int t>
class CharBuffer
{
  public:
  int member[t];
  CharBuffer():member{0}{}
};

int foo()
{
  constexpr int line_length = 1024U;
  CharBuffer<line_length> buffer{}; // line_length is used here but reported as a violation for M0-1-3
  return buffer.member[0];
}
```

The fix is to conservatively check that if a template instantiation or a static assert has a constant which is equal to a local variable marked as a constexpr, then the said variable is considered as used.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [x] Queries have been modified for the following rules:
     - M0-1-3

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [x] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [x] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2023-08-29 15:36 UTC, lcartey requested changes
Thanks @rak3-sh - nice job. Just a few minor tweaks.

2023-08-30 01:52 UTC, rak3-sh commented on cpp/autosar/src/rules/M0-1-3/UnusedLocalVariable.ql
>    not exists(v.getAnAccess())
If we remove it, then a false positive is raised for the below code for mssu.
```cpp
#include <array>
using namespace std;

enum DataType : unsigned char {
    int8,
    int16,
};

template <typename... Types>
int foo()
{
  const array <DataType, sizeof...(Types)> lldts {int8};
  const array <DataType, sizeof...(Types)> llams {int16};
 
  constexpr std::size_t mssu = 64 * 1024;
    static_assert(
        (sizeof(lldts) + sizeof(llams)) <= mssu,
        "assert");
  return 0;
}

int main()
{
  foo<int>();
  return 0;
}
```

I will add this as a test case for this rule too.

2023-08-30 02:21 UTC, rak3-sh commented on rule_packages/cpp/Templates.json
> +            "description": "In limited cases, this query can raise false-positives for variables that are defined as constexpr and used in an expression to instantiate a template."
Thanks for letting me know. I've done this in : da7e015732df3533cc16913abd868b2cfbd03082

2023-08-30 02:21 UTC, rak3-sh commented on cpp/autosar/src/rules/M0-1-3/UnusedLocalVariable.ql
>    not exists(v.getAnAccess())
This test is added in da7e015732df3533cc16913abd868b2cfbd03082

2023-08-30 10:36 UTC, lcartey commented
@rak3-sh this also requires clang-format.

2023-08-30 10:37 UTC, lcartey commented on cpp/autosar/src/rules/M0-1-3/UnusedLocalVariable.ql
>    not exists(v.getAnAccess())
I believe that the modifications I suggested to `getUseCountConservatively` should avoid the false positive here (by also counting compiler generated accesses).

2023-08-30 10:38 UTC, lcartey commented on cpp/autosar/src/rules/M0-1-3/UnusedLocalVariable.ql
>    not exists(v.getAnAccess())
It looks like the test doesn't show a false positive, so I think that's demonstrated in practice. Thanks for adding the test for this!

2023-08-30 10:57 UTC, lcartey approved these changes

2023-08-30 12:02 UTC, rak3-sh commented
Applied clang-format in 7804c408d9302d4950aeb4ed95826389eb38da83

2023-08-30 15:39 UTC, merged