`A14-5-2` do not consider type members declared with using aliases.
github/codeql-coding-standards pull request #746
Opened 2024-10-15 00:52 UTC by fjatWbyT

## Description

Implement [proposal](https://github.com/github/codeql-coding-standards/issues/739#issuecomment-2409588476) to omit type members declared with using aliases in rule `A14-5-2`.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [x] Queries have been modified for the following rules:
     - `A14-5-2`

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [x] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2024-10-15 13:18 UTC, lcartey requested changes
Thanks for this! I think we can actually do better, and retain the true positive while removing the false positive in this case.

2024-10-15 13:18 UTC, lcartey commented on cpp/autosar/src/rules/A14-5-2/NonTemplateMemberDefinedInTemplate.ql
> +  not d instanceof UsingAliasTypedefType
I think we can actually do better here. In the case we want to exclude, the entire "base type" of the using alias is considered to be template parameter. So we can exclude it directly:
```suggestion
  // Exclude Using alias which refer directly to a TypeParameter
  not d.(UsingAliasTypedefType).getBaseType() instanceof TemplateParameter
```
That removes the false positive and retains the true positive.

2024-10-15 13:18 UTC, lcartey commented on cpp/autosar/test/rules/A14-5-2/test.cpp
> +  using T2 = typename template_base<int>::type; // NON_COMPLIANT[FALSE_NEGATIVE]
If you adopt my suggestion above, this will be correctly found.
```suggestion
  using T2 = typename template_base<int>::type; // NON_COMPLIANT
```

2024-10-15 13:18 UTC, lcartey commented on change_notes/2024-10-15-fix-fp-739-a14-5-2.md
> +  - Fixes #739. Omit type members declared with using aliases.
```suggestion
  - Fixes #739. Correctly detect template parameters specified in using alias base types, e.g. `using T1 = some_type<T>::Type;`.
```

2024-10-16 03:38 UTC, fjatWbyT commented
Thank you very much, @lcartey! I adopted the suggestions in the PR as well as tested it locally and it is indeed working as you indicated.

Great that it can be updated to get rid of the false positive while retaining the true positive, thanks again!

2024-10-16 09:16 UTC, lcartey approved these changes

2024-10-16 10:17 UTC, merged