`EssentialType`: Implement correct essential types for bitwise binary operators `&`, `^` and `|`.
github/codeql-coding-standards pull request #787
Opened 2024-10-28 15:49 UTC by lcartey

## Description

Fixes #786.

Implements correct behaviour for binary bitwise operators.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [x] Queries have been modified for the following rules:
     - `RULE-10-1`
     - `RULE-10-3`
     - `RULE-10-4`
     - `RULE-10-5`
     - `RULE-10-6`
     - `RULE-10-7`
     - `RULE-10-8`
     - `RULE-12-2`
 
## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [x] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [x] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2024-12-03 00:20 UTC, MichaelRFairhurst requested changes

2024-12-03 00:20 UTC, MichaelRFairhurst commented on c/misra/test/c/misra/test.c
> +  u32 & s32; // Essentially signed, int
These are essentially unsigned ints in the .expected file, which I think is correct based on c11 spec

> if the operand that has unsigned integer type has rank greater or
equal to the rank of the type of the other operand, then the operand with
signed integer type is converted to the type of the operand with unsigned
integer type.

2025-01-12 22:32 UTC, lcartey commented on c/misra/src/codingstandards/c/misra/EssentialTypes.qll
> +    not this instanceof RShiftExpr
Agreed.

2025-01-12 23:50 UTC, lcartey commented on c/misra/src/codingstandards/c/misra/EssentialTypes.qll
> +          if leftEssentialType.getSize() > rightEssentialType.getSize()
Done.

2025-01-12 23:52 UTC, lcartey commented on c/misra/src/codingstandards/c/misra/EssentialTypes.qll
> +      if
I've avoided needing to do this by refactoring the binary operation and conditional expression classes to remove the duplication that would justify these extractions. I've also introduced a `EssentiallySignedOrUnsignedType` to avoid some additional boiler plate.

2025-01-13 00:06 UTC, lcartey commented on c/misra/test/c/misra/test.c
> +  u32 & s32; // Essentially signed, int
Thanks, fixed.

2025-01-16 20:29 UTC, MichaelRFairhurst requested changes
Refactor is **\*chef's kiss**\* fantastic! Great work untangling.

Perfect except for the one straggling commented out closing brace.

2025-01-16 20:29 UTC, MichaelRFairhurst commented on c/misra/src/codingstandards/c/misra/EssentialTypes.qll
> +// }
Stray comment

2025-01-16 23:02 UTC, lcartey commented on c/misra/src/codingstandards/c/misra/EssentialTypes.qll
> +// }
Addressed.

2025-01-16 23:04 UTC, MichaelRFairhurst approved these changes

2025-01-17 02:12 UTC, merged