Implement Concurrency6 package -- split out Concurrency7
github/codeql-coding-standards pull request #791
Opened 2024-11-01 04:42 UTC by MichaelRFairhurst

## Description

Implement Concurrency6 package -- split out Concurrency7.

I had added support for `pthread_create`, and left it in. Should I enable support for pthreads in the control flow graph in `Concurrency.qll`?

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [x] Queries have been added for the following rules:
     - `DIR-5-2`
     - `DIR-5-3`
     - `RULE-12-6`
     - `RULE-21-25`
     - `RULE-22-11`
 - [ ] Queries have been modified for the following rules:
     - _rule number here_

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [ ] Yes
  - [x] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [x] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [x] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2025-01-13 10:48 UTC, lcartey requested changes
Looks good overall, thanks!

> Should I enable support for pthreads in the control flow graph in Concurrency.qll?

Either add it, or add an issue to support it. Which queries does it affect? If the change is large, then a separate PR would be better.

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/DIR-5-3/BannedDynamicThreadCreation.ql
> + *       external/misra/c/audit
We don't currently have an audit query suite - could you add one? Thanks!

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/DIR-5-3/ThreadCreatedByThread.ql
> +Function callers(Function f) { result = f.getACallToThisFunction().getEnclosingFunction() }
There's already a standard library predicate for this - `Function.calls(Function)`.

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/DIR-5-3/ThreadCreatedByThread.ql
> +class ThreadReachableFunction extends Function {
I think this would be nicer if you rewrote this as a `ThreadRoot` class, that provides accessors `getThreadCreateCall()` and `getAReachableFunction()`.

Then the query could be rewritten as:
```codeql
from ThreadRoot threadRoot, CThreadCreateCall tc
where
  not isExcluded(tc, Concurrency6Package::threadCreatedByThreadQuery()) and
  threadRoot.getAReachableFunction() = tc.getEnclosingFunction()
select tc, "Thread creation call reachable from threaded function '$@' created by call to $@.", threadRoot,
  threadRoot.getName(), threadRoot.getThreadCreateCall() as tcOriginal, tcOriginal.getTarget().getName()
```

Note, I'm also suggesting here tagging in the original `CThreadCreateCall`, so that it's easier for a user to verify that `threadRoot` is actually a threaded function.

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/RULE-12-6/AtomicAggregateObjectDirectlyAccessed.ql
> +    exists(FieldAccess fa |
Are the `atomic_..` access functions alway guaranteed to be function calls and not macros? Could we get false positives for this query if a standard library decided to implement a macro which did access a field? In general the C library can be implemented with functions or macros. Or, in practice do we expect all standard libraries to implement this using a function call?

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/RULE-12-6/AtomicAggregateObjectDirectlyAccessed.ql
> +      fa.getQualifier().getUnderlyingType().hasSpecifier("atomic") and
Technically you don't need the getUnderlyingType here

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/RULE-12-6/AtomicAggregateObjectDirectlyAccessed.ql
> +      fa.getQualifier().getUnderlyingType().(PointerType).getBaseType().hasSpecifier("atomic") and
Do we need to strip top level specifiers here?
```suggestion
      fa.getQualifier().getUnderlyingType().stripTopLevelSpecifiers().(PointerType).getBaseType().hasSpecifier("atomic") and
```

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> +        getName().regexpMatch(prefix + ["atomic_thread_fence", "atomic_signal_fence"] + suffix) and
We are generating `2 * 2 * 3 = 12` regexes, and a similar number in the other cases. I've seen with other uses of this pattern that it can cause performance problems, so I think we might be better off generating a single regex for each case.

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> +        getName().regexpMatch(prefix + ["atomic_thread_fence", "atomic_signal_fence"] + suffix) and
However we do this, lets check performance carefully.

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> +        suffix = "_explicit" and
The `.*` suffix would also capture `_explicit`, but not be handled by this case.

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> + * return the name of that cnonstant. Otherwise, simply print the node.
```suggestion
 * return the name of that constant. Otherwise, simply print the node.
```

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> +  function, function.toString()
In general prefer to use `.getName()` for functions, as `toString()` may be evaluated for all elements in the database.
```suggestion
  function, function.getName()
```

2025-01-13 10:48 UTC, lcartey commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> +    // variables and functions, things that flow further back.
What else would this be? And if we cannot determine the value for it, presumably we can't tell whether it's in violation or not?

2025-01-13 10:48 UTC, lcartey commented on c/misra/test/rules/RULE-12-6/test.c
> +  ptr_atomic_s1->x = 0; // NON-COMPLIANT
Can we add some user macro-wrapped cases?

2025-01-25 04:52 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-12-6/AtomicAggregateObjectDirectlyAccessed.ql
> +    exists(FieldAccess fa |
I **think** we don't have to worry about this in practice, for a few reasons. Here's part 2 of a very interesting [blog post from RedHat](https://developers.redhat.com/blog/2016/01/19/toward-a-better-use-of-c11-atomics-part-2#dynamic_initialization) about locking vs lock free atomics, and some of the features in `atomic.h`.

> Let's now see why the macro wouldn't be useful ... since atomic types aren't structs but basic types, the macro would ... employ some compiler magic to access the hidden mutex and value members of the struct

It seems all current atomic implementations are lock free, and a locking implementation may never exist. It's easier to make lock free atomic pointers. Additionally, an `atomic s` _is_ of type `s` so something like `s->mutex` would require extra effort to support in the language, and implementations would probably instead use a magic builtin compiler function e.g. `__get_mutex(s)` than add support for a magic `s->mutex` on an `int` type, etc.

I'm happy to make this more defensive, though, so it doesn't bite us.

2025-01-25 04:54 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-12-6/AtomicAggregateObjectDirectlyAccessed.ql
> +      fa.getQualifier().getUnderlyingType().hasSpecifier("atomic") and
Would it not be possible to have, e.g.,

```c
typedef atomic struct { ... } my_atomic_struct;

my_atomic_struct foo;
foo->bar
```

which would require `getUnderlyingType` to detect?

2025-01-25 05:06 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-12-6/AtomicAggregateObjectDirectlyAccessed.ql
> +      fa.getQualifier().getUnderlyingType().hasSpecifier("atomic") and
I see `hasSpecifier` recursively checks through typedefs, confirmed working with a test, this can indeed be removed. Thanks!

2025-01-25 06:00 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-12-6/AtomicAggregateObjectDirectlyAccessed.ql
> +      fa.getQualifier().getUnderlyingType().(PointerType).getBaseType().hasSpecifier("atomic") and
Seems like in practice, no. The extractor is stripping the specifiers in this case, I can't make it fail without (even when `getQualifier().(VariableAccess).getTarget().getUnderlingType().(PointerType)` fails).

I added it for resilience anyway.

2025-01-25 06:20 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> +        suffix = "_explicit" and
Also, prefix = "" doesn't match the above. This must have been a dead branch. Deleted.

2025-01-25 06:54 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> +        getName().regexpMatch(prefix + ["atomic_thread_fence", "atomic_signal_fence"] + suffix) and
Changed to just one regex.

This is now the slowest predicate on glfw:

```
        364ms |     2 | 203ms @ 2    | Element::ElementBase.toString/0#dispred#6e016f86@4589bave
```

2025-01-27 23:48 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> +    // variables and functions, things that flow further back.
The goal was to essentially look for proofs that the value is set correctly. All flow should track back to an explicitly correct value, something like a `BinaryOperation` should be incorrect, given that `memory_order_seq_cst` is a simple enum value.

I'm assuming, looking at this again, that this approach is inefficient. I deleted this case, but I opened https://github.com/github/codeql-coding-standards/issues/848 and simply deleted this case for now.

This gives us a false positive for `atomic_thread_fence(g1 + 1)`, which is reasonable.

2025-01-29 10:29 UTC, lcartey commented on c/misra/src/rules/RULE-21-25/InvalidMemoryOrderArgument.ql
> +    // variables and functions, things that flow further back.
> This gives us a false positive for atomic_thread_fence(g1 + 1), which is reasonable.

I think it's a false negative, rather than a false positive!

> I'm assuming, looking at this again, that this approach is inefficient. I deleted this case, but I opened #848 and simply deleted this case for now.

I don't actually think it would be too inefficient - if I recall correctly, the shared dataflow library has some optimisations enabling the use of forward or reverse flow calculations to help with this case. I think it's fine to follow up in #848, though.

2025-01-29 11:55 UTC, merged