Implement Concurrency7 package
github/codeql-coding-standards pull request #799
Opened 2024-11-18 08:03 UTC by MichaelRFairhurst

## Description

_please enter the description of your change here_

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [x] Queries have been added for the following rules:
     - RULE-9-7
     - RULE-21-26
 - [ ] Queries have been modified for the following rules:
     - _rule number here_

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [ ] Yes
  - [x] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [x] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [x] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2025-01-29 10:57 UTC, lcartey requested changes

2025-01-29 10:57 UTC, lcartey commented on c/misra/src/rules/RULE-21-26/TimedlockOnInappropriateMutexType.ql
> +select sink.getNode(), source, sink, "Call to mtx_timedlock with mutex not of type 'mtx_timed'."
Add a message link to the source - perhaps make the link `mutex` in the message? Otherwise users have to know to click into the path viewer in GitHub to see the source.

2025-01-29 10:57 UTC, lcartey commented on c/misra/src/rules/RULE-21-26/TimedlockOnInappropriateMutexType.ql
> +    getTarget().hasName("mtx_init") and
Could `mtx_init` be a macro?

2025-01-29 10:57 UTC, lcartey commented on c/misra/src/rules/RULE-9-7/UninitializedAtomicObject.ql
> +      getTarget().getName() = "__c11_atomic_init"
Is this name required by the standard? If not, we need to confirm it's used by all our supported compilers, or use a different approach (identify the function call wrapped by the macro `atomic_init`?)

2025-01-29 10:57 UTC, lcartey commented on c/misra/src/rules/RULE-9-7/UninitializedAtomicObject.ql
> +      initialization.getAddressedExpr().(VariableAccess).getTarget() = v and
Do we need to consider non-local initialization? e.g. a function that takes the address and initializes the variable?

2025-01-29 10:57 UTC, lcartey commented on rule_packages/c/Concurrency7.json
> +          "description": "Atomic objects that do not have static storage duration shall be initialized with a value or by using 'atomic_init()'.",
Consider adding an `implementation_scope` for this rule.

2025-02-11 01:00 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-21-26/TimedlockOnInappropriateMutexType.ql
> +    getTarget().hasName("mtx_init") and
It isn't in glibc or in clang stdc, but it is on FreeBSD.

Should we assume that if it is a macro, it expands to a simple wrapper function, e.g., `#define mtx_init(a, b) __f((a), (b))`? FWIW, that [isn't the case](https://github.com/bitrig/bitrig/blob/c22c5c6ebcc96092f69737815c84927b83e701be/sys/arch/arm64/include/mutex.h#L53) on FreeBSD, which passes `mutexTypeExpr` into a function call for the second arg.

2025-02-13 14:59 UTC, lcartey commented on c/misra/src/rules/RULE-21-26/TimedlockOnInappropriateMutexType.ql
> +    getTarget().hasName("mtx_init") and
Ok, let's keep it like this for now - we'll determine whether we need to expand coverage during compiler compatibility testing.

2025-02-15 05:13 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-9-7/UninitializedAtomicObject.ql
> +      getTarget().getName() = "__c11_atomic_init"
OK, I quickly authored a little library to make this easier going forward.

2025-02-15 05:21 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-9-7/UninitializedAtomicObject.ql
> +      initialization.getAddressedExpr().(VariableAccess).getTarget() = v and
I added an exception for if v is passed by address to any other function. That seems like a reasonable defense.

2025-02-18 13:22 UTC, lcartey requested changes
I like the idea of the `StdFunctionOrMacro` parameterized module, but I think we should hide it away in the library, and provide a simple interface to access a "call" of either kind.

We've previously done something similar in `CharFunctions`, so I would see us incorporating that modelling at some later date.

2025-02-18 13:22 UTC, lcartey commented on c/misra/src/rules/RULE-9-7/UninitializedAtomicObject.ql
> +    exists(StdFunctionOrMacro<C11FunctionWrapperMacro, atomicInit/0>::Call c |
I think we should encapsulate this within the `StdFunctionOrMacro` library, and expose it like this:
```cpp
class AtomicInitCall = StdFunctionOrMacro<C11FunctionWrapperMacro, atomicInit/0>::Call
```

This enables us to hide away the macro/function complexity, and provide a uniform interface for other APIs in the future.

2025-02-19 04:59 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-9-7/UninitializedAtomicObject.ql
> +    exists(StdFunctionOrMacro<C11FunctionWrapperMacro, atomicInit/0>::Call c |
Great suggestion, very much agreed, done!

2025-02-19 10:23 UTC, lcartey approved these changes

2025-02-19 11:48 UTC, merged