Add support for deviations on next line and multiple lines
github/codeql-coding-standards pull request #807
Opened 2024-12-03 12:17 UTC by lcartey

## Description

This draft PR proposes an extension of our deviations mechanism to suppress results on the next line and on multiple lines. This would make it easier to apply deviations at a broader scale.

We do this by introducing an annotation format to be used in comment markers in code starting with `DEVIATION`. The new markers are:

 - `DEVIATION(<code-identifier>)` - the deviation applies to results on the current line (duplication of existing non-annotated support, included for consistency).
 - `DEVIATION_NEXT_LINE(<code-identifier>)` - this deviation applies to results on the next line.
 - `DEVIATION_BEGIN(<code-identifier>)` - marks the beginning of a range of lines where the deviation applies.
 - `DEVIATION_END(<code-identifier>)` - marks the end of a range of lines where the deviation applies.

I'm definitely open to feedback on the naming format used here. Some considerations:

 - I avoided using `NOCODEQL` or similar as it doesn't apply to all of CodeQL - only the Coding Standards queries.
 - I wanted to include the word deviation, as this is tied to the deviations mechanism as specified in [MISRA Compliance 2020](https://misra.org.uk/app/uploads/2021/06/MISRA-Compliance-2020.pdf).
 - It should be relatively short, otherwise it becomes unwieldy to add in code.

This would address https://github.com/github/codeql-coding-standards/issues/326.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [x] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [x] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [ ] Queries have been modified for the following rules:
     - _rule number here_

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2025-02-15 02:52 UTC, MichaelRFairhurst requested changes
Fun PR to read through, very cool to see the stack as a solution for implementing pairings in an immutable context like CodeQL! Some thoughts on it since its a cool weedy coding task!

2025-02-15 02:52 UTC, MichaelRFairhurst commented on cpp/common/src/codingstandards/cpp/deviations/CodeIdentifierDeviation.qll
> +  DeviationRecord getDeviationRecord() { result = record }
should be getADeviationRecord

2025-02-15 02:52 UTC, MichaelRFairhurst commented on cpp/common/src/codingstandards/cpp/deviations/InvalidDeviationCodeIdentifier.ql
> +  exists(DeviationEnd end |
We should also report unclosed `DeviationStart`s

2025-02-15 02:52 UTC, MichaelRFairhurst commented on docs/user_manual.md
> +  long double x4; // codeql::<standard>_deviation(a-0-4-2-deviation) - COMPLIANT
should probably say `codeql::autosar_deviation` here

2025-02-17 09:31 UTC, fjatWbyT commented on cpp/common/src/codingstandards/cpp/deviations/InvalidDeviationCodeIdentifier.md
> +# Invalid deviation dode identifier
```suggestion
# Invalid deviation code identifier
```

2025-02-18 13:30 UTC, lcartey commented on cpp/common/src/codingstandards/cpp/deviations/CodeIdentifierDeviation.qll
> +  DeviationRecord getDeviationRecord() { result = record }
The intention is that a code identifier is unique to a specific deviation record, but it's not currently enforced. I've opened an issue for that here:
https://github.com/github/codeql-coding-standards/issues/861

2025-02-18 16:08 UTC, lcartey commented on cpp/common/src/codingstandards/cpp/deviations/CodeIdentifierDeviation.qll
> +    prevStack = TConsBeginStack(_, stack)
> If I'm not mistaken, this will hold for values I find counter-intuitive when foo is popped from a stack with a head of bar. I would expect record to be the top of stack but instead mkBeginStack(foo, _, TConsBeginStack(bar, _), _) holds.

I'm not sure if I fully follow. The previous call to `mkBeginStack` will enforce that all of `prevStack` is for the same deviation record - i.e. `mkBeginStack(record, file, prevStack, index - 1)` will only hold for `prevStack`s with the same `record`. The `stack` argument is then set to the tail of the `prevStack` to represent the popping, that `stack` argument will also be for the same deviation record. Does that answer your question/concern?

> Another thing I could be incorrect about. But I believe this predicate won't hold once we find an unmatched begin/end, correct? It's hard to know exactly how behavior should degrade in this case. But I might suggest that we leave the current stack unaltered, or pop whatever is on the stack, or return EmptyBeginStack(), so that at least later correctly matched pushes and pops continue to work.

This predicate still holds for unclosed begins. For example, if we had a file (`f1`) with a single begin (`b1`) for a record (`r1`) and no end, the predicate values for that file would be:
```
mkBeginStack(r1, f1, TEmptyBeginStack(), 0)
mkBeginStack(r1, f1, TConsBeginStack(b1, TEmptyBeginStack()), 1)
```
Nothing fails in this predicate, but `isDeviationRangePaired` would not hold for `b1`.

For ends, the failure state is that there's no available begins on the stack - i.e. the stack is empty. That case is handled below by propagating the empty stack to the next case. For example, if we consider a different file (`f2`) and record (`r2`), where there's an end (`e2`) without a begin, the predicate values would be:
```
mkBeginStack(r2, f2, TEmptyBeginStack(), 0)
mkBeginStack(r2, f2, TEmptyBeginStack(), 1)
```
If the file had further begins/ends that were correctly paired, those would be handled under the current scheme.

2025-02-18 16:51 UTC, lcartey commented on cpp/common/src/codingstandards/cpp/deviations/CodeIdentifierDeviation.qll
> +  TConsBeginStack(DeviationBegin begin, TBeginStack prev) {
I don't think we need to store it - the record is implied by the `DeviationBegin`, and the `TBeginStack`. The only reason to add it here would be to improve the evaluation performance, but I haven't seen that to be necessary.

2025-02-18 17:35 UTC, lcartey commented on cpp/common/src/codingstandards/cpp/deviations/CodeIdentifierDeviation.qll
> +    prevStack = TConsBeginStack(_, stack)
Ok, I've made some minor changes - is that any clearer?

2025-02-18 21:17 UTC, MichaelRFairhurst reviewed
Thanks, LGTM! Just one question left.

2025-02-18 21:17 UTC, MichaelRFairhurst commented on cpp/common/src/codingstandards/cpp/deviations/CodeIdentifierDeviation.qll
> +      mkBeginStack(begin.getRecord(), file, prev, index - 1)
I see that we're selecting DeviationBegin so this isn't true.

2025-02-18 21:17 UTC, MichaelRFairhurst commented on cpp/common/src/codingstandards/cpp/deviations/CodeIdentifierDeviation.qll
> +    prevStack = TConsBeginStack(_, stack)
Ah, I see. What I was missing is that there is a separate stack for each deviation record, rather than a stack per file. LGTM!

2025-02-18 23:04 UTC, lcartey commented on cpp/common/src/codingstandards/cpp/deviations/CodeIdentifierDeviation.qll
> +  DeviationRecord getDeviationRecord() { result = record }
Oh, you're right - let me change that. I'd forgotten I added support for multiple records through multiple arguments.

2025-02-18 23:17 UTC, lcartey commented
/test-performance

2025-03-11 04:35 UTC, fjatWbyT commented
> ```
> 
> Release                            : v2.40.0
> Platform                           : x86-linux
> Language                           : c
> [ snip ]
> Mean_Predicate_Execution_Time_Ms   : 49.33329796264856
> [ snip ]
> Mean_Query_Execution_Time_s        : 0.0493332979626485
> [ snip ]
> 
> ```

While going through the first table, I think that `Mean_Query_Execution_Time_s` is `Mean_Predicate_Execution_Time_s`.

The salient result I noticed in 807 is in the second table:

> ```
> Release           : 807
> Run               : 2025-02-18_23-18-05
> Platform          : x86-linux
> Language          : c
> Suite             : misra-default
> Predicate         : ResourceLeakAnalysis::ResourceLeakConfigSig[MutexObjectsNotAlwaysUnlocked::MutexLeakConfig]::getAnAlias/1#e76446be
> Execution_Time_Ms : 104697
> ```

2025-03-12 00:40 UTC, MichaelRFairhurst approved these changes
LGTM!

2025-03-12 00:42 UTC, MichaelRFairhurst commented
@fjatWbyT yes, good catch. That was introduced past the last release (by me!) and was fixed. Overall, esp. with that fixed, everything here looks great to me.

2025-03-12 02:17 UTC, merged