Implement Concurrency9 package on top of Concurrency8 work
github/codeql-coding-standards pull request #819
Opened 2024-12-11 01:22 UTC by MichaelRFairhurst

## Description

Implement Concurrency9 package on top of Concurrency8. **Marked as draft because Concurrency8 is not yet merged, to aid review**. When Concurrency8 lands, this PR will be closed and a PR into main will be opened.

Break apart `Concurrency.qll`.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [x] Queries have been added for the following rules:
     - `DIR-5-1`
     - `RULE-22-14`
     - `RULE-22-15`
     - `RULE-22-17`
     - `RULE-22-18`
     - `RULE-22-19`
     - `RULE-22-20`
 - [ ] Queries have been modified for the following rules:
     - _rule number here_

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [x] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [x] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2025-03-13 20:32 UTC, MichaelRFairhurst commented
Apologies @nicolaswill, didn't realize this was red. Fixed CI/CD!

2025-03-26 01:32 UTC, nicolaswill requested changes

2025-03-26 01:32 UTC, nicolaswill commented on c/common/src/codingstandards/c/SubObjects.qll
> +    result = getParent().getRootIdentity()
Should this be a call to the transitive closure of `getParent()`?
I think my gap in understanding (if I'm wrong) is whether this can be nested...

2025-03-26 01:32 UTC, nicolaswill commented on c/common/src/codingstandards/c/initialization/GlobalInitializationAnalysis.qll
> +    not exists(Function f2 | f2.calls(f)) and
This will hold for functions that are called via function pointers.

2025-03-26 01:32 UTC, nicolaswill commented on c/misra/src/rules/DIR-5-1/PossibleDataRaceBetweenThreads.ql
> +    this.calls*(aWrite.getEnclosingFunction()) and
I've been staring at this logic for a bit. Confirming: Are we assuming that `this` refers to a function that may directly call, indirectly call, or be the same as the function enclosing aWrite? A comment here would be helpful.

2025-03-26 01:32 UTC, nicolaswill commented on c/misra/src/rules/DIR-5-1/PossibleDataRaceBetweenThreads.ql
> +        " $@ not synchronized, for example from thread function $@ spawned from a loop."
```suggestion
        " $@ not synchronized from thread function $@ spawned from a loop."
```

Would remove "for example" unless necessary.

2025-03-26 01:32 UTC, nicolaswill commented on c/misra/src/rules/DIR-5-1/PossibleDataRaceBetweenThreads.ql
> +        " $@, for example from thread function $@, not synchronized with $@, for example from thread function $@."
```suggestion
        " $@ from thread function $@ is not synchronized with $@ from thread function $@."
```

2025-03-26 01:32 UTC, nicolaswill commented on c/misra/src/rules/RULE-22-17/InvalidOperationOnUnlockedMutex.ql
> +select operation, "Invalid operation on mutex '$@' not locked by the current thread",
```suggestion
select operation, "Invalid operation on mutex '$@' not locked by the current thread.",
```

2025-03-26 01:32 UTC, nicolaswill commented on c/misra/src/rules/RULE-22-18/NonRecursiveMutexRecursivelyLockedAudit.ql
> + *              that has previous may havec locked it.
```suggestion
 *              that may have previously locked it.
```

2025-03-26 01:32 UTC, nicolaswill commented on c/misra/src/rules/RULE-22-18/NonRecursiveMutexRecursivelyLockedAudit.ql
> +select n, "Mutex locked after previous $@.", coveredByLock, "already locked"
I would suggest rephrasing this to "Mutex locked after it was already $@.", coveredByLock, "previously locked"

2025-03-26 01:32 UTC, nicolaswill commented on c/misra/src/rules/RULE-22-19/ConditionVariableUsedWithMultipleMutexes.ql
> +  "Condition variable $@ associated with multiple mutexes, operation uses mutex $@ while $@ uses other mutex $@",
```suggestion
  "Condition variable $@ associated with multiple mutexes, operation uses mutex $@ while $@ uses other mutex $@.",
```

2025-03-26 01:33 UTC, nicolaswill commented on c/common/src/codingstandards/c/SubObjects.qll
> +  TObjectIndex(SubObject array) { array.getType() instanceof ArrayType }
Internal discussion [here](https://github.slack.com/archives/CPNQ6CE1L/p1742951339410399).

2025-03-26 01:37 UTC, nicolaswill commented
This is really great work... I love how the libraries are rather modular and reusable.

I've made some comments that are for the most part minor. I've verified the functionality based on your test-cases and thought of some small edge-cases... while I'm sure there are more (mainly in terms of false negatives), the rest LGTM.

Happy to merge once the smaller fixes are addressed.

2025-03-26 09:30 UTC, nicolaswill commented on c/misra/src/rules/RULE-22-20/ThreadStorageNotInitializedBeforeUse.ql
> +  "Thread specific storage pointer '$@' possibly used before initialization, from entry point function '$@'.",
```suggestion
  "Thread specific storage pointer '$@' used before initialization from entry point function '$@'.",
```
In what case might this produce false-positives leading to the use of "possibly"? If there isn't a concrete case that can be documented or handled, I would remove "possibly."

2025-03-26 09:32 UTC, nicolaswill commented on cpp/common/src/codingstandards/cpp/concurrency/LockingOperation.qll
> +      getTarget().(MemberFunction).getDeclaringType().hasQualifiedName("std", "mutex") or
Potential refactor to `getTarget().(MemberFunction).getDeclaringType().hasQualifiedName("std", ["mutex", timed_mutex", "shared_timed_mutex", "recursive_mutex", "recursive_timed_mutex"])`

2025-03-26 09:55 UTC, nicolaswill commented on c/common/src/codingstandards/c/SubObjects.qll
> +  TObjectIndex(SubObject array) { array.getType() instanceof ArrayType }
Update: this should indeed be equivalent.

2025-03-27 07:03 UTC, MichaelRFairhurst commented on c/common/src/codingstandards/c/SubObjects.qll
> +      result.(DotFieldAccess).getQualifier() = getParent().getAnAccess()
Added a comment. This is intentional, because the pointed-to object won't be part of the same block of memory.

Where I'm using this library, it might be better to support `PointerFieldAccess` and maybe add a new predicate on `SubObject` along the lines of "`isSameObject()`" or something like that. Because we probably do want to find race conditions around `x->y` across threads. However, once pointers are involved our ability to analyze plummets, so, I'm not sure if I should attempt that here. What do you think?

2025-03-27 07:09 UTC, MichaelRFairhurst commented on c/common/src/codingstandards/c/SubObjects.qll
> +    result = getParent().getRootIdentity()
I added a comment. In this case we want `x.y.z` to have a root object of just `x`. That's because the storage duration of `x` determines the storage duration of `x.y.z` etc.

2025-03-27 07:26 UTC, MichaelRFairhurst commented on c/common/src/codingstandards/c/initialization/GlobalInitializationAnalysis.qll
> +    not exists(Function f2 | f2.calls(f)) and
Good catch!

2025-03-27 07:36 UTC, MichaelRFairhurst commented on c/misra/src/rules/DIR-5-1/PossibleDataRaceBetweenThreads.ql
> +    this.calls*(aWrite.getEnclosingFunction()) and
Attempted to clarify, let me know if it still needs work!

2025-03-27 07:39 UTC, MichaelRFairhurst commented on c/misra/src/rules/RULE-22-18/NonRecursiveMutexRecursivelyLockedAudit.ql
> + *              that has previous may havec locked it.
:skull: thanks, good catch..!

2025-03-27 16:04 UTC, MichaelRFairhurst commented
Thank you Nick! This is ready for re-review!

2025-03-27 16:41 UTC, nicolaswill requested changes
I missed a small typo in my previous review. Otherwise, LGTM!

2025-03-27 16:41 UTC, nicolaswill commented on rule_packages/c/Concurrency9.json
> +          "description": "Mutex that may be initialized without mtx_recursive shall not be locked by a thread that may have previously locked it.",
```suggestion
          "description": "Mutexes that may be initialized without mtx_recursive shall not be locked by a thread that may have previously locked it.",
```

2025-03-27 17:22 UTC, nicolaswill approved these changes

2025-03-27 22:36 UTC, merged