Michaelrfairhurst/address rule amendments from amd3
github/codeql-coding-standards pull request #822
Opened 2024-12-13 01:32 UTC by MichaelRFairhurst

## Description

Address most MISRA C 2012 rule amendments in Amendment3.
    
Does not address amendments that are covered in other PRs (clarifications) or
Generics behavior. Most updates related to complex floating types. One update
related to emergent language features.

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [x] Queries have been modified for the following rules:
     - `DIR-4-6`
     - `RULE-10-1`
     - `RULE-10-3`
     - `RULE-10-4`
     - `RULE-10-5`
     - `RULE-10-7`
     - `RULE-10-8`
     - `RULE-14-1`

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [x] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [x] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [x] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

2025-01-29 11:08 UTC, lcartey requested changes
A couple of comments on the changes to emergent language features.

2025-01-29 11:08 UTC, lcartey commented on change_notes/2024-12-12-complex-floating-essential-types.md
> + - `EssentialType` - for all queries related to essential types:
I think were missing a note for the emergent language feature query.

2025-01-29 11:08 UTC, lcartey commented on cpp/common/src/codingstandards/cpp/Emergent.qll
> -  class AlignAsAttribute extends EmergentLanguageFeature, Attribute {
Did you mean to make these changes here?

2025-02-09 08:14 UTC, MichaelRFairhurst commented on cpp/common/src/codingstandards/cpp/Emergent.qll
> -  class AlignAsAttribute extends EmergentLanguageFeature, Attribute {
I did mean to, yes. This covers all the amendments that aren't blocked from amoundment3.

However, I reverted the deletion of `_Generic`, and I changed `amendments.csv` to mark the `RULE-1-4` as not yet implemented, so that we don't forget to revisit that once generics are landed.

2025-02-09 08:29 UTC, MichaelRFairhurst commented on cpp/common/src/codingstandards/cpp/Emergent.qll
> -  class AlignAsAttribute extends EmergentLanguageFeature, Attribute {
Also reverted deletions of atomics, threads, since those rules haven't been merged yet, and marked `RULE-1-4` from amendment 4 not yet implemented.

2025-02-18 23:37 UTC, lcartey approved these changes

2025-02-19 01:02 UTC, merged